### ISSUE TITLE
A better way to measure performance of SGEMM using cuBLAS backend

### ISSUE THREAD

**Issue by vitduck** [oneapi-src/oneMKL#106]
# Summary
onMKL shows underwhelmed SGEMM performance for small matrices.

# Version
oneMKL v0.2

# Environment
* HW you use: NVIDIA V100
* Backend library version: CUDA/10.2 
* OS name and version: CentOS 7.4.1708
* Compiler: Intel-llvm 2021-06-08 

# Steps to reproduce
I attached the source files required to measure the performance of sgemm (GFLOPS). 
Timing is obtained using std;:chrono. 

# Observed behavior
For m = n = k  = 4096, the observed performance is ~ 500 GFlops. In comparison, native cuBLAS archives up to 10 TFlops. 
I think one possible reason is the high cost of creating cuBLAS context under the hood.  
For native cuBLAS, the creation of context can be effectively excluded from cudaEventRecord().
Is there a better way to measure the performance of SGEMM with cuBLAS backend ? 

Thanks 
[sgemm.zip](https://github.com/oneapi-src/oneMKL/files/6629559/sgemm.zip)

**Comment by vrpascuzzi** [comment]
@vitduck,
Thanks for reporting this useful observation. Indeed, I discussed at some length with @mehdi-goli regarding this exact bottleneck. It's probably best he provides insight.

**Comment by vitduck** [comment]
Performance (Gflops): 
| n=m=k | cublas  |  oneMKL |
| -------- | ------- | --------- |  
|   1024   | 10599  |      9.1     | 
|   2048   | 11666  |     72.6    |
|   4096   | 12942  |      568    | 
|   8192   | 13836  |     3411   | 
| 16834   | 13376  |     9981   |

Cost of context creation can be offset by using sufficient large matrix. 
Assuming that the cost of context creation is constant regardless of matrix size, it can be substracted between two run. 
The performnace would be : (2*N2**3 - 2*N1**3)/(t2 - t1)/1e9 
With N2=8182, N1=4096, the performace is ~ 13 TFlops, which is quite close to native cuBLAS.  
In any case, the context creation would be negligible w.r.t walltime for serious application. 

@vrpascuzzi 
I appreciate your comments as well. If nothing else, may the issue be closed ?

**Comment by mehdi-goli** [comment]
Thanks, @mkrainiuk, and @vrpascuzzi. I had a brief chat with @mkrainiuk and we believe that caching the CUDA context for reuse should yield better performance.

**Comment by mmeterel** [comment]
@vitduck 
#107 is merged. Any chance you can try your benchmark again?

**Comment by mkrainiuk** [comment]
Please note #107 will improve time with removal of additional context creation, but we still have the main context. For main context we need to implement caching mechanism to get oneMKL performance as close to pure cuBLAS as possible.

**Comment by vitduck** [comment]
I updated the performance. 

| n=m=k | cublas  | oneMKL (0.2) | oneMKL (448e0e1) |
| ------    | ------  | -------------- | --------------------|
|  1024    | 10599 |      9.1            |            17.6             | 
|  2048    | 11666 |     72.6           |          139.7             | 
|  4096    | 12942 |     568            |        1057                |
|  8192    | 13836 |     3411          |        5258                |
| 16834   | 13376 |     9981          |      11157                |

In term of runing time per sgemm call, which are averaged over 100 repeated calls,  I see ~ 30% time reduction. 
To quantify impact of cached context, I have to check previous iterative solver implementations. 
Thanks for the patch.

**Comment by mmeterel** [comment]
> Please note #107 will improve time with removal of additional context creation, but we still have the main context. For main context we need to implement caching mechanism to get oneMKL performance as close to pure cuBLAS as possible.

@mkrainiuk Is anybody already working on caching mechanism? Can we open an issue to track it?

**Comment by mkrainiuk** [comment]
> > Please note #107 will improve time with removal of additional context creation, but we still have the main context. For main context we need to implement caching mechanism to get oneMKL performance as close to pure cuBLAS as possible.
> 
> @mkrainiuk Is anybody already working on caching mechanism? Can we open an issue to track it?

I did small experiment with global context for one function to confirm this idea, and it did work. But I don't think somebody is working on the cache implementation yet. @mmeterel do you think we can track it as this issue or we need more specific one?

**Comment by mmeterel** [comment]
> > > Please note #107 will improve time with removal of additional context creation, but we still have the main context. For main context we need to implement caching mechanism to get oneMKL performance as close to pure cuBLAS as possible.
> > 
> > 
> > @mkrainiuk Is anybody already working on caching mechanism? Can we open an issue to track it?
> 
> I did small experiment with global context for one function to confirm this idea, and it did work. But I don't think somebody is working on the cache implementation yet. @mmeterel do you think we can track it as this issue or we need more specific one?

@mkrainiuk I guess this issue is fine too, although the title of this issue does not reflect the scope of the work needed.  :)

**Comment by mmeterel** [comment]
@vitduck I opened #111 to track this issue with proper title :)

Are you ok closing this one?

**Comment by vitduck** [comment]
I am sorry for late reply. The issue can be closed. 
Once again thanks for your time.
