### ISSUE TITLE
CMake issue, -fsycl-unnamed-lambda passed to C/Fortran compiler

### ISSUE THREAD

**Issue by pghysels** [oneapi-src/oneMKL#116]
If I add
```
find_package(MKL REQUIRED)
target_link_libraries(mylib PUBLIC MKL::MKL_DPCPP)
```
in CMakeLists.txt and run CMake with `-DCMAKE_CXX_COMPILER=dpcpp`,
 then I get these errors:
```
gfortran: error: unrecognized command-line option '-fsycl-unnamed-lambda'
gcc: error: unrecognized command-line option '-fsycl-unnamed-lambda'
```
It does work when I add this ` -DCMAKE_C_COMPILER=icx  -DCMAKE_Fortran_COMPILER=ifx` when running CMake
but it still gives these warnings:
```
clang-13: warning: argument unused during compilation: '-fsycl-unnamed-lambda' [-Wunused-command-line-argument]
ifx: command line warning #10006: ignoring unknown option '-fsycl-unnamed-lambda'
```

**Comment by mkrainiuk** [comment]
@pghysels thank you for the input! I've transferred this bug into internal Intel oneMKL product bug tracking system. As it's not really related to oneMKL opensource interfaces project I will close it here, but we can update the status once we will fix it in Intel oneMKL product.

**Comment by akabalov** [comment]
Hello @pghysels!
We made changes from oneMKL side. Fixes will be available in upcoming Intel oneMKL 2021.4 release.

**Comment by pghysels** [comment]
Thanks!

**Comment by jiapei100** [comment]
Is this issue still ongoing  ??


```console
CMAKE_BUILD_TYPE: Release
 C compiler: icx was not found in PATH, using clang instead
 The CXX compiler identification is unknown
 CMake Error at CMakeLists.txt:135 (project):
   The CMAKE_CXX_COMPILER:

     dpcpp

   is not a full path and was not found in the PATH.

   Tell CMake where to find the compiler by setting either the environment
   variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
   to the compiler, or to the compiler name if it is in the PATH.

```

**Comment by mmeterel** [comment]
@jiapei100  Did you try Intel oneMKL 2021.4 release (or later) and still seeing the issue?
