### ISSUE TITLE
Please provide an open source licensed backend option

### ISSUE THREAD

**Issue by paravoid** [oneapi-src/oneMKL#12]
While oneMKL is licensed under the Apache2 license, which is an open source license (thanks for that!), to the best of my knowledge both of the currently available backends are currently licensed under proprietary, non-open-source licenses: Intel MKL is licensed under the Intel Simplified Software License, while NVIDIA cuBLAS is licensed under NVIDIA's proprietary EULA.

It'd be great if there was an alternative backend option that was open source, like e.g. OpenBLAS. Thanks for the consideration and for your efforts in this project!

**Comment by mmeterel** [comment]
Hi @paravoid Thanks for your interest and feedback on oneMKL. We will soon be adding NETLIB interface for BLAS component into oneMKL as an open source backend. If there is another backend option you are interested, please feel free to contribute to oneMKL. Thanks again for your interest.

**Comment by cdluminate** [comment]
I second this request.

**Comment by shaneastory** [comment]
We encourage you to add support for additional BLAS libraries. The project is open source, so please do your part and contribute.

**Comment by paravoid** [comment]
Was this resolved with 82b9cdc3e88de42515a20829047e718faa451339?

**Comment by mmeterel** [comment]
Hi @paravoid , Yes, we have enabled NETLIB backend for BLAS domain. Pls let us know if you have any feedback.
