### ISSUE TITLE
Building tests with both cuBLAS and cuRAND enabled hits compilation issues

### ISSUE THREAD

**Issue by npmiller** [oneapi-src/oneMKL#127]
# Summary

Trying to build the tests with both cuBLAS and cuRAND backends enabled hit compilation issues.

# Version

Using the latest version: 19c43b0f68dcaba5bc518d5becdfa0097bebfa7c

# Environment

This should be pretty straightforward to reproduce in any environment but let me know if you need more details for this section.

# Steps to reproduce

The issue happens if all of these are provided:
* `-DENABLE_CUBLAS_BACKEND=True`
* `-DENABLE_CURAND_BACKEND=True`
* `-DBUILD_FUNCTIONAL_TESTS=True`

# Observed behavior

This was discussed in #91 and https://github.com/oneapi-src/oneMKL/pull/126#discussion_r704654552, however it looks like that ticket fixed the issue for building one of them but not both of them at the same time.

`TARGET_DOMAINS` also doesn't seem to work properly with cuBLAS and cuRAND, it always gets reset here:
* https://github.com/oneapi-src/oneMKL/blob/develop/CMakeLists.txt#L108

Because it's checking the specified target domains against a domain list that is only populated when using the MKLCPU or MKLGPU backends.

I tried hacking that part of the CMake to let a `blas;rng` target domain list go through, however this still seemed to fail when building the tests.

# Expected behavior

I see two main possible outcomes for this:

* Mark this as unsupported and make CMake throw out an error if someone is trying to build this configuration
* Fix the build issue/CMake so that this combination is supported

**Comment by jinz2014** [comment]
I got the following errors

```
[  0%] Built target onemkl_rng
[  0%] Built target onemkl_blas
[  0%] Built target onemkl
[  3%] Built target onemkl_blas_cublas_obj
[  3%] Built target onemkl_blas_cublas
[  4%] Built target onemkl_rng_curand_obj
[  4%] Built target onemkl_rng_curand
[  5%] Built target gtest
[  6%] Built target gtest_main
[  6%] Building CXX object tests/unit_tests/blas/extensions/CMakeFiles/blas_extensions_ct.dir/gemm_bias.cpp.o
/tmp/oneMKL/tests/unit_tests/blas/extensions/gemm_bias.cpp:130:48: error: no matching function for call to 'gemm_bias'
  130 |                 TEST_RUN_CT_SELECT(main_queue, oneapi::mkl::blas::column_major::gemm_bias, transa,
      |                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/oneMKL/tests/unit_tests/blas/extensions/../../include/test_helper.hpp:191:53: note: expanded from macro 'TEST_RUN_CT_SELECT'
  191 |                 TEST_RUN_NVIDIAGPU_CURAND_SELECT(q, func, __VA_ARGS__);    \
      |                                                     ^~~~
/tmp/oneMKL/tests/unit_tests/blas/extensions/../../include/test_helper.hpp:107:5: note: expanded from macro 'TEST_RUN_NVIDIAGPU_CURAND_SELECT'
  107 |     func(oneapi::mkl::backend_selector<oneapi::mkl::backend::curand>{ q }, __VA_ARGS__)
      |     ^~~~
/tmp/oneMKL/tests/unit_tests/blas/extensions/gemm_bias.cpp:170:24: note: in instantiation of function template specialization '(anonymous namespace)::test<float, signed char, signed char, int>' requested here
  170 |     EXPECT_TRUEORSKIP((test<float, int8_t, int8_t, int32_t>(
      |                        ^
/tmp/oneMKL/include/oneapi/mkl/blas/detail/blas_ct_backends.hxx:485:20: note: candidate function not viable: no known conversion from 'backend_selector<oneapi::mkl::backend::curand aka 5>' to 'backend_selector<backend::mklcpu aka 0>' for 1st argument
  485 | static inline void gemm_bias(backend_selector<backend::BACKEND> selector, transpose transa,
      |                    ^         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/oneMKL/include/oneapi/mkl/blas/detail/blas_ct_backends.hxx:485:20: note: candidate function not viable: no known conversion from 'backend_selector<oneapi::mkl::backend::curand aka 5>' to 'backend_selector<backend::mklgpu aka 1>' for 1st argument
  485 | static inline void gemm_bias(backend_selector<backend::BACKEND> selector, transpose transa,
      |                    ^         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/oneMKL/include/oneapi/mkl/blas/detail/blas_ct_backends.hxx:485:20: note: candidate function not viable: no known conversion from 'backend_selector<oneapi::mkl::backend::curand aka 5>' to 'backend_selector<backend::rocblas aka 7>' for 1st argument
  485 | static inline void gemm_bias(backend_selector<backend::BACKEND> selector, transpose transa,
      |                    ^         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                      
```

**Comment by jinz2014** [comment]
@andrewtbarker   Could you please take a look at the issue reported in 2021 ?

**Comment by andrewtbarker** [comment]
@vrpascuzzi @aelizaro Is this easy to fix or should we just document that we do not support this combination?

**Comment by vrpascuzzi** [comment]
@andrewtbarker It's been a few years since I worked on this, but IMO the combination should be supported.

Can the libraries be linked and used together in an application? (Are the tests faulty?)
