### ISSUE TITLE
Building problems

### ISSUE THREAD

**Issue by ducbueno** [oneapi-src/oneMKL#14]
Hello.

I'm getting the following error in the building process, more specifically in the first `cmake` command.

`CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find CBLAS (missing: CBLAS_file)`

I have built lapack from the link listed in the dependencies section of the instructions.

Does anyone know how I can fix this?

**Comment by vmalia** [comment]
@ducbueno Can you please post your build command? Did you define REF_BLAS_ROOT in your CMake command?

**Comment by ducbueno** [comment]
@vmalia I did define `REF_BLAS_ROOT` in my `cmake` command. I tried two ways:

1) Installing lapack as instructed in its Git (that is, installing it at `$HOME/.local`) and running the following `cmake` command:

`cmake .. -DREF_BLAS_ROOT=/home/ducbueno/.local/lapack`

2) Installing lapack with root privileges and running the following `cmake` command:

`cmake .. -DREF_BLAS_ROOT=/usr/local/lib` (I'm not sure if this is correct though. I tried it since the lapack libraries were installed in this directory.)

**Comment by NadyaTen** [comment]
Hello,
Cmake is looking for libcblas.so, libblas.so files. Do you have them in REF_BLAS_ROOT (REF_BLAS_ROOT/lib, REF_BLAS_ROOT/lib64) directory? 

And btw, are you using latest revision of master?

**Comment by vmalia** [comment]
> `cmake .. -DREF_BLAS_ROOT=/usr/local/lib` (I'm not sure if this is correct though. I tried it since the lapack libraries were installed in this directory.)

@ducbueno 
Can you try `cmake .. -DREF_BLAS_ROOT=/usr/local` ? Since correct path to REF_BLAS_ROOT is the path that contains lib folder, which in-turn contains libblas.so and libcblas.so as mentioned by @NadyaTen 

Same applies to other dependency variables. You can check the Find<module>.cmake file in cmake/ directory of the project too, if you get undefined variable errors.

**Comment by ducbueno** [comment]
Something is not adding up here. By following the installation instructions on the lapack Git (https://github.com/Reference-LAPACK/lapack) I get only the libblas.a and liblapack.a files.

When I run `sudo find / -name 'libcblas.so'` and `sudo find / -name 'libblas.so'` I get nothing.

Is there any other way of installing these libraries? I'm running Ubuntu by the way.

And @NadyaTen I think I'm using the latest revision, I cloned from the following link: https://github.com/oneapi-src/oneMKL.git

**Comment by ducbueno** [comment]
I was able to install libblas.so with `sudo apt-get install libblas-dev`, but still no results for `sudo find / -name 'libcblas.so'`.

**Comment by vmalia** [comment]
@ducbueno 
Can you try the command with an additional CMake definition "-DBUILD_SHARED_LIBS=ON"? By default LAPACK build system sets it to OFF (line 48 of https://github.com/Reference-LAPACK/lapack/blob/master/CMakeLists.txt), which is why you only get *.a static libraries.

**Comment by ducbueno** [comment]
@vmalia thanks a lot! That solved the issue.

I'm still very new to CMake, so that was not obvious at all to me.

**Comment by vmalia** [comment]
> @vmalia thanks a lot! That solved the issue.
> 
> I'm still very new to CMake, so that was not obvious at all to me.

Happy to help and glad to have you here :)
Closing the issue now.
