### ISSUE TITLE
Add several working examples

### ISSUE THREAD

**Issue by mkrainiuk** [oneapi-src/oneMKL#148]
# Summary
Provide several examples that can be built and run.

# Problem statement
As it was mentioned in #142, [readme](https://github.com/oneapi-src/oneMKL#support-and-requirements) example section doesn't cover all link lines and it does not reflect all latest changes in compilers behavior. At least one or two full examples that users can build and execute will improve the experience with the project. And also regular testing could show if examples need to be updated in case there is some changes in the latest compilers.

# Preferred solution
Add examples folder with several examples and include them to the main build system.

**Comment by mmeterel** [comment]
@mcao59  Can we close this issue?

**Comment by mmeterel** [comment]
> @mcao59 Can we close this issue?

@mcao59 ping

**Comment by mmeterel** [comment]
The examples are added. Closing.
