### ISSUE TITLE
ROCm/HIP backend support for oneMKL BLAS domain

### ISSUE THREAD

**Issue by TejaX-Alaghari** [oneapi-src/oneMKL#160]
The current CUDA backend for BLAS domain seems to utilize "CL/sycl/backends/cuda.hpp" (cublas_scope_handle.hpp) to communicate with the CUDA runtime. But there doesn't seem to be any such equivalent header file on the "CL/sycl/backends" folder for supporting ROCm/HIP backend.

Given the context, what is the recommended way to add ROCm/HIP backend support for oneMKL domain libs?

**Comment by mmeterel** [comment]
Hi @TejaX-Alaghari Thanks for your question. For ROCm backend, there are two on-going projects. 

1. hipSYCL team is enabling ROCm backend support. See #144 
2. In parallel, there is an experiential work to add HIP backend support to DPC++. (https://github.com/intel/llvm/blob/sycl/sycl/doc/GetStartedGuide.md#build-dpc-toolchain-with-support-for-hip-amd) Once this work is complete, there is a plan to add ROCm support to oneMKL through DPC++ as well. 

Hope this answers your question.

**Comment by mmeterel** [comment]
Closing issue. Please let us know if there are more questions.
