### ISSUE TITLE
[CUDA] map cublasGemmEx to SYCL

### ISSUE THREAD

**Issue by zjin-lcf** [oneapi-src/oneMKL#168]
Is there a MKL function that is similar to the cublasGemmEx function ? 

Thanks

**Comment by mmeterel** [comment]
@zjin-lcf  What A./B/C precisions are you interested? oneMKL functions `gemm` and `gemm_bias` cover many precisions combinations.

**Comment by zjin-lcf** [comment]
8-bit integer GEMM.  Please see the example: https://github.com/zjin-lcf/HeCBench/blob/master/gemmEx-cuda/main.cu

Thanks.

**Comment by mmeterel** [comment]
Can you try `gemm_bias` with A/B/C = int8_t/int8_t/int32_t?

**Comment by zjin-lcf** [comment]
Ok. I will try.

**Comment by zjin-lcf** [comment]
Is it a good idea to merge gemm_bias with gemm, like cuda's gemm function ? Should I open a request for such function ?

**Comment by zjin-lcf** [comment]
I added the sycl version with mkl gemm and gemm_bias functions. 
https://github.com/zjin-lcf/HeCBench/tree/master/gemmEx-sycl
Executing the gemm_bias fails. This may be expected.

**Comment by mmeterel** [comment]
> Is it a good idea to merge gemm_bias with gemm, like cuda's gemm function ? Should I open a request for such function ?

@zjin-lcf  In this project, we are following the APIs given in [oneAPI spec](https://spec.oneapi.io/versions/latest/elements/oneMKL/source/domains/blas/gemm_bias.html#onemkl-blas-gemm-bias). We would like to keep `gemm_bias `and `gemm `as separate APIs since their underlying functionality is different due to offsets.

**Comment by mmeterel** [comment]
> I added the sycl version with mkl gemm and gemm_bias functions. https://github.com/zjin-lcf/HeCBench/tree/master/gemmEx-sycl Executing the gemm_bias fails. This may be expected.

Could you please clarify if this is a question or an issue with the repo?
