### ISSUE TITLE
oneMKL support for DFT and VM on CUDA devices

### ISSUE THREAD

**Issue by zslavens** [oneapi-src/oneMKL#182]
Hello,
I was recently able to build oneMKL, and noted the support for optimized linear algebra (BLAS/LAPACK) and random number generation (RNG) compatible with Nvidia GPU backend.  I am interested in your plans to incorporate other domains of oneMKL, and am specifically looking for optimized support for discrete Fourier transform (DFT) and vector math (VM) functionality.  These would presumably be backed by cuFFT/cuFFTW and CUDA Math Libraries, similar to the existing oneMKL BLAS being backed by Nvidia cuBLAS.

Thank you!

**Comment by mmeterel** [comment]
@zslavens Thanks for your feedback. As mentioned in #27, adding DFT (and similarly VM) functionality to oneMKL interfaces project is part of our future plans. We will update #27 when the functionality is enabled. 
I will close this issue since it is covered by another one.
