### ISSUE TITLE
cublasSgeam question

### ISSUE THREAD

**Issue by zjin-lcf** [oneapi-src/oneMKL#183]
I have a question about MKL. Which SYCL function should be called for mapping cublasSgeam ?
https://docs.nvidia.com/cuda/cublas/index.html#cublas-lt-t-gt-geam

Thanks

**Comment by vmalia** [comment]
@mmeterel , can you help with this question? Thanks!

**Comment by mmeterel** [comment]
@zjin-lcf  Thanks for the question. 
`cublasSgeam `can be mapped to `omatadd `function. However, this function is currently not supported in oneMKL interfaces repo. We plan to add it in Q2. 

If you are trying to use it with oneMKL product, then, support for `omatadd` will be added in the next release. However, you can still achieve same functionality by using `omatadd_batch `API with batch_size=1. `omatadd_batch `is already supported in latest oneMKL product. 

Let me know if you have further questions.

**Comment by zjin-lcf** [comment]
Thank you for your answer. Could it be part of Intel oneMKL BLAS Routines for Data Parallel C++ ?

**Comment by mmeterel** [comment]
`omatadd_batch `is already part of Intel oneMKL binary product (inside BLAS). Unfortunately, the documentation is currently missing - but will be available very soon. You should be able to see the symbol in public header files. 
`omatadd `will be available in next Intel oneMKL binary product  (inside BLAS).

**Comment by zjin-lcf** [comment]
I look forward to the documentation to understand how the function is called for execution on a GPU.  Like the gemm(buffer/USM) example shown in 
https://www.intel.com/content/www/us/en/develop/documentation/oneapi-mkl-dpcpp-developer-reference/top/blas-and-sparse-blas-routines/blas-level-3-routines/gemm.html

Thanks

**Comment by mmeterel** [comment]
Closing the issue.

**Comment by mmeterel** [comment]
@zjin-lcf  Documentation for `omatadd_batch` is available here: 
https://www.intel.com/content/www/us/en/develop/documentation/oneapi-mkl-dpcpp-developer-reference/top/blas-routines/blas-like-extensions/omatadd_batch.html

**Comment by zjin-lcf** [comment]
On an Intel 0x56a0 device, the execution time of the function is long compared to the serial time. If the program is not written properly, please let me know. https://github.com/zjin-lcf/HeCBench/blob/master/geam-sycl/main.cpp

```
./main 16384 16384 4
----------------
FP32 transpose matrix (16384 x 16384)
----------------
serial transpose time = 4291.419783 (ms)
Average device transpose time = 2599792.662484 (us)
PASS
```

On a RTX3090 device
```
----------------
FP32 transpose matrix (16384 x 16384)
----------------
serial transpose time = 3982.541913 (ms)
Average device transpose time = 2577.705122 (us)
PASS
```

**Comment by mmeterel** [comment]
@zjin-lcf Looks like you are using Intel® Arc ™ A770 Graphics (DG2). Are you using same benchmark code for both GPU runs?

In your benchmark code, I realized you don't have any warmup calls. Can you please copy this [loop](https://github.com/zjin-lcf/HeCBench/blob/ae10980107ceab76a04553e0a2667b8ba5a15938/geam-sycl/main.cpp#L43) and run it for 2-3 times before starting the real timing? This will help with excluding the program/kernel creating time.

In terms of performance, tagging @andrewtbarker for omatadd_batch.

**Comment by zjin-lcf** [comment]
I evaluated the SYCL program on the Intel device and the CUDA program on the Nvidia device. Thank you for the suggestion on the programs.  I appreciate your investigation.

**Comment by andrewtbarker** [comment]
Here's what I see on an Arc A770:
```
./issue 16384 16384 4
----------------FP32 transpose matrix (16384 x 16384)----------------
Host: serial matrix transpose time = 3352.432679 (ms)
Device: average matrix transpose time = 2537.045089 (ms)
PASS
```
If the units in your output are correct (ms versus us), this is similar to what you see, and the device time is faster. What are you expecting?

**Comment by andrewtbarker** [comment]
It looks like your case is a pure transpose operation, which you can also do with the [omatcopy](https://www.intel.com/content/www/us/en/docs/onemkl/developer-reference-dpcpp/2023-0/omatcopy.html) function. For me this is providing better performance in your benchmark code:
```
./issue 16384 16384 4
----------------FP32 transpose matrix (16384 x 16384)----------------
Host: serial matrix transpose time = 3560.097326 (ms)
Device: average matrix transpose time = 36.434860 (ms)
PASS
```
I just replace the omatadd_batch call with this:
```cpp
        status = oneapi::mkl::blas::row_major::omatcopy(
            q,
            oneapi::mkl::transpose::trans,
            nrow,
            ncol,
            alpha,
            d_matrix,
            ncol,
            d_matrixT,
            nrow);
```

**Comment by zjin-lcf** [comment]
Please see the execution time of the CUDA program on a GPU

RTX2070
Measured bandwidth: 402074 MB/s

./main 16384 16384 200
Device: average matrix transpose time = 5.848160 (ms)

**Comment by zjin-lcf** [comment]
> It looks like your case is a pure transpose operation, which you can also do with the [omatcopy](https://www.intel.com/content/www/us/en/docs/onemkl/developer-reference-dpcpp/2023-0/omatcopy.html) function. For me this is providing better performance in your benchmark code:
> 
> ```
> ./issue 16384 16384 4
> ----------------FP32 transpose matrix (16384 x 16384)----------------
> Host: serial matrix transpose time = 3560.097326 (ms)
> Device: average matrix transpose time = 36.434860 (ms)
> PASS
> ```
> 
> I just replace the omatadd_batch call with this:
> 
> ```c++
>         status = oneapi::mkl::blas::row_major::omatcopy(
>             q,
>             oneapi::mkl::transpose::trans,
>             nrow,
>             ncol,
>             alpha,
>             d_matrix,
>             ncol,
>             d_matrixT,
>             nrow);
> ```

I didn't know the function. Thanks.
