### ISSUE TITLE
Cannot compile oneMKL application when the sycl/sycl.hpp is used in user code

### ISSUE THREAD

**Issue by sbalint98** [oneapi-src/oneMKL#193]
# Summary
When using oneMKL with the hipSYCL backend the user will probably include the `sycl/sycl.hpp` header. This will result in ambiguous namespace definitions.

# Version
oneMKL latest with #191 applied
The last good version was probably: 560a2e32bbb0c190af6ca18198961837cb110c8e

# Environment
hipSYCL latest, with cuda backend, although the issue is most likely present with all the backends of hipSYCL and potentially with intel LLVM.

# Steps to reproduce
Compile the following simple test program:
```
#include "oneapi/mkl.hpp"
#include <sycl/sycl.hpp>

int main() {
  auto cpu_dev = sycl::device(sycl::cpu_selector());
  sycl::queue cpu_queue(cpu_dev);
}
```
with the syclcc invocation of:
`/opt/hipSYCL/bin/syclcc --hipsycl-targets="omp" -I /opt/onemkl/include/ -L /opt/onemkl/lib/  test.cpp `

# Observed behavior
the compilation fails with:
```
test.cpp:6:18: error: reference to 'sycl' is ambiguous
  auto cpu_dev = sycl::device(sycl::cpu_selector());
                 ^
/opt/hipSYCL/bin/../include/sycl/sycl.hpp:33:11: note: candidate found by name lookup is 'sycl'
namespace sycl {
          ^
/opt/hipSYCL/bin/../include/CL/sycl.hpp:34:11: note: candidate found by name lookup is 'cl::sycl'
namespace sycl {
          ^

```

# Expected behavior
Compiles successfully

**Comment by sbalint98** [comment]
A possible solution could be to wrap all inclusion of the CL/sycl.hpp header in oneMKL with the following:
```
#if __has_include(sycl/sycl.hpp) 
#include <sycl/sycl.hpp>
#else 
#include <CL/sycl.hpp>
#endif 
````
If this solution is agreed on, would it be preferable, to replace it everywhere, or to rather try to minimize the number of occurrences of inclusions of the SYCL header before applying this change? I believe one include in the types.hpp could be sufficient for the entire project, however, this would need coordination with all domains. 

note that this will only work of #192 is also merged

**Comment by mmeterel** [comment]
@sbalint98 Could you please provide all the requirement environment variables and compiler flags to be able to reproduce this error? If I follow the steps provided, I get:
syclcc fatal error: Required command line argument --hipsycl-cpu-cxx or environment variable HIPSYCL_CPU_CXX not specified

**Comment by mmeterel** [comment]
@sbalint98 #199 is merged. Could you please check if this issue still exists or not?

**Comment by sbalint98** [comment]
Problem seems to be resolved now, thank you for the PR!

**Comment by mmeterel** [comment]
> Problem seems to be resolved now, thank you for the PR!

Thanks for checking. Can you please let me know to reproduce the issue for future reference?

**Comment by sbalint98** [comment]
Based on your error message I think the problem is that `syclcc` cannot find the `syclcc.json` configuration file, which contains presets for multiple variables including the one it complains about. I haven't seen this error before with hipSYCL that is otherwise functional, are you sure that you are using the `syclcc` in the install directory? 

I could reproduce the exact same error by using `syclcc` that has not been installed.

**Comment by mmeterel** [comment]
@sbalint98 Yes, the problem was, I was not using the syclcc in the install directory. After using the right version, I could also verify the fix. Thanks.
