### ISSUE TITLE
[hipSYCL][CUDA][CMake] redefinition of 'sycl' as different kind of symbol

### ISSUE THREAD

**Issue by ajaypanyala** [oneapi-src/oneMKL#198]
Building `oneMKL` with `hipSYCL` as follows

`
cmake -DCMAKE_CXX_COMPILER=$hipSYCL_ROOT/bin/syclcc-clang  -DCUDA_TOOLKIT_ROOT_DIR=$NV_HOME -DENABLE_CUBLAS_BACKEND=ON  -DENABLE_MKLCPU_BACKEND=OFF -DENABLE_NETLIB_BACKEND=OFF -DENABLE_MKLGPU_BACKEND=OFF -DENABLE_ROCBLAS_BACKEND=OFF -DBUILD_FUNCTIONAL_TESTS=OFF -DCMAKE_INSTALL_PREFIX=$oneMKL_HOME -DHIPSYCL_TARGETS="cuda:sm_80" -DONEMKL_SYCL_IMPLEMENTATION=hipSYCL -DTARGET_DOMAINS=blas -DCMAKE_CXX_FLAGS_INIT="--hipsycl-targets="cuda:sm_80"" -DCMAKE_PREFIX_PATH=$CUBLAS_PATH/lib -DOPENCL_INCLUDE_DIR=$CUDA_HOME/include
`

The configure step goes smoothly, but the build step gives the following errors:

```
Consolidate compiler generated dependencies of target onemkl_blas_cublas_obj
[ 30%] Building CXX object bin/blas/backends/cublas/CMakeFiles/onemkl_blas_cublas_obj.dir/cublas_level1.cpp.o
In file included from /global/homes/p/panyala/code/oneMKL/src/blas/backends/cublas/cublas_level1.cpp:20:
/global/homes/p/panyala/code/oneMKL/src/blas/backends/cublas/cublas_task.hpp:13:11: error: redefinition of 'sycl' as different kind of symbol
namespace sycl {
          ^
/global/homes/p/panyala/code/oneMKL/include/oneapi/mkl/types.hpp:27:11: note: previous definition is here
namespace sycl = cl::sycl;
          ^
```

Commenting [this](https://github.com/oneapi-src/oneMKL/blob/develop/src/blas/backends/cublas/cublas_task.hpp#L13) line (and L15) results in a successful build though. Not sure if this change really needs to be made or if I missed something. Am building `hipSYCL` with `CUDA` support using `Clang` as described [here](https://github.com/illuhad/hipSYCL/blob/develop/doc/install-cuda.md#if-using-clang)

**Comment by mmeterel** [comment]
@ajaypanyala Thanks for the question. This issue looks related to  #193 . We are currently working on a fix for it. 

Moreover, CUDA backend support with hipSYCL is not currently officially supported in oneMKL interfaces repo. Please see [README.md](https://github.com/oneapi-src/oneMKL/blob/develop/README.md) There is an open PR and it will be tested after fixing #193.

**Comment by ajaypanyala** [comment]
@mmeterel Thanks! Will wait until the open PR is merged. Closing the issue.
