### ISSUE TITLE
Why SYCL is a must fof this oneMKL? Instead of CUDA support?

### ISSUE THREAD

**Issue by jiapei100** [oneapi-src/oneMKL#205]
How can I build **oneMKL** with **CUDA** under Ubuntu 22.04 ? Without using **SYCL** ?

**Comment by Sholde** [comment]
Hello @jiapei100,

I will try to answer your questions.

> How can I build oneMKL with CUDA under Ubuntu 22.04 ?

To build oneMKL with CUDA, you just need to follow the [build instructions](https://github.com/oneapi-src/oneMKL/blob/develop/docs/building_the_project.rst#building-for-cuda).
You will need a compiler that supports **SYCL**. So you just need to install [intel/llvm](https://github.com/intel/llvm).
Furthermore, oneMKL is an interface that calls the backend libraries.

> Without using SYCL ?

You can't build oneMKL without SYCL support. oneMKL uses the C++ language of course, but it also uses an abstraction layer called [SYCL](https://www.khronos.org/sycl/), which is a kind of overlay of C++ if you will.
With the compiler above you will use the [Intel oneAPI Data Parallel C++](https://www.intel.com/content/www/us/en/developer/tools/oneapi/data-parallel-c-plus-plus.html#gs.2s4nxy) (DPC++) APIs of SYCL.
As you can see in the [README.md](https://github.com/oneapi-src/oneMKL/blob/develop/README.md#supported-usage-models), oneMKL provides users with an interface, called oneAPI, that uses DPC++.
So it is not possible to build oneMKL without **SYCL** support.

I hope I have answered all your questions.
Don't hesitate to report any misunderstanding you may have,

**Comment by mmeterel** [comment]
@Sholde Thanks for the explanations. :) As mentioned by @Sholde oneMKL interfaces project is part of oneAPI that is based on DPC++/SYCL. The purpose here is, use oneAPI and run it on every hardware. In this particular case (oneMKL interfaces repo), the purpose is to create an interface layer that can be used to run oneMKL APIs on every hardware. So, you will need a SYCL implementation (such as DPC++, LLVM or hipSYCL) to be able to build oneMKL interfaces and then you can choose the backend depending on the hardware you have. For NVIDIA GPUs, you need either LLVM compiler with CUDA backend. 
Hope this helps answering the question.

**Comment by mmeterel** [comment]
@jiapei100 if the provided answers are sufficient, can we close this issue?

**Comment by jiapei100** [comment]
@mmeterel 

Thank you so much ...


I got a **AMD Ryzen Threadripper 3960X 24-Core Processor** CPU, with **NVidia Geforce 2080 Ti** GPU.
It seems I need to have **hipSYCL**.. Am I right?

**Comment by mmeterel** [comment]
@jiapei100 Looks like you can actually use LLVM compiler with CUDA backend - this will allow you to use cuBLAS/cuSOLVER/cuRAND backends with oneMKL interfaces.

**Comment by jiapei100** [comment]
Thank you  @mmeterel  ...

I still have some conern:

- Is [ISPC](https://github.com/ispc/ispc) specifically for Intel chips and Intel chips **ONLY** ?? What if I have a **AMD** chip?
- If **YES**, is it possible to build [ISPC](https://github.com/ispc/ispc) for **AMD chips** ?

**Comment by mmeterel** [comment]
@jiapei100 I am not familiar with ISPC and do not want to give wrong information. I would suggest posting this question to ISPC repo.

**Comment by mmeterel** [comment]
Closing this issue, since the original question is answered.

**Comment by ValZapod** [comment]
You do understand clang also supports cuda? As good as nvcc. And one can just say that PTX and Streaming assembler, SASS is just SYCL.
