### ISSUE TITLE
Missing oneapi/mkl/stats.hpp header file

### ISSUE THREAD

**Issue by RodneyGuo** [oneapi-src/oneMKL#206]
Dear sirs, after I install the oneapi, I can find the stats.hpp from below folder:
/opt/intel/oneapi/mkl/latest/include/oneapi/mkl/stats.hpp
However, if I compile the oneMKL from the source, I cannot find this header file from the output.
Is this file generated by any other repos?

**Comment by vmalia** [comment]
Hello @RodneyGuo, `oneMKL` is used for 3 different things. I hope this FAQ helps clarify your question. https://github.com/oneapi-src/oneMKL#onemkl

**Comment by RodneyGuo** [comment]
It is quite clear now. Thanks for the reply.
