### ISSUE TITLE
Failed to build oneMKL under Ubuntu 22.04

### ISSUE THREAD

**Issue by jiapei-nexera** [oneapi-src/oneMKL#207]
1. My **ENV**

```console
➜  ~ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04 LTS
Release:	22.04
Codename:	jammy
➜  ~ uname -r
5.15.0-37-generic
➜  ~ gcc --version
gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

➜  ~ clang --version
Ubuntu clang version 14.0.0-1ubuntu1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
➜  ~ 
```

2. CMake **ERROR** messages:

```console
 CMAKE_BUILD_TYPE: Release
 C compiler: icx was not found in PATH, using clang instead
 The CXX compiler identification is unknown
 CMake Error at CMakeLists.txt:135 (project):
   The CMAKE_CXX_COMPILER:

     dpcpp

   is not a full path and was not found in the PATH.

   Tell CMake where to find the compiler by setting either the environment
   variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
   to the compiler, or to the compiler name if it is in the PATH.

 Configuring incomplete, errors occurred!
 See also "....../oneMKL/build/CMakeFiles/CMakeOutput.log".
 See also "....../oneMKL/build/CMakeFiles/CMakeError.log".
```

My question: how to build **oneMKL** successfully from source under Ubuntu 22.04?

**Comment by mmeterel** [comment]
quick question: Did you install Intel oneAPI base tool kit from here?

https://www.intel.com/content/www/us/en/developer/tools/oneapi/dpc-compiler.html#gs.3r7dij

**Comment by jiapei-nexera** [comment]
@mmeterel 
Nope.... I actually built everything from github...
Is there any difference between [oneAPI MKL](https://github.com/oneapi-src/oneMKL) and the [oneAPI at Official website](https://www.intel.com/content/www/us/en/developer/tools/oneapi/dpc-compiler.html#gs.3r7dij) ?


Cheers

**Comment by mmeterel** [comment]
@jiapei-nexera You need DPC++ compiler to be able to build oneMKL interfaces. Where did you get that from?

**Comment by jiapei-nexera** [comment]
@mmeterel 
oh.... Okay.... I didn't realise that is a must... 
So, DPC++ is able to handle both Intel and AMD chips, right???

Now, I'm downloading DPC++ ...

**Comment by mmeterel** [comment]
DPC++ will only work for Intel GPUs.

For AMD, you need hipSYCL. Please see README for more details on which compilers supports which hardware.

**Comment by jiapei-nexera** [comment]
@mmeterel 
Installed... But under `~/intel`. How can I specify my own installation directory ? For instance, `/opt/intel` ?

**Comment by jiapei-nexera** [comment]
@mmeterel 

I still got some **ERROR** message while building **oneMKL**. It looks **oneMKL is looking for MKL** for building??

```console
CMake Error at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
   Could NOT find MKL (missing: mkl_sycl_file)
 Call Stack (most recent call first):
   /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
   cmake/FindMKL.cmake:54 (find_package_handle_standard_args)
   src/blas/backends/mklcpu/CMakeLists.txt:23 (find_package)
```

**Comment by Sholde** [comment]
Hi @jiapei-nexera ,

You can find the `cmake` command to build the oneMKL interface [here](https://github.com/oneapi-src/oneMKL/blob/develop/docs/building_the_project.rst#L280).

Note that you need to `source` in your current terminal the file named `setenv.sh` in your intel root directory (according to your previous comment, this is `~/intel` or `/opt/intel`).
So just run `source /opt/intel/oneapi/setenv.sh`. It will set all the environment variables for you.

I hope this helps,

**Comment by Sholde** [comment]
By the way, by sourcing this script, it will set the MKLROOT environment variable, and you will not need to specify your intel installation directory.

**Comment by mmeterel** [comment]
> @mmeterel
> 
> I still got some **ERROR** message while building **oneMKL**. It looks **oneMKL is looking for MKL** for building??
> 
> ```
> CMake Error at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
>    Could NOT find MKL (missing: mkl_sycl_file)
>  Call Stack (most recent call first):
>    /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
>    cmake/FindMKL.cmake:54 (find_package_handle_standard_args)
>    src/blas/backends/mklcpu/CMakeLists.txt:23 (find_package)
> ```

Here, we are trying to build oneMKL interfaces. And by default, it is using Intel oneMKL backends (mklcpu/mklgpu). (oneMKL interfaces and Intel oneMKL are two different things, please see [FAQ](https://github.com/oneapi-src/oneMKL#faqs)). 
If you don't want to use mklcpu/mklgpu backends, they can be controlled using CMAKE variables as @Sholde pointed out. 
Which backend(s) are you interested?

**Comment by jiapei-nexera** [comment]
@mmeterel 

Got you finally...

So, you are actually saying that: 
**Intel oneAPI->MKL** is the backend, but this **github oneMKL** is **ONLY** the interface of that backend?

Is my understanding correct now????

**Comment by mmeterel** [comment]
@jiapei-nexera That is true. We use name `oneMKL interfaces` for this repo and `Intel oneMKL` to refer the binary product shipped with oneAPI base tool kit. If you can use those names in the future, it would be helpful. :)

**Comment by jiapei-nexera** [comment]
@mmeterel 

Thank you so much...

Now, everything built....
The **ONLY** tough thing is now: **Open3D**.

Are you from the same Intel team???

**Comment by mmeterel** [comment]
@jiapei-nexera Anytime!

Unfortunately I am not familiar with it. Do you mind sharing how you are planning to use oneMKL interfaces?

**Comment by jiapei100** [comment]
@mmeterel 

To tell the truth, I just need to compile `Intel oneMKL` with **OpenCV** and some 3rdparty libraries.
I used to use `liblapack` and `libblas` directly, for **SVD Decomposition**. That reminds of my ancient time... I ALSO used [jama](https://math.nist.gov/javanumerics/jama/) .... Really, long long long long ago...

Anyway, thank you @mmeterel 
You cleared most of my questions....
Thank you ...

Nice dream...

**Comment by mmeterel** [comment]
@jiapei100 you welcome. Please reach out for any future questions.
