### ISSUE TITLE
Where is the Vector Math interface?

### ISSUE THREAD

**Issue by StrongerXi** [oneapi-src/oneMKL#211]
Hi oneMKL team.

I was looking at the Vector Math interface in [developer reference](https://www.intel.com/content/www/us/en/develop/documentation/oneapi-mkl-dpcpp-developer-reference/top/vector-mathematical-functions.html), which says the interfaces are given in 
```
oneapi/mkl/vm.hpp
```

But I can't find it in the repo codebase. Am I missing something?

cc: @jacobkahn

**Comment by mkrainiuk** [comment]
Hi @StrongerXi, the documentation describes [Intel(R) oneAPI Math Kernel Library (oneMKL)](https://software.intel.com/content/www/us/en/develop/tools/oneapi/components/onemkl.html) product. [This opensource project](https://github.com/oneapi-src/oneMKL#oneapi-math-kernel-library-onemkl-interfaces) provides interfaces for multiple third-party libraries, including NVIDIA cuBLAS, Intel oneMKL product, etc.
Vector Math is available as part of[ Intel oneMKL product](https://software.intel.com/content/www/us/en/develop/tools/oneapi/components/onemkl.html) but it's not yet implemented as part of this project.

**Comment by mkrainiuk** [comment]
Oh, could you please check the link? it points to oneDNN documentation for me

**Comment by mkrainiuk** [comment]
I believe this is the right link to oneMKL Interfaces opensource project documentation: https://oneapi-src.github.io/oneMKL/index.html

**Comment by StrongerXi** [comment]
My bad! Link updated.

**Comment by mkrainiuk** [comment]
Thank you!
For this link my first comment is correct, it covers Intel product only. VM is not part of opensource project yet.

**Comment by StrongerXi** [comment]
Makes sense. I think I found the interfaces I need now. Thank you for the clarification!

**Comment by mkrainiuk** [comment]
I will close this question, as it was resolved.
