### ISSUE TITLE
[CUSOLVER] cuSOLVER handler does not support multiple streams

### ISSUE THREAD

**Issue by ericlars** [oneapi-src/oneMKL#216]
# Summary
[Intel llvm](https://github.com/intel/llvm/commit/dd418459868a976cd2eeae367fea6b92795ea611
) introduced multiple CUDA streams per SYCL queue which broke the cuSOLVER scope handler that assumed one stream per device per thread. This broke asynchronous submissions, in the short term synchronous cuSOLVER submissions should be used. See #209 and #215 for further details.

# Version
All versions built with intel llvm after dd418459868a976cd2eeae367fea6b92795ea611.

# Environment
cuSOLVER backend

**Comment by mmeterel** [comment]
@ericlars is this fixed and can be closed?
