### ISSUE TITLE
error while loading shared libraries: libonemkl.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ManjulaChalla** [oneapi-src/oneMKL#221]
Hi,

I executed SYCL application on NVIDIA GPU which is having oneMKL library. I built the open source MKL library for NVIDIA GPU's. The code is generating an output, i didn't get a problem there.

But while profiling the SYCL application using NVIDIA Nsight compute, I have the below error.
 error while loading shared libraries: libonemkl.so.0: cannot open shared object file: No such file or directory
==ERROR== The application returned an error code (127).
==WARNING== No kernels were profiled.

As a workaround, i even tried locate libonemkl.so.0 and copied it to current directory.But still the profiling part didn't work.
I
![Screenshot 2022-08-22 150708](https://user-images.githubusercontent.com/100553269/185890345-f436a260-5407-4ece-ae59-209944fd3af1.jpg)

**Comment by mkrainiuk** [comment]
Hi @ManjulaChalla!
It looks like the profiling tool limitation. As I see on different forums users recommend adding a symbolic link in your project's root directory to the shared libraries that you need or install oneMKL as User Guide recommends to do for GUI libraries in case of such error [here](https://docs.nvidia.com/nsight-systems/UserGuide/index.html#gui-troubleshooting)

**Comment by mmeterel** [comment]
@ManjulaChalla Can this issue/question be closed now? Do you have any other questions?

**Comment by Rbiessy** [comment]
The question was answered and there hasn't been any activity in a long time so closing.
