### ISSUE TITLE
function fft() sometimes fails to calculate result

### ISSUE THREAD

**Issue by StefanPofahl** [oneapi-src/oneMKL#222]
# Summary
Provide a short summary of the issue. Sections below provide guidance on what
factors are considered important to reproduce an issue.
See:
https://github.com/JuliaMath/FFTW.jl/issues/250
and
https://discourse.julialang.org/t/comparison-of-different-fft-implementations/86021/2
At least with 47499754 points the function fft() fails.

# Version
Report oneMKL version and githash.
If it is a regression, report githash for the last known good revision.
I do not know how to figure this out.
FFTW.version() reports: v3.3.4

# Environment
oneMKL works with multiple HW and backend libraries and also depends on the
compiler and build environment. Include
the following information to help reproduce the issue:
* HW you use
* Backend library version
* OS name and version
* Compiler version
* CMake output log

juliaLTS, package FFTW.jl

# Steps to reproduce
Please check that the issue is reproducible with the latest revision on
master. Include all the steps to reproduce the issue.
https://discourse.julialang.org/t/comparison-of-different-fft-implementations/86021/2

# Observed behavior
Document behavior you observe. For performance defects, like performance
regressions or a function being slow, provide a log including output generated
by your application, as well as details on what performance is expected or to
what performance was compared to.
no calculation of spectrum

# Expected behavior
Document behavior you expect.
correct spectrum

**Comment by lhuot** [comment]
Thank you for the bug report! This project doesn't cover oneMKL binary product and the better way to escalate issues is the [oneMKL Forum](https://community.intel.com/t5/Intel-oneAPI-Math-Kernel-Library/bd-p/oneapi-math-kernel-library). You can read more about difference between oneMKL interfaces project and Intel oneMKL release [here](https://github.com/oneapi-src/oneMKL#onemkl). That said, the Intel oneMKL team will take a look at this issue now that you've brought it to our attention. Thanks!

**Comment by StefanPofahl** [comment]
Thanks for your reply, I have opened a question / issue:
https://community.intel.com/t5/Intel-oneAPI-Math-Kernel-Library/function-fft-sometimes-fails-to-calculate-result/m-p/1414125#M33641
