### ISSUE TITLE
cuBLAS backend (and potentially other domains) fails with latest LLVM builds 

### ISSUE THREAD

**Issue by mmeterel** [oneapi-src/oneMKL#223]
# Summary
As first observed in #219 many tests in cuBLAS backend is failing with latest LLVM builds. 

# Version
I have tried LLVM commit: 66361038b63caaae566fc9648f5da50b74222b83 and got the below tests failing (showing only a few of them)

         1 - BLAS/RT/Nrm2TestSuite/Nrm2Tests.RealSinglePrecision/Column_Major_TITAN_RTX (Failed)
          3 - BLAS/RT/Nrm2TestSuite/Nrm2Tests.RealDoublePrecision/Column_Major_TITAN_RTX (Failed)
          7 - BLAS/RT/Nrm2TestSuite/Nrm2Tests.ComplexDoublePrecision/Column_Major_TITAN_RTX (Failed)
         17 - BLAS/RT/IamaxTestSuite/IamaxTests.RealSinglePrecision/Column_Major_TITAN_RTX (Failed)
         19 - BLAS/RT/IamaxTestSuite/IamaxTests.RealDoublePrecision/Column_Major_TITAN_RTX (Failed)
         23 - BLAS/RT/IamaxTestSuite/IamaxTests.ComplexDoublePrecision/Column_Major_TITAN_RTX (Failed)
         27 - BLAS/RT/DotuTestSuite/DotuTests.ComplexDoublePrecision/Column_Major_TITAN_RTX (Failed)
         35 - BLAS/RT/DotcTestSuite/DotcTests.ComplexSinglePrecision/Column_Major_TITAN_RTX (Failed)
         67 - BLAS/RT/AsumTestSuite/AsumTests.ComplexSinglePrecision/Column_Major_TITAN_RTX (Failed)
         81 - BLAS/RT/ScalTestSuite/ScalTests.RealSinglePrecision/Column_Major_TITAN_RTX (Failed)
         85 - BLAS/RT/ScalTestSuite/ScalTests.ComplexSinglePrecision/Column_Major_TITAN_RTX (Failed)
         87 - BLAS/RT/ScalTestSuite/ScalTests.ComplexDoublePrecision/Column_Major_TITAN_RTX (Failed)
        103 - BLAS/RT/RotgTestSuite/RotgTests.RealDoublePrecision/Column_Major_TITAN_RTX (Failed)
        113 - BLAS/RT/RotTestSuite/RotTests.ComplexSinglePrecision/Column_Major_TITAN_RTX (Failed)
        155 - BLAS/RT/CopyUsmTestSuite/CopyUsmTests.RealSinglePrecision/Column_Major_TITAN_RTX (Failed)
        157 - BLAS/RT/CopyUsmTestSuite/CopyUsmTests.RealDoublePrecision/Column_Major_TITAN_RTX (Failed)
        159 - BLAS/RT/CopyUsmTestSuite/CopyUsmTests.ComplexSinglePrecision/Column_Major_TITAN_RTX (Failed)
        161 - BLAS/RT/CopyUsmTestSuite/CopyUsmTests.ComplexDoublePrecision/Column_Major_TITAN_RTX (Failed)
        163 - BLAS/RT/AxpyUsmTestSuite/AxpyUsmTests.RealSinglePrecision/Column_Major_TITAN_RTX (Failed)
        165 - BLAS/RT/AxpyUsmTestSuite/AxpyUsmTests.RealDoublePrecision/Column_Major_TITAN_RTX (Failed)
        167 - BLAS/RT/AxpyUsmTestSuite/AxpyUsmTests.ComplexSinglePrecision/Column_Major_TITAN_RTX (Failed)
        169 - BLAS/RT/AxpyUsmTestSuite/AxpyUsmTests.ComplexDoublePrecision/Column_Major_TITAN_RTX (Failed)
        187 - BLAS/RT/SwapUsmTestSuite/SwapUsmTests.RealSinglePrecision/Column_Major_TITAN_RTX (Failed)
        189 - BLAS/RT/SwapUsmTestSuite/SwapUsmTests.RealDoublePrecision/Column_Major_TITAN_RTX (Failed)
        191 - BLAS/RT/SwapUsmTestSuite/SwapUsmTests.ComplexSinglePrecision/Column_Major_TITAN_RTX (Failed)
        193 - BLAS/RT/SwapUsmTestSuite/SwapUsmTests.ComplexDoublePrecision/Column_Major_TITAN_RTX (Failed)
        197 - BLAS/RT/ScalUsmTestSuite/ScalUsmTests.RealSinglePrecision/Column_Major_TITAN_RTX (Failed)
        199 - BLAS/RT/ScalUsmTestSuite/ScalUsmTests.RealDoublePrecision/Column_Major_TITAN_RTX (Failed)
        201 - BLAS/RT/ScalUsmTestSuite/ScalUsmTests.ComplexSinglePrecision/Column_Major_TITAN_RTX (Failed)
        203 - BLAS/RT/ScalUsmTestSuite/ScalUsmTests.ComplexDoublePrecision/Column_Major_TITAN_RTX (Failed)
        205 - BLAS/RT/ScalUsmTestSuite/ScalUsmTests.ComplexRealSinglePrecision/Column_Major_TITAN_RTX (Failed)
        207 - BLAS/RT/ScalUsmTestSuite/ScalUsmTests.ComplexRealDoublePrecision/Column_Major_TITAN_RTX (Failed)
        213 - BLAS/RT/RotmUsmTestSuite/RotmUsmTests.RealSinglePrecision/Column_Major_TITAN_RTX (Failed)
        215 - BLAS/RT/RotmUsmTestSuite/RotmUsmTests.RealDoublePrecision/Column_Major_TITAN_RTX (Failed)
        225 - BLAS/RT/RotUsmTestSuite/RotUsmTests.RealSinglePrecision/Column_Major_TITAN_RTX (Failed)
        227 - BLAS/RT/RotUsmTestSuite/RotUsmTests.RealDoublePrecision/Column_Major_TITAN_RTX (Failed)
        229 - BLAS/RT/RotUsmTestSuite/RotUsmTests.ComplexSinglePrecision/Column_Major_TITAN_RTX (Failed)
        231 - BLAS/RT/RotUsmTestSuite/RotUsmTests.ComplexDoublePrecision/Column_Major_TITAN_RTX (Failed)
        239 - BLAS/RT/HpmvTestSuite/HpmvTests.ComplexDoublePrecision/Column_Major_TITAN_RTX (Failed)
        245 - BLAS/RT/Her2TestSuite/Her2Tests.ComplexSinglePrecision/Column_Major_TITAN_RTX (Failed)
        251 - BLAS/RT/HemvTestSuite/HemvTests.ComplexDoublePrecision/Column_Major_TITAN_RTX (Failed)
        253 - BLAS/RT/HbmvTestSuite/HbmvTests.ComplexSinglePrecision/Column_Major_TITAN_RTX (Failed)
        257 - BLAS/RT/GeruTestSuite/GeruTests.ComplexSinglePrecision/Column_Major_TITAN_RTX (Failed)
        259 - BLAS/RT/GeruTestSuite/GeruTests.ComplexDoublePrecision/Column_Major_TITAN_RTX (Failed)

I have not tested other domains, but we will likely see similar errors there too. 

# Environment
Test cublas backend on Nvidia GPU using a newer version of LLVM compiler. 

# Observed behavior
Many tests are failing.

# Expected behavior
All tests should pass.

**Comment by yhmtsai** [comment]
I would also like to provide a docker image such that people can reproduce it easily.
The docker image is available in [ginkgohub/oneapi:cuda11.6](https://hub.docker.com/layers/ginkgohub/oneapi/cuda11.6/images/sha256-0bc4c10d79a75b183ac1deafcda753365c6e1a94edc3046a9a0eb8ba2d7b9d94?context=explore)
Use it like using nvidia docker.
I can also get the error on A100 GPU but less error than Titan X.
in `/var/tmp/oneMKL` corresponding build folder
blas: 
```
cmake -DCMAKE_CXX_COMPILER=clang++ -DENABLE_MKLCPU_BACKEND=OFF -DENABLE_MKLGPU_BACKEND=OFF \
 -DENABLE_NETLIB_BACKEND=OFF -DENABLE_CUBLAS_BACKEND=ON -DENABLE_CUSOLVER_BACKEND=OFF \
 -DENABLE_CURAND_BACKEND=OFF -DBUILD_FUNCTIONAL_TESTS=ON \
 -DREF_BLAS_ROOT=/var/tmp/lapack-release/build ..
```
lapack:
```
cmake -DCMAKE_CXX_COMPILER=clang++ -DENABLE_MKLCPU_BACKEND=OFF -DENABLE_MKLGPU_BACKEND=OFF \
 -DENABLE_NETLIB_BACKEND=OFF -DENABLE_CUBLAS_BACKEND=OFF -DENABLE_CUSOLVER_BACKEND=ON \ 
 -DENABLE_CURAND_BACKEND=OFF -DBUILD_FUNCTIONAL_TESTS=ON \
 -DREF_LAPACK_ROOT=/var/tmp/lapack-release/build ..
```
[A100_blas_error.txt](https://github.com/oneapi-src/oneMKL/files/9547460/A100_blas_error.txt)
[A100_lapack_error.txt](https://github.com/oneapi-src/oneMKL/files/9547461/A100_lapack_error.txt)

**Comment by mmeterel** [comment]
Fixed by #228. Closing.

**Comment by mmeterel** [comment]
> I would also like to provide a docker image such that people can reproduce it easily. The docker image is available in [ginkgohub/oneapi:cuda11.6](https://hub.docker.com/layers/ginkgohub/oneapi/cuda11.6/images/sha256-0bc4c10d79a75b183ac1deafcda753365c6e1a94edc3046a9a0eb8ba2d7b9d94?context=explore) Use it like using nvidia docker. I can also get the error on A100 GPU but less error than Titan X. in `/var/tmp/oneMKL` corresponding build folder blas:
> 
> ```
> cmake -DCMAKE_CXX_COMPILER=clang++ -DENABLE_MKLCPU_BACKEND=OFF -DENABLE_MKLGPU_BACKEND=OFF \
>  -DENABLE_NETLIB_BACKEND=OFF -DENABLE_CUBLAS_BACKEND=ON -DENABLE_CUSOLVER_BACKEND=OFF \
>  -DENABLE_CURAND_BACKEND=OFF -DBUILD_FUNCTIONAL_TESTS=ON \
>  -DREF_BLAS_ROOT=/var/tmp/lapack-release/build ..
> ```
> 
> lapack:
> 
> ```
> cmake -DCMAKE_CXX_COMPILER=clang++ -DENABLE_MKLCPU_BACKEND=OFF -DENABLE_MKLGPU_BACKEND=OFF \
>  -DENABLE_NETLIB_BACKEND=OFF -DENABLE_CUBLAS_BACKEND=OFF -DENABLE_CUSOLVER_BACKEND=ON \ 
>  -DENABLE_CURAND_BACKEND=OFF -DBUILD_FUNCTIONAL_TESTS=ON \
>  -DREF_LAPACK_ROOT=/var/tmp/lapack-release/build ..
> ```
> 
> [A100_blas_error.txt](https://github.com/oneapi-src/oneMKL/files/9547460/A100_blas_error.txt) [A100_lapack_error.txt](https://github.com/oneapi-src/oneMKL/files/9547461/A100_lapack_error.txt)

Thanks for the image @yhmtsai This issue should be fixed now. Please let us know if you still see issues.

**Comment by yhmtsai** [comment]
Hi @mmeterel ,
Thanks for pushing these fixes.
It passes all tests on cuBLAS, but there are 16 failures in `*trd*` test in cuSOLVER on TitanX.
```
	177 - LAPACK/RT/Hetrd/HetrdAccuracyUsm.ComplexSinglePrecision/NVIDIA_TITAN_X__Pascal_ (Failed)
	178 - LAPACK/RT/Hetrd/HetrdAccuracyUsm.ComplexDoublePrecision/NVIDIA_TITAN_X__Pascal_ (Failed)
	179 - LAPACK/RT/Hetrd/HetrdAccuracyBuffer.ComplexSinglePrecision/NVIDIA_TITAN_X__Pascal_ (Failed)
	180 - LAPACK/RT/Hetrd/HetrdAccuracyBuffer.ComplexDoublePrecision/NVIDIA_TITAN_X__Pascal_ (Failed)
	323 - LAPACK/RT/Sytrd/SytrdAccuracyUsm.RealSinglePrecision/NVIDIA_TITAN_X__Pascal_ (Failed)
	324 - LAPACK/RT/Sytrd/SytrdAccuracyUsm.RealDoublePrecision/NVIDIA_TITAN_X__Pascal_ (Failed)
	325 - LAPACK/RT/Sytrd/SytrdAccuracyBuffer.RealSinglePrecision/NVIDIA_TITAN_X__Pascal_ (Failed)
	326 - LAPACK/RT/Sytrd/SytrdAccuracyBuffer.RealDoublePrecision/NVIDIA_TITAN_X__Pascal_ (Failed)
	575 - LAPACK/CT/Hetrd/HetrdAccuracyUsm.ComplexSinglePrecision/NVIDIA_TITAN_X__Pascal_ (Failed)
	576 - LAPACK/CT/Hetrd/HetrdAccuracyUsm.ComplexDoublePrecision/NVIDIA_TITAN_X__Pascal_ (Failed)
	577 - LAPACK/CT/Hetrd/HetrdAccuracyBuffer.ComplexSinglePrecision/NVIDIA_TITAN_X__Pascal_ (Failed)
	578 - LAPACK/CT/Hetrd/HetrdAccuracyBuffer.ComplexDoublePrecision/NVIDIA_TITAN_X__Pascal_ (Failed)
	721 - LAPACK/CT/Sytrd/SytrdAccuracyUsm.RealSinglePrecision/NVIDIA_TITAN_X__Pascal_ (Failed)
	722 - LAPACK/CT/Sytrd/SytrdAccuracyUsm.RealDoublePrecision/NVIDIA_TITAN_X__Pascal_ (Failed)
	723 - LAPACK/CT/Sytrd/SytrdAccuracyBuffer.RealSinglePrecision/NVIDIA_TITAN_X__Pascal_ (Failed)
	724 - LAPACK/CT/Sytrd/SytrdAccuracyBuffer.RealDoublePrecision/NVIDIA_TITAN_X__Pascal_ (Failed)
```
detail in [oneMKL_cuSOLVER_TitanX_error.txt](https://github.com/oneapi-src/oneMKL/files/9644827/oneMKL_cuSOLVER_TitanX_error.txt)

oneMKL commit: 9abb8cf1a8b4fa56c1a81db885e6f545d8a9623b
intel clang commit: e1794b668cd2e539672f500fcb0e6bcbc9766077
cuda: 11.6.2

I will update the test results from A100 and the docker image later.

**Comment by mmeterel** [comment]
@yhmtsai Thanks for the new results. These failures are from cuSOLVER backend. Please feel free to open a new issue since this one is closed. 
Tagging @ericlars and @sknepper
