### ISSUE TITLE
A support matrix

### ISSUE THREAD

**Issue by zjin-lcf** [oneapi-src/oneMKL#224]
Can you please create a table to show which CUDA functions are supported and not supported by oneMKL ?

" cublasSgeam can be mapped to omatadd function. However, this function is currently not supported in oneMKL interfaces repo. We plan to add it in Q2. "

**Comment by mmeterel** [comment]
@zjin-lcf IMHO, creating such a table and maintaining it for different domains (BLAS/LAPACK/RNG) and backends (CUDA/ROCM) will create extra and unnecessary overhead for our team. Instead, I would recommend looking at the source code to find out the most accurate and up-to date information. 
For unsupported functions, you can search for such [exceptions](https://github.com/oneapi-src/oneMKL/blob/634d7d25c7bed523d1157cb46177c4d7494862d2/src/blas/backends/cublas/cublas_level3.cpp#L1259):

**Comment by mmeterel** [comment]
@zjin-lcf  
Closing this issue based on the argument made earlier. Please let us know if you have strong objections.
