### ISSUE TITLE
omatadd_batch 

### ISSUE THREAD

**Issue by zjin-lcf** [oneapi-src/oneMKL#225]
# Summary

ldc
Leading dimension of the A matrices. If matrices are stored using column major layout, lda must be at least m. If matrices are stored using row major layout, lda must be at least n. Must be positive.

# URLs
https://www.intel.com/content/www/us/en/develop/documentation/oneapi-mkl-dpcpp-developer-reference/top/blas-routines/blas-like-extensions/omatadd_batch.html

# Additional details
Please clarify the meaning of ldc.

**Comment by andrewtbarker** [comment]
Thank you for reporting this, I will try to get this fixed soon.

**Comment by andrewtbarker** [comment]
The documentation you quote should read:

> ldc
> Leading dimension of the C matrices. If matrices are stored using column major layout, ldc must be at least m. If matrices are stored using row major layout, ldc must be at least n. Must be positive.

Does that help?

**Comment by mmeterel** [comment]
@zjin-lcf Looks like this is not related to oneMKL open source interfaces repo, right? Best way to report issues related to Intel oneMKL product (including documentation) is opening a JIRA (if possible) or reporting on [oneMKL forum](https://community.intel.com/t5/Intel-oneAPI-Math-Kernel-Library/bd-p/oneapi-math-kernel-library)
Thanks for catching this. :)

**Comment by mmeterel** [comment]
Closing since this is related to oneMKL product.

**Comment by zjin-lcf** [comment]
Do you mind forwarding the issue to the oneMKL team ? 
https://www.intel.com/content/www/us/en/develop/documentation/oneapi-mkl-dpcpp-developer-reference/top/blas-routines/blas-like-extensions/omatadd_batch.html

**Comment by zjin-lcf** [comment]
> The documentation you quote should read:
> 
> > ldc
> > Leading dimension of the C matrices. If matrices are stored using column major layout, ldc must be at least m. If matrices are stored using row major layout, ldc must be at least n. Must be positive.
> 
> Does that help?

I didn't receive your emails in my mailbox after your reply. Thanks.

**Comment by mmeterel** [comment]
> Do you mind forwarding the issue to the oneMKL team ? https://www.intel.com/content/www/us/en/develop/documentation/oneapi-mkl-dpcpp-developer-reference/top/blas-routines/blas-like-extensions/omatadd_batch.html

We (@andrewtbarker  and I) are part of oneMKL product team.
