### ISSUE TITLE
[RNG] PRNG function in a kernel

### ISSUE THREAD

**Issue by zjin-lcf** [oneapi-src/oneMKL#239]
Users can call 'curand_init' and 'curand_uniform4' in a CUDA kernel ?  I am not sure if they are supported by oneMKL interface.  Thanks.

**Comment by aelizaro** [comment]
Hi @zjin-lcf, [RNG device APIs ](https://www.intel.com/content/www/us/en/develop/documentation/oneapi-mkl-dpcpp-developer-reference/top/random-number-generators/random-number-generators-device-routines.html)(callable from sycl-kernels) are now available only in Intel oneMKL product, not in oneMKL interfaces yet.

**Comment by mmeterel** [comment]
@zjin-lcf  Can this issue/question be closed?

**Comment by zjin-lcf** [comment]
Will they be supported in oneMKL interfaces ?

**Comment by aelizaro** [comment]
@zjin-lcf, I will convert this question into a feature request, is it ok? If you have any important use cases, please, share your time expectations, so we can prioritize it accordingly.

**Comment by zjin-lcf** [comment]
I don't have a time frame. I am not a scientist; may I assume that it is is a feature for many basic use cases in simulation ?  Thank you.

https://docs.nvidia.com/cuda/curand/device-api-overview.html#device-api-overview
https://docs.nvidia.com/cuda/curand/group__DEVICE.html#group__DEVICE

**Comment by zjin-lcf** [comment]
I try to add some uses case regardless of your priority.

https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/cuda/Distributions.cu

**Comment by zjin-lcf** [comment]
I will close the issue.
