### ISSUE TITLE
[RNG] Question: functions.hpp does not contain all the generate() functions?

### ISSUE THREAD

**Issue by sphblue** [oneapi-src/oneMKL#253]
When you look at this usage model
https://www.intel.com/content/www/us/en/develop/documentation/oneapi-mkl-dpcpp-developer-reference/top/random-number-generators/random-number-generators-device-routines/intel-onemkl-rng-device-usage-model.html

![image](https://user-images.githubusercontent.com/90853374/204595660-b303beb0-9afa-4bb9-a7f6-f90c348204ad.png)

There is a function called generate() with two arguments -> oneapi::mkl:rng::device::generate(distr, engine); 

&nbsp;&nbsp;

**Observations**

1) I can't seem to find this corresponding generate() function in the oneMKL repository. The closest I found is the following, however, this takes in 4 arguments instead of the 2 arguments

![image](https://user-images.githubusercontent.com/90853374/204596306-8973dfd1-3047-463c-af73-2837d4212e63.png)

2) I found the corresponding generate() function in the **other** public oneAPI repo, which is located in /opt/intel/oneapi/mkl/2022.2.0/include/oneapi/mkl/rng/device/functions.hpp . However, this is in a separate package, not part of this oneMKL repo

---

**Question:** 
Is the generate() function with two arguments missing in this oneMKL repo (according to the usage document above) ? If yes, can it be included? 

&nbsp;&nbsp;

**Comment by aelizaro** [comment]
Hi @sphblue, thank you for the question! There are two kinds of APIs supported in oneMKL RNG: device and host. Device APIs which you are looking for is not yet part of oneMKL specification and oneMKL Interfaces project, they are available only in binary Intel oneMKL product as part of [oneAPI toolkits](https://www.intel.com/content/www/us/en/developer/tools/oneapi/base-toolkit.html#gs.jgyaex).

Please, let us know if you want to use device APIs directly from oneMKL Interfaces. I will be also glad to answer any other RNG-related questions.

**Comment by mmeterel** [comment]
@sphblue Looks like the question is answered. Can this issues be closed?
