### ISSUE TITLE
oneMKL CPU backend does not build with LLVM compiler

### ISSUE THREAD

**Issue by andrewtbarker** [oneapi-src/oneMKL#254]
# Summary

The documentation claims the oneMKL CPU backend will work with LLVM compiler, but the build fails because `-lOpenCL` is missing.

# Version

Happens for git hash `f4866ab`.

# Environment

- CPU is Intel Core i9-7920X
- Backend library version is oneMKL 2022.2.
- Ubuntu 18.04.6 LTS
- LLVM (Intel project with LLVM technology) 20220319
- CMake build log attached: [build.txt](https://github.com/oneapi-src/oneMKL/files/10177883/build.txt)

# Steps to reproduce

Follow build instructions, using LLVM as compiler and setting `-DENABLE_MKLCPU_BACKEND=ON`

# Observed behavior

Build fails with the following error:
```
/usr/bin/ld: cannot find -lOpenCL
clang-15: error: linker command failed with exit code 1 (use -v to see invocation)
bin/blas/backends/mklcpu/CMakeFiles/onemkl_blas_mklcpu.dir/build.make:93: recipe for target 'lib/libonemkl_blas_mklcpu.so.0' failed
```
See attached build log for full log.

# Expected behavior

Build succeeds.

**Comment by mkrainiuk** [comment]
`cannot find -lOpenCL` looks like the build system adds libOpenCL.so to the link line as expected, but for some reasons this library cannot be found on the system. Could you please check if OpenCL is present in system paths or LIBRARY_PATH env variable?
If not, you can download OpenCL for CPU driver from LLVM [dependency configuration file](https://github.com/intel/llvm/blob/sycl/buildbot/dependency.conf).
I followed [Install low level runtime](https://github.com/intel/llvm/blob/sycl/sycl/doc/GetStartedGuide.md#use-dpc-toolchain) and I was able to build MKLCPU backend with LLVM successfully

**Comment by andrewtbarker** [comment]
I can get it built now with the correct `LIBRARY_PATH`. We can probably close this issue, but ideally I think we would look for the opencl library in the configure step with cmake rather than having it fail to build.

**Comment by mkrainiuk** [comment]
This is a good idea, I've opened PR for this.
