### ISSUE TITLE
Build error for cuda using cmake

### ISSUE THREAD

**Issue by Rajashekar25** [oneapi-src/oneMKL#266]
Hi, 
I am building oneMKL for cuda with cublas back end. I am using cmake options defined in https://oneapi-src.github.io/oneMKL/building_the_project#building-with-cmake. 
I am giving the options -DREF_BLAS_ROOT=/usr/local/lib and giving additional flags -DCBLAS=ON -DBUILD_SHARED_LIBS=ON. based on another issue I have seen. 
The below Error occurs for me:
CMake error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandaradArgs.cmake:146 (message) :
I am
could not find CBLAS ( missing CBLAS_file)
In /usr/local/lib only libblas.a, liblapack.a are present. 
I have built dpc++ toolchain for Nvidia GPUs. I am compiling with clang++ and dpc++ codes are working fine. 
Can you please help me to resolve the error ?

**Comment by Rajashekar25** [comment]
Hi, I was able to resolve the error by providing the flag -DREF_BLAS_ROOT=/usr/lib/x86_64-lunux-gnu. 
libblas.so file is present in the above directory.

**Comment by mmeterel** [comment]
@Rajashekar25 Glad you were able to resolve the issue. :)

**Comment by Rajashekar25** [comment]
Thanks @mmeterel 👍
