### ISSUE TITLE
Functional_test build errors with cuda backend 

### ISSUE THREAD

**Issue by JinlongLi2001** [oneapi-src/oneMKL#270]
### I'm building oneMKL for cuda backend using these cmake options:
````cmake 
cmake \
-DCMAKE_CXX_COMPILER=clang++ \
-DCMAKE_C_COMPILER=clang \
-DBUILD_SHARED_LIBS=ON \
-DENABLE_CUBLAS_BACKEND=ON \
-DENABLE_CUSOLVER_BACKEND=ON \
-DENABLE_CURAND_BACKEND=ON \
-DENABLE_MKLCPU_BACKEND=OFF \
-DENABLE_MKLGPU_BACKEND=OFF \
-DREF_BLAS_ROOT=/home/ljl/Apps/lapack \
-DREF_LAPACK_ROOT=/home/ljl/Apps/lapack \
-DBUILD_FUNCTIONAL_TESTS=ON \
-DCMAKE_BUILD_TYPE=Debug \
-DBUILD_EXAMPLES=ON \
..
````
### cmake -j failed with these bash output :
````bash
/home/ljl/Downloads/oneMKL/tests/unit_tests/blas/extensions/gemm_bias.cpp:138:48: error: no matching function for call to 'gemm_bias'
                TEST_RUN_CT_SELECT(main_queue, oneapi::mkl::blas::row_major::gemm_bias, transa,
                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
````
- Seems header has not be included correctly
- The same errors founded in(only tested,maybe not all of them) :
````bash
unit_tests/blas/level2/hpmv.cpp
unit_tests/lapack/source/gebrd.cpp
````
- A header included by these sources may be not correct

**Comment by mmeterel** [comment]
@jiuxiaocloud Thanks for reporting the issue. I believe this error is coming because all CUDA backends AND functional tests are enabled. AFAIK, if you want to enable functional testing, we can only enable one backend at a time. 

Do you need to enable all backend and testing at the same time? If not, can you try single backend?

(ENABLE_CUBLAS_BACKEND=ON, -DENABLE_CUSOLVER_BACKEND=ON, -DENABLE_CURAND_BACKEND=ON, -DBUILD_FUNCTIONAL_TESTS=ON)

**Comment by mmeterel** [comment]
@mkrainiuk I have seen this issue a few times before. Can you please verify my comment above and if you agree, can we add a note to README/[Building the project](https://oneapi-src.github.io/oneMKL/building_the_project.html)?

**Comment by JinlongLi2001** [comment]
### Well , test passed with only one cuda backend at a time, please update your documentation correctly

**Comment by mkrainiuk** [comment]
Sure, we will update the documentation, but I think we need to investigate why we have this limitation and how to fix it.

**Comment by mmeterel** [comment]
@jiuxiaocloud  Note added in #279. We will also investigate the root-cause. Do you have any concerns closing the issue?

**Comment by JinlongLi2001** [comment]
all right
