### ISSUE TITLE
is MKL now open?

### ISSUE THREAD

**Issue by cheers00** [oneapi-src/oneMKL#28]
It appears like you have open sourced MKL library for sgemm. Thanks

**Comment by vmalia** [comment]
Hi @cheers00 ,

MKL sgemm implementation is not open sourced. This project provides wrappers that can be used with sgemm implementation of your choice, MKL sgemm or some other, to run on a hardware of your choice, CPU or GPU. Check the README.md for details about supported backends and hardware platforms. You can check the below comment to understand the difference between different oneMKL products: https://github.com/oneapi-src/oneMKL/issues/22#issuecomment-635029135

Hope that helps.
