### ISSUE TITLE
iamax and asum bug related to USM

### ISSUE THREAD

**Issue by FRYoussef** [oneapi-src/oneMKL#280]
# Summary
While working with an NVIDIA GPU, I attempted to use the iamax function, but encountered a segmentation fault that only occurred when using USM (Unified Shared Memory) and obtaining memory through the "malloc_device" function. After investigating possible causes, I found that obtaining memory through the "malloc_shared" function for the "result" variable resolved the issue. Further digging revealed that the variable is reinterpreted from int to int64_t in [this line](https://github.com/oneapi-src/oneMKL/blob/develop/src/blas/backends/cublas/cublas_level1.cpp#L1021) to ensure compatibility between oneMKL and cuBLAS. However, since the operation is performed on the host side, a segmentation fault occurs when memory for that variable is obtained with "malloc_device". It's worth noting that the same issue may be occurring with rocBlas.

On the other side, I have also found a related bug but with asum function. Getting memory for the "result" variable with "malloc_device" ends with a segmentation fault, but everything works well with "malloc_shared". In this case, I could not find any evidence of why it is crashing.

# Version
oneMKL githash: 45c43edcfaea9773a01fcd32b1354984d6780b8e

# Environment
* HW: NVIDIA 1030GT
* OS: Ubuntu 22.04

**Comment by FRYoussef** [comment]
Here is a simple code to test the issue:

```cpp
#include <iostream>
#include <string>
#include <CL/sycl.hpp>
#include "oneapi/mkl.hpp"


int main(int argc, char* argv[]) {
    auto nvidia_gpu_selector = [](const sycl::device &Device) {
        const std::string DriverVersion = Device.get_info<sycl::info::device::driver_version>();
        if (Device.is_gpu() && (DriverVersion.find("CUDA") != std::string::npos))
            return 1;
        return -1;
    };
    cl::sycl::queue q{nvidia_gpu_selector};

    constexpr int N{100};
    double h_sum{-1};
    int64_t h_imax{-1};
    double* vec   = sycl::malloc_device<double>(N, q);
    double* sum   = sycl::malloc_device<double>(1, q); // change -> malloc_shared
    int64_t* imax = sycl::malloc_device<int64_t>(1, q); // change -> malloc_shared
    q.memset(vec, 0, N*sizeof(double)).wait();

    oneapi::mkl::blas::column_major::asum(q, N, vec, 1, sum);
    oneapi::mkl::blas::column_major::iamax(q, N, vec, 1, imax);
    q.wait();

    q.memcpy(&h_sum, sum, sizeof(double)); // must be 0
    q.memcpy(&h_imax, imax, sizeof(int64_t)); // must be 0
    q.wait();

    std::cout << "Sum = " << h_sum << ", Max index = " << h_imax << std::endl;

    sycl::free(vec, q);
    sycl::free(sum, q);
    sycl::free(imax, q);
    return 0;
}
```
Just try changing the malloc_device of the result variables to malloc_shared.

**Comment by andrewtbarker** [comment]
I can reproduce this. It is USM-specific, the buffer APIs seem okay. In addition to `iamax`, `iamin`, and `asum`, it also affects `nrm2` and probably all the level-1 BLAS APIs that return a scalar parameter.

There are two separate issues: setting the correct pointer mode with `cuBlasPointerMode` and the host-side adjustment for 0-based indices in `iamax` and `iamin`. The pointer mode is relatively easy to fix, the other is going to be slightly uglier. I'm working on a fix and tests now.

**Comment by andrewtbarker** [comment]
@FRYoussef Let me know if the changes in PR #304 resolve this for you.

**Comment by FRYoussef** [comment]
As far as I tested it, it worked for me. Well done!!
