### ISSUE TITLE
where is MKLROOT when I use `conda install -c intel mkl mkl-devel mkl-static mkl-include`?

### ISSUE THREAD

**Issue by dongwhfdyer** [oneapi-src/oneMKL#286]
I was trying to install aihwkit which is based on MKL library. It requires me set the ENV variable `MKLROOT`. So I tried different ways to install MKL as illustrated in the following image. They all seem to be smooth in installation. But I don't know where it is installed so I can't set the `MKLROOT`. And how can I know if I install it correctly?
I am very grateful if someone can help!!
![image](https://user-images.githubusercontent.com/59996817/222660606-1c5432c3-4210-404f-a911-6271196eec50.png)

**Comment by mmeterel** [comment]
@dongwhfdyer I have been using Online installer, which have worked for me so far. Do you want to try it?

@vmalia are you familiar with Conda package?

**Comment by dongwhfdyer** [comment]
Yeah i tried. 
These are the commands I use.
```bash
wget https://registrationcenter-download.intel.com/akdlm/irc_nas/19138/l_onemkl_p_2023.0.0.25398.sh

sudo sh ./l_onemkl_p_2023.0.0.25398.sh
```
But I got the following output. 
Life is so hard.

```


Integrity check failed. X
Checksum of file /home/szh2/intel/installercache/downloadcache/intel.oneapi.
lin.condaindex,v=2023.0.0-25326/cupPayload.cup is not correct.
Integrity check failed.
Checksum of file /home/szh2/intel/installercache/downloadcache/intel.oneapi.
lin.tbb.runtime,v=2021.8.0-25334/cupPayload.cup is not correct.
Installation of component has failed.
Component id: intel.oneapi.lin.oneapi-common.vars, name: oneAPI Common, vers
Integrity check failed.

Checksum of file /home/szh2/intel/installercache/downloadcache/intel.oneapi. |
lin.condaindex,v=2023.0.0-25326/cupPayload.cup is not correct. |
Integrity check failed. |
Checksum of file /home/szh2/intel/installercache/downloadcache/intel.oneapi. |
lin.tbb.runtime,v=2021.8.0-25334/cupPayload.cup is not correct. |
Installation of component has failed. Component id: intel.oneapi.lin.oneapi-common.vars, name: oneAPI Common, vers
```

**Comment by mmeterel** [comment]
@vmalia do you have any idea?

**Comment by vmalia** [comment]
@dongwhfdyer seems like the oneAPI installer could not verify the files. Please try to re-download the files and perform a clean installation. On linux, files are usually installed in `/opt/intel/`. If you still see a problem, please post your steps, links, and other details here: https://community.intel.com/t5/Intel-oneAPI-Math-Kernel-Library/bd-p/oneapi-math-kernel-library. This is the dedicated forum for oneMKL backend.

**Comment by hxhc** [comment]
The `MKL_ROOT` is `conda_path/envs/the_env_mkl_installed/library/` or `conda_path/envs/the_env_mkl_installed`
