### ISSUE TITLE
cublas_extensions question

### ISSUE THREAD

**Issue by jinz2014** [oneapi-src/oneMKL#299]
Will you plan to support the functions in src/blas/backends/cublas/cublas_extensions.cpp ?

**Comment by mmeterel** [comment]
@jinz2014  Is there a specific API you are interested?

**Comment by jinz2014** [comment]
It is gemm_bias. 

Other users may be interested in all extensions.

**Comment by mmeterel** [comment]
Are you interested in gemm operation with offsets? I could not locate this functionality in cuBLAS. Can you point it to me if I am missing it?

Or are you interested in gemm with integer precision? 

In the near term, we did not have plans to add new functionality, but that can change if there is good justification. We also encourage community support as described [here](https://github.com/oneapi-src/oneMKL/blob/develop/CONTRIBUTING.md).

**Comment by jinz2014** [comment]
It is gemm with integer precision. I am not sure which MKL gemm functions support low precision (e.g. 8-bit integer).  Thanks.

**Comment by mmeterel** [comment]
@jinz2014 For oneMKL product, please refer to these pages to see the low precision support for `gemm` and `gemm_bias` APIs.
[gemm](https://www.intel.com/content/www/us/en/docs/onemkl/developer-reference-dpcpp/2023-0/gemm.html), [gemm_bias](https://www.intel.com/content/www/us/en/docs/onemkl/developer-reference-dpcpp/2023-0/gemm-bias.html)

**Comment by mmeterel** [comment]
@jinz2014 I hope, your question is answered. Please let me know if you have other questions. If you want to see this functionality added, please open a feature request and provide more information on the importance, timeline, which precisions, etc. You are welcome to contribute as well.
