### ISSUE TITLE
Overriding CMAKE_BUILD_TYPE

### ISSUE THREAD

**Issue by Ruyk** [oneapi-src/oneMKL#3]
The following code:

https://github.com/oneapi-src/oneMKL/blob/7f40c123571995d2e89a910e7844145ec91cd937/CMakeLists.txt#L26-L32

overrides the default `CMAKE_BUILD_TYPE` passed by the command line, and expect users to use `BUILD_DEBUG` flag. Is not really the way CMake users expect to build the programs, some may say is not idiomatic. In practice, it causes some conflicts with Jenkins scripts and user expectations about building the project. 

Is there any particular reason for this? otherwise, `CMAKE_BUILD_TYPE` should be enough to cover for the use case...

**Comment by mkrainiuk** [comment]
Thank you @Ruyk, agree, this is incorrect behavior in oneMKL. I've opened PR #4
