### ISSUE TITLE
oneapi-src/oneMKL and RNG

### ISSUE THREAD

**Issue by vpascuzz** [oneapi-src/oneMKL#30]
[Possibly related to #8.]

I am having some troubling experience with oneAPI and oneMKL. To build my application against oneMKL from oneAPI/beta07 using [intel/llvm (1b762a8)](https://github.com/intel/llvm/commit/1b762a86f156c1e8d00cff76b0b94e7b57094e15), it seems that I need
```
set(LINK_LIBS
  mkl_sycl mkl_intel_ilp64 mkl_tbb_thread
  mkl_core tbb sycl OpenCL pthread m dl)
``` 
[UPDATE]
I can actually build with just:
```
mkl_sycl mkl_intel_ilp64 mkl_tbb_thread mkl_core tbb
```

At first, I thought I found the perfect configuration, but it turns out when running a simple unit test `top` shows ~14GB of virtual memory being used since I'm pulling in all these additional libraries.

I thought I'd build oneMKL from this repo against the oneAPI/beta07 oneMKL -- i.e. setting `MKL_ROOT` to the `oneAPI/<...>/oneMKL` install directory -- to see if that'd help. However, I can't even compile against the built library:
```
$ cmake --build .
[1/12] Linking CXX shared library x86_64-centos7-clang110-opt/lib/libSyclRng.so
FAILED: x86_64-centos7-clang110-opt/lib/libSyclRng.so 
: && /opt/modulefiles/dpcpp/dpcpp_wrapper/clang++ -fPIC -g -O2 -fsycl -std=c++17 -Wno-unknown-cuda-version -O2 -g -DNDEBUG  -Wl,--as-needed -Wl,--no-undefined -Wl,-z,max-page-size=0x1000 -Wl,--hash-style=both -shared -Wl,-soname,libSyclRng.so -o x86_64-centos7-clang110-opt/lib/libSyclRng.so FastCaloSycl/SyclRng/CMakeFiles/SyclRng.dir/src/SimHitRng.cxx.o -L/bld4/atlas/root/v6-14-08_gcc93/lib -Wl,-rpath,/bld4/atlas/root/v6-14-08_gcc93/lib:/home/vrpascuzzi/atlas/dev/build.FastCaloSim-GPU.dpcpp/x86_64-centos7-clang110-opt/lib:  x86_64-centos7-clang110-opt/lib/libSyclCommon.so  -lonemkl  -lonemkl_blas_mklcpu  -lonemkl_blas_mklgpu && :
/tmp/SimHitRng-00fcad.o: In function `SimHitRng::Dealloc()':
/home/vrpascuzzi/atlas/dev/source/FastCaloSim-GPU/FastCaloSimAnalyzer/FastCaloSycl/SyclRng/src/SimHitRng.cxx:105: undefined reference to `mkl::rng::philox4x32x10::~philox4x32x10()'
/tmp/SimHitRng-00fcad.o: In function `SimHitRng::Init(unsigned int, unsigned short, unsigned long, unsigned long long)':
/home/vrpascuzzi/atlas/dev/source/FastCaloSim-GPU/FastCaloSimAnalyzer/FastCaloSycl/SyclRng/src/SimHitRng.cxx:47: undefined reference to `mkl::rng::philox4x32x10::philox4x32x10(cl::sycl::queue&, unsigned long)'
/tmp/SimHitRng-00fcad.o: In function `SimHitRng::Generate(unsigned int)':
/home/vrpascuzzi/atlas/dev/source/FastCaloSim-GPU/FastCaloSimAnalyzer/FastCaloSycl/SyclRng/src/SimHitRng.cxx:58: undefined reference to `cl::sycl::event mkl::rng::generate<mkl::rng::uniform<float, mkl::rng::uniform_method::standard>, mkl::rng::philox4x32x10>(mkl::rng::uniform<float, mkl::rng::uniform_method::standard> const&, mkl::rng::philox4x32x10&, long, mkl::rng::uniform<float, mkl::rng::uniform_method::standard>::result_type*, std::vector<cl::sycl::event, std::allocator<cl::sycl::event> > const&)'
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```
using now:
```
set(LINK_LIBS onemkl onemkl_blas_mklcpu onemkl_blas_mklgpu)
```

Can someone shed some light on this for me? How should I be compiling against oneMKL to get access to the RNGs?

**Comment by vpascuzz** [comment]
RNG aside, this large virtual memory usage comes from instantiating a `cl::sycl::device`, `cl::sycl::queue` or `cl::sycl::context` in code. Not sure if this is expected...

**Comment by mkrainiuk** [comment]
Hi @vpascuzz!

Let me try to define 3 problems that you observed: 
1)  If I understand correctly you built DPC++ compiler from LLVM repo and want to use it with oneMKL from beta07. Since we still in beta stage as far as I know Intel DPC++ compiler from beta07 can be not compatible with DPC++ compiler built from LLVM repo. As the result mkl_sycl library built with DPC++ compiler from beta07 can be not compatible with DPC++ libs from LLVM repo. 
Please try to use both DPC++ compiler and oneMKL from beta07.
First link line definitely should work, second (simplified) link line also most likely will work since DPC++ compiler adds runtime libraries by default.

2)  Unfortunately you can't use opensource oneMKL library for RNG, since it contains only BLAS domain so far. We are working on enabling RNG domain to introduce it in opensource.

3)  I don't think large virtual memory usage is expected behavior. Could you please share small reproducer with source code and how you build it? I tried oneMKL RNG examples with DPC++ compiler from beta07, I see only up to 1GB virtual memory used in top, so probably I missed something or it could be specific to compiler from LLVM repo.

**Comment by jasukhar** [comment]
@vpascuzz do you still need help on this issue? As Maria clarified, this open source project doesn't support RNG. However you can use RNG if you work with Intel oneMKL beta07 directly (without this open source project). If you need further help here with open source BLAS,  please reply to 1 and 2 questions from @mkrainiuk  post. if you have questions about Intel oneMKL beta07 as a binary product, you need to address it to [Intel forum](https://community.intel.com/t5/Intel-oneAPI-Math-Kernel-Library/bd-p/oneapi-math-kernel-library )

**Comment by vpascuzz** [comment]
Thanks for the reply, @mkrainiuk!

> 1. If I understand correctly you built DPC++ compiler from LLVM repo and want to use it with oneMKL from beta07. Since we still in beta stage as far as I know Intel DPC++ compiler from beta07 can be not compatible with DPC++ compiler built from LLVM repo. As the result mkl_sycl library built with DPC++ compiler from beta07 can be not compatible with DPC++ libs from LLVM repo.
>    Please try to use both DPC++ compiler and oneMKL from beta07.
>    First link line definitely should work, second (simplified) link line also most likely will work since DPC++ compiler adds runtime libraries by default.

The beta07 version of MKL links fine with a custom llvm build. And anyway, I can't use the beta07 compiler as it doesn't contain the CUDA plugin interface.

> 2. Unfortunately you can't use opensource oneMKL library for RNG, since it contains only BLAS domain so far. We are working on enabling RNG domain to introduce it in opensource.

Thanks for this. I wasn't sure if this applied only to CUDA or not.

> 3. I don't think large virtual memory usage is expected behavior. Could you please share small reproducer with source code and how you build it? I tried oneMKL RNG examples with DPC++ compiler from beta07, I see only up to 1GB virtual memory used in top, so probably I missed something or it could be specific to compiler from LLVM repo.

It turns out this is not related to the linked libraries; any piece of code that has a `cl::sycl::{queue,device,context}` would do it. E.g.
```
int main(int argc, char** argv) {
  cl::sycl::device dev = cl::sycl::device(cl::sycl::host_selector());
  sleep(10);
  return 0;
}
```

I guess virtual memory is not something we need to worry about anyhow...

**Comment by mkrainiuk** [comment]
Hi @vpascuzz, 

1. Oh, I see, but just to clarify, oneMKL from beta07 also doesn't support CUDA backend. We plan to enable it for RNG as part of opensource oneMKL project only.
3. Well, but it's still a problem.

@bader, do you aware of any large virtual memory usage problems in application with sycl objects in case of using compiler with CUDA backend?

**Comment by vpascuzz** [comment]
Hi, @mkrainiuk.

> large virtual memory usage problems in application with sycl objects in case of using compiler with CUDA backend?

The large virtual memory is also observed without the CUDA backend.

**Comment by vpascuzz** [comment]
As per [intel/llvm#2211](https://github.com/intel/llvm/issues/2211), oneMKL-beta08 appears to be compatible with my build ([1b762a8](https://github.com/intel/llvm/commit/1b762a86f156c1e8d00cff76b0b94e7b57094e15)) and another (built by someone else on 2020-07-23; not sure which commit it's based) of llvm.

I will keep this issue open in case anyone wants to follow up on the observed (seemingly large) virtual memory allocation. It may be more useful to open a separate ticket for this issue on [intel/llvm](https://github.com/intel/llvm), however.

**Comment by jasukhar** [comment]
Hi @vpascuzz ! Virtual memory allocation issue should be submitted against  [intel/llvm](https://github.com/intel/llvm). Do you want to open issue yourself? if not, I can submit it on your behalf. Please let me know how you want to proceed

**Comment by vpascuzz** [comment]
Hi, @jasukhar.

> Virtual memory allocation issue should be submitted against [intel/llvm](https://github.com/intel/llvm).

It looks like it's an isolated issue; I see it on one machine with the llvm built from https://github.com/intel/llvm/commit/1b762a86f156c1e8d00cff76b0b94e7b57094e15 but not on another machine with a more recent revision.

I will open the issue myself if I see the behavior again. For now, I think it's safe to say there's no problem.
