### ISSUE TITLE
CMake MKLConfig.cmake file used by vcpkg has a missing slash in GLOB MKL_DLL_FILE that lets dll finding fail 

### ISSUE THREAD

**Issue by mgexo** [oneapi-src/oneMKL#302]
# Summary
MKLConfig.cmake has an issue here: that lets the globbing for the dlls fail

`
file(GLOB MKL_DLL_FILE "${MKL_ROOT}/bin${MKL_DLL_GLOB}"
        "${MKL_ROOT}/../bin${MKL_DLL_GLOB}"
        "${MKL_ROOT}/../binmkl/${MKL_DLL_GLOB}")
    if(NOT ${lib} STREQUAL ${MKL_IFACE_LIB} AND NOT ${lib} STREQUAL ${MKL_BLAS95} AND NOT ${lib} STREQUAL ${MKL_LAPACK95})  # Windows IFACE libs are static only
      list(LENGTH MKL_DLL_FILE MKL_DLL_FILE_LEN)
`

You can already see that behind /binmkl/ is a slash but the first to lines do NOT have a slash i.e. if the .dlls are in the bin folder they are not found. 

The fix is to add slashes after the bin

`
file(GLOB MKL_DLL_FILE "${MKL_ROOT}/bin/${MKL_DLL_GLOB}"
        "${MKL_ROOT}/../bin/${MKL_DLL_GLOB}"
        "${MKL_ROOT}/../binmkl/${MKL_DLL_GLOB}")
    if(NOT ${lib} STREQUAL ${MKL_IFACE_LIB} AND NOT ${lib} STREQUAL ${MKL_BLAS95} AND NOT ${lib} STREQUAL ${MKL_LAPACK95})  # Windows IFACE libs are static only
      list(LENGTH MKL_DLL_FILE MKL_DLL_FILE_LEN)
`

I suppose that all GLOBs should be checked and fixed like that and then pushe to vcpkg.

**Comment by andrewtbarker** [comment]
Thank you for reporting this. Do you get an error message when using this? Can you share any scripts / command lines you are using and the error messages you are getting?

**Comment by dnhsieh-intel** [comment]
Hi @mgexo, if I understand correctly, the `MKLConfig.cmake` you refer to is from [the oneMKL download binaries](https://www.intel.com/content/www/us/en/developer/tools/oneapi/onemkl.html#gs.ukvd29). Could you let us know what version you are using please? In the latest version, it is:
```
    file(GLOB MKL_DLL_FILE "${MKL_ROOT}/redist/${MKL_ARCH}/${MKL_DLL_GLOB}"
        "${MKL_ROOT}/../redist/${MKL_ARCH}/${MKL_DLL_GLOB}"
        "${MKL_ROOT}/../redist/${MKL_ARCH}/mkl/${MKL_DLL_GLOB}")
```

**Comment by mgexo** [comment]
> Thank you for reporting this. Do you get an error message when using this? Can you share any scripts / command lines you are using and the error messages you are getting?

It was the latest from Microsoft vcpkg in Windows see https://vcpkg.io/en/ .

The errors you get are like those i.e. it does not find the .dll even though they are locally present in the right folder . When I fixes the slashes it works:

CMake Error at C:/vcpkg/installed/x64-windows/share/mkl/MKLConfig.cmake:103 (message):
1> [CMake]   ... .*.dll not found
 
 I was actually not sure where to create the Issue and maybe you are not even aware that someone ported the Intel MKL to the vcpkg manager . The respective file may be here : https://github.com/microsoft/vcpkg/blob/master/ports/intel-mkl/portfile.cmake 

It seems to do some search & replace magic like this which may be wrong:

 vcpkg_replace_string("${CURRENT_PACKAGES_DIR}/share/mkl/MKLConfig.cmake" "bin\${MKL_DLL_GLOB" "bin/\${MKL_DLL_GLOB")
    vcpkg_replace_string("${CURRENT_PACKAGES_DIR}/share/mkl/MKLConfig.cmake" [["../bincompiler" "../compiler/lib"]] [["bin" "../bincompiler" "../compiler/lib"]])
   
I will also report it there https://github.com/microsoft/vcpkg/commit/0526b9cb221ebdc18a8e3de2a25c307a6971bc99

**Comment by Neumann-A** [comment]
Replacement issue in https://github.com/microsoft/vcpkg/blob/4f9d25a7f299db656c376af402637819ee2caba0/ports/intel-mkl/portfile.cmake#L172 missing the extra `/`

**Comment by dnhsieh-intel** [comment]
Thank you @Neumann-A! Closing this issue since it is not part of the oneMKL Interfaces project.

**Comment by mgexo** [comment]
Thanks all!
