### ISSUE TITLE
Improve CMake to make oneMKL easier to use

### ISSUE THREAD

**Issue by Rbiessy** [oneapi-src/oneMKL#306]
# Summary
I have faced issues when trying to use OneMKL as a dependency using CMake. From my testing currently users of oneMKL need to manually set the right includes or libraries to link in CMake to have oneMKL as a dependency. I would like to discuss if we can improve this.

# Version
Latest oneMKL commit, AFAIK this is not a recent issue.

# Environment
I am using the oneAPI 2023.1.0 package and using the [modules files](https://www.intel.com/content/www/us/en/docs/oneapi/programming-guide/2023-1/use-modulefiles-with-linux.html) to load `mkl` and `compiler`.
CMake 3.26.3.

# Steps to reproduce

## First approach
I have tried to use OneMKL in 2 ways. First using `FetchContent` as shown with the following `CMakeLists.txt`:
```
cmake_minimum_required(VERSION 3.13)
project(sample)

include(FetchContent)
set(BUILD_FUNCTIONAL_TESTS OFF)
set(BUILD_EXAMPLES OFF)
FetchContent_Declare(
    open_onemkl
    GIT_REPOSITORY https://github.com/oneapi-src/oneMKL.git
    GIT_TAG dc22279396def65b1af1742a45dda7afcf7c0a22
)
FetchContent_MakeAvailable(open_onemkl)

add_executable(test test.cpp)
target_link_libraries(test PRIVATE onemkl)
```
and the simplest `test.cpp`:
```
int main() { return 0; }
```
The CMake command `cmake -Bbuild .` is failing with:
```
CMake Error at build/_deps/open_onemkl-src/src/blas/CMakeLists.txt:43 (target_link_libraries):
  Target "onemkl_blas" links to:

    ONEMKL::SYCL::SYCL

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.
```
and the same errors for all the other domains and backends. I think `FetchContent` is quite common in modern CMake. I have had more success with `ExternalProject` but this method has limitations and requires the user to manually set the include directory and link to the libraries as far as I know. Do you think it would be valuable to support this? I'm not sure what changes are needed to fix this so help would be appreciated.

## Second approach
Another common approach is to use `find_package(oneMKL)` like so:
```
cmake_minimum_required(VERSION 3.13)
project(sample)

find_package(oneMKL REQUIRED)
add_executable(test gemm_usm.cpp)
target_link_libraries(test PRIVATE MKL::onemkl)
```
Here I am copying some of the existing examples from [`gemm_usm.cpp`](https://github.com/oneapi-src/oneMKL/blob/develop/examples/blas/run_time_dispatching/level3/gemm_usm.cpp) (as well as [`example_helper.hpp`](https://github.com/oneapi-src/oneMKL/blob/develop/examples/include/example_helper.hpp)).
As discussed in https://github.com/oneapi-src/oneMKL/issues/269 there are issues to set up the compiler (see the attached [cmake_install_patch.txt](https://github.com/oneapi-src/oneMKL/files/11295952/cmake_install_patch.txt)).
I am building with:
```
cd /path/to/oneMKL
cmake -Bbuild -GNinja -DENABLE_MKLCPU_THREAD_TBB=OFF -DBUILD_FUNCTIONAL_TESTS=OFF -DBUILD_EXAMPLES=OFF -DCMAKE_INSTALL_PREFIX=/path/to/oneMKL/install .
cd /path/to/sample
cmake -Bbuild -GNinja -DCMAKE_CXX_COMPILER=/opt/intel/oneapi/compiler/latest/linux/bin/icpx -DoneMKL_ROOT=/path/to/oneMKL/install .
ninja -Cbuild
```
The build is failing to link with:
```
/opt/intel/oneapi/compiler/latest/linux/bin/icpx  -fsycl CMakeFiles/test.dir/gemm_usm.cpp.o -o test  -Wl,-rpath,/path/to/oneMKL/install/lib  /path/to/oneMKL/install/lib/libonemkl.so.0  /opt/intel/oneapi/compiler/latest/linux/lib/libsycl.so && :
/usr/bin/ld: /tmp/icpx-c0cdbb/gemm_usm-1d68df.o: in function `run_gemm_example(sycl::_V1::device const&)':
gemm_usm-b1c519.cpp:(.text+0x111c): undefined reference to `oneapi::mkl::blas::column_major::gemm(sycl::_V1::queue&, oneapi::mkl::transpose, oneapi::mkl::transpose, long, long, long, float, float const*, long, float const*, long, float, float*, long, oneapi::mkl::blas::compute_mode, std::vector<sycl::_V1::event, std::allocator<sycl::_V1::event> > const&)'
icpx: error: linker command failed with exit code 1 (use -v to see invocation)
```

I would expect that `target_link_libraries` add all the required dependencies for a minimal example like this to work. I can see the CMake of the example has more logic but I couldn't find a nice solution to fix this. Am I missing something here? It would be nice to be able to use oneMKL with as little code from the user as possible.
That's not the only issue with this approach. For instance if I try to build a [DFT example](https://github.com/oneapi-src/oneMKL/blob/develop/examples/dft/run_time_dispatching/real_fwd_usm.cpp) it fails to use the expected headers:
```
FAILED: CMakeFiles/test.dir/real_fwd_usm.cpp.o 
/opt/intel/oneapi/compiler/latest/linux/bin/icpx  -isystem /path/to/oneMKL/install/include -fsycl -MD -MT CMakeFiles/test.dir/real_fwd_usm.cpp.o -MF CMakeFiles/test.dir/real_fwd_usm.cpp.o.d -o CMakeFiles/test.dir/real_fwd_usm.cpp.o -c /path/to/samples/onemkl_sample2/real_fwd_usm.cpp
/path/to/samples/onemkl_sample2/real_fwd_usm.cpp:65:52: error: no member named 'INPLACE' in 'oneapi::mkl::dft::config_value'
                   oneapi::mkl::dft::config_value::INPLACE);
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
````

CMake includes the installed oneMKL headers as a system include which ends up as a lower priority than the installed MKL headers so `/opt/intel/oneapi/mkl/2023.1.0/include` are used instead. I couldn't find what is causing this behavior in oneMKL CMake but I think the expected behavior is to include `/path/to/oneMKL/install/include` as a user include with `-I` instead of `-isystem`.

Please let me know if you think there is value in fixing these issues. If so I can help for some of them but I don't fully understand what are the changes needed.

**Comment by Rbiessy** [comment]
There has been some CMake improvements but the 2 main issues remain:

- `FetchContent` runs into the same issue with `ONEMKL::SYCL::SYCL target not found`.
- The interface headers conflict with the closed-source MKL headers with `find_package`. I think the interface headers should not be included as system headers.

**Comment by vmalia** [comment]
Thank you @Rbiessy , we will take a look.

**Comment by akabalov** [comment]
Hello @Rbiessy 
I think the first problem with FetchContent goes away if you specify the compiler like: 
`cmake -Bbuild . -DCMAKE_CXX_COMPILER=icpx -DCMAKE_C_COMPILER=icx`

At least in my local runs, if I don't specify compiler, cmake uses /usr/bin/c++ by default and everything starts crashing from the beginning (like from the first steps "unrecognized command line option '-fsycl'". If I set the compiler, everything is fine and I don't have ` ONEMKL::SYCL::SYCL target not found` problem.

**Comment by Rbiessy** [comment]
Hello @akabalov you're right, thanks for that. I'm usually not setting the compiler since oneMKL can detect which one is used automatically. I suppose it makes sense to let the users choose how to handle this.

I can see another issue when trying to build the sample with `FetchContent`, the generated header file `config.hpp` is not found
```
/home/romain/prog/samples/onemkl_sample1/build/_deps/open_onemkl-src/include/oneapi/mkl/detail/backends_table.hpp:32:10: fatal error: 'oneapi/mkl/detail/config.hpp' file not found
   32 | #include "oneapi/mkl/detail/config.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

This file ends up in `build/_deps/open_onemkl-build/bin/oneapi/mkl/detail/config.hpp`. It would be very useful if the user doesn't need to manually add an include path in the CMake. I think it would be possible to add the right include path to the `onemkl` target, what do you think?

**Comment by mschilling0** [comment]
Hi, this issue is not directly related to my issue. However, the title is broad enough where it loosely fits. 

For projects with multiple subprojects with different MKL usages, I found its difficult to use the provided `MKLConfig.cmake` since it doesn't contain all the targets. I understand its parameterized, but I suspect the variables all get cached so trying to specify multiple configurations seems nearly impossible.  Also the target `MKL::mkl_sycl` doesn't seem to link mkl_sycl.so.

Anyways, if its more proper to create a new issue for this. I can do that.

**Comment by akabalov** [comment]
> FetchContent

Yes, I got a fix for this problem. I'll open a PR soon once I complete the validation.

**Comment by akabalov** [comment]
> Hi, this issue is not directly related to my issue. However, the title is broad enough where it loosely fits.
> 
> For projects with multiple subprojects with different MKL usages, I found its difficult to use the provided `MKLConfig.cmake` since it doesn't contain all the targets. I understand its parameterized, but I suspect the variables all get cached so trying to specify multiple configurations seems nearly impossible. Also the target `MKL::mkl_sycl` doesn't seem to link mkl_sycl.so.
> 
> Anyways, if its more proper to create a new issue for this. I can do that.

Hello Matthew!
I would suggest to open a new issue for this problem. Thank you a lot in advance!

**Comment by akabalov** [comment]
> There has been some CMake improvements but the 2 main issues remain:
> 
> * `FetchContent` runs into the same issue with `ONEMKL::SYCL::SYCL target not found`.
> * The interface headers conflict with the closed-source MKL headers with `find_package`. I think the interface headers should not be included as system headers.

As for the second issue, after some investigation, I found this page https://gitlab.kitware.com/cmake/cmake/-/issues/22033
We do use "INTERFACE_INCLUDE_DIRECTORIES" in oneMKL opensource in our oneMKLTargets.cmake (you can find it in your installation folder here lib/cmake/oneMKL/oneMKLTargets.cmake)

`set_target_properties(MKL::onemkl PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"`

To make your example workable, just add after target_link_libraries
`set_target_properties(test PROPERTIES NO_SYSTEM_FROM_IMPORTED true)`

P.S I tried it with cmake 3.25.2 which I had locally and build completed successfully.

**Comment by Rbiessy** [comment]
Thank you, that's interesting. I can get it working as well.

- Is there any plan to document that we need to use `NO_SYSTEM_FROM_IMPORTED` with `find_package` somewhere? I'm not sure where the best place would be, maybe the main README? I am concerned than others may run into this issue.
  - I think it would also be valuable to document that the `CXX` compiler must be set to `icpx` when using `FetchContent`. Possibly also improve the error message if that isn't done.
- From your link I can see that we could also set `EXPORT_NO_SYSTEM` on the providing target rather than the consuming target if the CMake version is 3.25+. Would it be possible to set that if we detect that the CMake version used is recent enough? The whole idea is that it should be as easy to use oneMKL interface as other vendor's libraries so this would be a good step towards this.
- The cmake_install_patch.txt I attached in the description still seems to be needed to be able to use `find_package`.

**Comment by akabalov** [comment]
Hi @Rbiessy 
I think I addressed all questions from this issue. Do you have any objections to close it?

**Comment by Rbiessy** [comment]
Thank you for this @akabalov. I can confirm that my basic examples are working fine now so I am closing it.
