### ISSUE TITLE
[DFT] Building multiple DFT backends at once causes linking conflicts

### ISSUE THREAD

**Issue by FMarno** [oneapi-src/oneMKL#309]
# Summary
When building multiple DFT backends at once, each backend defines a symbol for the many `oneapi::mkl::dft::compute_forward(...)` and `oneapi::mkl::dft::compute_backward(...)` compilation time dispatch overloads, so at linking time either one can be chosen.
To get around this I tried linking just one of the two backends, but then compilation failed because of an undefined reference to `oneapi::mkl::dft::detail::descriptor<...>::commit(oneapi::mkl::backend_selector<other_backend>)`. This is because both `ENABLE_MKLCPU_BACKEND`  and `ENABLE_MKLGPU_BACKEND` are defined in the preprocessor so both commits are defined here - 
https://github.com/oneapi-src/oneMKL/blob/develop/include/oneapi/mkl/dft/detail/descriptor_impl.hpp#L63 .
I tried getting around this by providing a definition of `commit` but made it a weak symbol so it can be overridden when the appropriate backend is linked. This led to problems when running the tests because https://github.com/oneapi-src/oneMKL/blob/develop/tests/unit_tests/main_test.cpp#L113 is still picking up both devices.

I believe other interfaces get around this by having a `backend_selector<backend::BACKEND>` parameter on all the functions, like here https://github.com/oneapi-src/oneMKL/blob/develop/include/oneapi/mkl/blas/detail/blas_ct_backends.hxx. I think the best course of action might be a spec change to include a `backend_selector` on `compute_forward` and `compute_backward`.

# Version
This on develop, I specifically tested githash 005c3c79a44974fc8c3adebfa71d94b0fe005f33

# Steps to reproduce
Build with both ENABLE_MKLCPU_BACKEND and ENABLE_MKLGPU_BACKEND set to 1.

# Observed behavior
When running `test_main_dft_ct` I get this output:
```
finlay@devpc-c310:~/perf/oneMKL/build$ ./bin/test_main_dft_ct 
Run this program with --terse_output to change the way it prints its output.
[==========] Running 488 tests from 3 test suites.
[----------] Global test environment set-up.
[----------] 240 tests from ComputeTestSuite/ComputeTests_in_place
[ RUN      ] ComputeTestSuite/ComputeTests_in_place.COMPLEX_SINGLE_in_place_buffer/sizes_8_batches_1_Intel_R__UHD_Graphics_750__0x4c8a_
Skipping test because: "oneMKL: DFT/compute_forward: function is not implemented Not implemented for MKLCPU"
...
```
# Expected behavior
The MKLGPU `compute_forward` should be called.

**Comment by FMarno** [comment]
One suggestion for implementing the _current_ specification would be to use the descriptor to choose which `compute_forward` to dispatch to i.e.
```cpp
void compute_forward(descriptor d, args...) {
  switch(d.get_backend()) {
#if ENABLE_MKLGPU_BACKEND
    case mklgpu: compute_forward_mklgpu(args...); break;
#endif
#if ENABLE_MKLCPU_BACKEND
    case mklcpu: compute_forward_mklcpu(args...); break;
#endif
  }
}
```
My concern with this is that is missing the intention of the specification author.

**Comment by lhuot** [comment]
> One suggestion for implementing the _current_ specification would be to use the descriptor to choose which `compute_forward` to dispatch to i.e.
> 
> ```c++
> void compute_forward(descriptor d, args...) {
>   switch(d.get_backend()) {
> #if ENABLE_MKLGPU_BACKEND
>     case mklgpu: compute_forward_mklgpu(args...); break;
> #endif
> #if ENABLE_MKLCPU_BACKEND
>     case mklcpu: compute_forward_mklcpu(args...); break;
> #endif
>   }
> }
> ```
> 
> My concern with this is that is missing the intention of the specification author.

This is for the compile time dispatching functionality? Is the "intent" you are referring to here that there should be no runtime dispatch?

**Comment by FMarno** [comment]
@lhuot Yes to both.

**Comment by lhuot** [comment]
I believe RNG would be in the similar situation for their oneapi::mkl::rng::generate API.
Did you check what they are doing?
@aelizaro would you have any insights to share on how RNG handles compile time dispatching for the multiple backends for the generate API?

**Comment by aelizaro** [comment]
@lhuot, @FMarno, if I understand correctly, we don't have such issue in RNG as we take backend_selector parameter for compile-time dispatching only in engine's constructor: https://github.com/oneapi-src/oneMKL/blob/4c7e7eb7227bf131d6326d3dd84f2bfc57ecf3b9/include/oneapi/mkl/rng/engines.hpp#L72 and use pimpl to create an exact implementation we need (e.g. mklcpu::create_philox4x32x10(selector.get_queue(), seed) will return derived class for mklcpu implementation)

also, to avoid having multiple oneapi::mkl::domain::foo() functions they all marked as static inline in oneMKL Interfaces headers: https://github.com/oneapi-src/oneMKL/blob/develop/include/oneapi/mkl/blas/detail/blas_ct_backends.hxx

**Comment by lhuot** [comment]
> @lhuot, @FMarno, if I understand correctly, we don't have such issue in RNG as we take backend_selector parameter for compile-time dispatching only in engine's constructor:
> 
> https://github.com/oneapi-src/oneMKL/blob/4c7e7eb7227bf131d6326d3dd84f2bfc57ecf3b9/include/oneapi/mkl/rng/engines.hpp#L72
> 
> and use pimpl to create an exact implementation we need (e.g. mklcpu::create_philox4x32x10(selector.get_queue(), seed) will return derived class for mklcpu implementation)
> also, to avoid having multiple oneapi::mkl::domain::foo() functions they all marked as static inline in oneMKL Interfaces headers: https://github.com/oneapi-src/oneMKL/blob/develop/include/oneapi/mkl/blas/detail/blas_ct_backends.hxx

This is similar than the DFT descriptor constructor. But then when calling the generate APIs (that have the engine as input and not the backend selector) don't you have different implementation depending on backend for this API or is the implementation the same for any backend?

**Comment by FMarno** [comment]
@aelizaro This is another example of dynamic dispatch since the the v-table of `engine.pimpl` will have to be loaded here https://github.com/oneapi-src/oneMKL/blob/develop/include/oneapi/mkl/rng/functions.hpp#L51. 
It is definitely another solution to implementing the specification, but I again worry that it misses the intent in the same way as my suggestion.

**Comment by FMarno** [comment]
I've just noticed that I can't actually find `backend_selector` in the oneMKL specification. @aelizaro Do you know how it was decided which functions would have a `backend_selector`?

**Comment by aelizaro** [comment]
@FMarno, as I remember, it is not part of oneMKL specification (same as interfaces which take `backend_selector` instead of `sycl::queue`), it is just an extension of oneMKL Interfaces to handle compile-time backend selection case - it has just minimal support for tag-dispatching and accessing the `sycl::queue` itself

**Comment by FMarno** [comment]
> @FMarno, as I remember, it is not part of oneMKL specification (same as interfaces which take `backend_selector` instead of `sycl::queue`), it is just an extension of oneMKL Interfaces to handle compile-time backend selection case - it has just minimal support for tag-dispatching and accessing the `sycl::queue` itself

Thank you for clarifying that. I guess I made an assumption somewhere along the line that the `backend_selector` was part of the specification.

**Comment by FMarno** [comment]
#342 removed the duplicate function signatures, so this should be solved now. I confirmed this by running the tests for MKLCPU and MKLGPU from the same binary!
