### ISSUE TITLE
Syntax error in src/blas/backends/cublas/cublas_level1.cpp

### ISSUE THREAD

**Issue by zhiweij1** [oneapi-src/oneMKL#314]
The code lost `||` at the end of line 770
https://github.com/oneapi-src/oneMKL/blob/815584721775c1eadde457d00bf016b6c03ac9c1/src/blas/backends/cublas/cublas_level1.cpp#L770

**Comment by mmeterel** [comment]
@zhiweij1 Thanks for reporting. We will fix asap.
