### ISSUE TITLE
The certificate is expired: The primary key is not live

### ISSUE THREAD

**Issue by parisa-hr** [oneapi-src/oneMKL#326]
Hi 

My OS is Fedora 38 and I follow the [Document Instructions](https://www.intel.com/content/www/us/en/developer/tools/oneapi/onemkl-download.html?operatingsystem=linux&distributions=dnf)

![image](https://github.com/oneapi-src/oneMKL/assets/44742050/b0826110-4196-48c4-a894-7622b8296d7b)

But I got :
```
error: Certificate 1A8497B11911E097:
  The certificate is expired: The primary key is not live
error: https://yum.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB: key 1 import failed.

```
![image](https://github.com/oneapi-src/oneMKL/assets/44742050/6431b276-87b7-4c76-a4db-e7112558a72e)

I don't know what should I do to fix this.
Thanks

**Comment by vmalia** [comment]
Please try to re-download the files and perform a clean installation. If you still see a problem, please post your steps, links, and other details here: https://community.intel.com/t5/Intel-oneAPI-Math-Kernel-Library/bd-p/oneapi-math-kernel-library. This is the dedicated forum for oneMKL backend.
