### ISSUE TITLE
CMake building error

### ISSUE THREAD

**Issue by Lang0722** [oneapi-src/oneMKL#335]
Following the issues in https://github.com/oneapi-src/oneMKL/issues/334
After the Cmake is done and proceed the next step `make -j`, generate the error message
`
In file included from /home/lang/oneMKL/src/blas/backends/cublas/cublas_level3.cpp:19:
In file included from /home/lang/oneMKL/src/blas/backends/cublas/cublas_helper.hpp:31:
In file included from /usr/include/cublas_v2.h:65:
In file included from /usr/include/cublas_api.h:76:
In file included from /usr/include/cuda_bf16.h:3628:
/usr/include/cuda_bf16.hpp:373:9: error: use of undeclared identifier '__float_as_uint'; did you mean '__imf_float_as_uint'?
    x = __float_as_uint(f);
`

My Cmake command is here:
`
cmake .. -DCMAKE_CXX_COMPILER=/opt/intel/oneapi/compiler/2023.1.0/linux/bin-llvm/clang++ \
         -DCMAKE_C_COMPILER=/opt/intel/oneapi/compiler/2023.1.0/linux/bin-llvm/clang \
         -DENABLE_CUBLAS_BACKEND=True  \
         -DENABLE_CUSOLVER_BACKEND=True \
         -DENABLE_CURAND_BACKEND=FALSE   \
         -DENABLE_MKLCPU_BACKEND=FALSE \
         -DENABLE_MKLGPU_BACKEND=FALSE \
         -DBUILD_FUNCTIONAL_TESTS=FALSE \
         -DCMAKE_BUILD_TYPE=Release \
         -BUILD_DOC=TRUE \
         -DCMAKE_INSTALL_PREFIX=/home_to_onemkl/build/install/ 
`

**Comment by vmalia** [comment]
Hello @Lang0722,
The Intel DPC++/C++ compiler from the oneAPI Toolkits does not support the CUDA backend. Please use the Intel LLVM compiler with CUDA support: https://intel.github.io/llvm-docs/GetStartedGuide.html#build-dpc-toolchain-with-support-for-nvidia-cuda
