### ISSUE TITLE
oneMKL Specification Versioning Strategy wording

### ISSUE THREAD

**Issue by edwards-nag** [oneapi-src/oneMKL#34]
# Summary
The wording for the MINOR count in the oneMKL Specification Versioning Strategy is confusing.

# URLs
https://spec.oneapi.com/versions/latest/oneAPI-spec.pdf section 13.1.5.1

# Additional details
Wording for MINOR count mentions deleting APIs but "without breaking backwards compatibility". Should deleting APIs only occur with an increment in the MAJOR count?

**Comment by spencerpatty** [comment]
Hi Edward,  

What you describe "deleting APIs only occur with an increment in the MAJOR count" is the current intent of this statement.  Any deletion of apis or functionality should happen at MAJOR counts.  That means that when a case for removing an api comes up, we will mark it as deprecated (still a process we are working out for the spec) and then hopefully be able to align the removal with other changes that may occur and group them into a MAJOR uptick.  Does this make sense to you?  Do you have any concerns with this?

Spencer

**Comment by spencerpatty** [comment]
We will update the language in the spec to be inline with this intent.

**Comment by edwards-nag** [comment]
Hi Spencer,

That makes sense, thanks.

Edward

**Comment by vmalia** [comment]
Changes merged. Closing.
