### ISSUE TITLE
cuFFT porting guide

### ISSUE THREAD

**Issue by jinz2014** [oneapi-src/oneMKL#351]
A porting guide from cuFFT to oneMKL FFT will be helpful for users/developers. It may be straightforward to migrate from cuFFT to hipFFT.

For example, 

cufftPlan2d(&plan, N, N, CUFFT_Z2Z)
cufftExecZ2Z(plan, d_inData, d_inData, CUFFT_FORWARD);
 cufftDestroy(plan);

**Comment by Rbiessy** [comment]
While I agree it would be valuable, we have no plans to write a porting guide currently.
The example you are showing should be simple enough to port to oneMKL. You can have a look at the [USM example](https://github.com/oneapi-src/oneMKL/blob/develop/examples/dft/run_time_dispatching/real_fwd_usm.cpp) and set the descriptor to use the `COMPLEX` domain, `DOUBLE` precision and use a `std::vector` for the FFT dimensions.
We can try to help more you if you have a specific issue using oneMKL.

**Comment by jinz2014** [comment]
I am not familiar with FFT, but find that "DFTI_INPLACE" has become an undeclared variable in the oneMKL interface.

**Comment by Rbiessy** [comment]
Yes, `DFTI_INPLACE` is used for the close-source MKL API. You can find the open-source API spec [here](https://spec.oneapi.io/versions/latest/elements/oneMKL/source/domains/dft/dft.html). The example I linked above shows how to set an inplace configuration with `oneapi::mkl::dft::config_value::INPLACE`.
Hope this helps.

**Comment by jinz2014** [comment]
Yes. Thank you for your answers.

**Comment by Rbiessy** [comment]
Great, I'm closing this issue. Feel free to re-open or create more if you have more questions.
