### ISSUE TITLE
no member named 'stats' in namespace 'oneapi::mkl'

### ISSUE THREAD

**Issue by jinz2014** [oneapi-src/oneMKL#352]
# Problem statement
 The issue is no member named 'stats' in namespace 'oneapi::mkl'

# Preferred solution
support of oneapi:mkl::stats with CUDA and ROCm.

oneapi::mkl::stats is a closed source library. Is it helpful to migrate the implementations from DPC++ to CUDA/HIP ?

**Comment by paveldyakov** [comment]
Hi @jinz2014, 

Thank you for your interest to oneMKL Interfaces. 
Yes, oneapi::mkl::stats is currently presented in Intel oneMKL only. 

Could you please tell if you know the respective libraries for statistics routines calculations in Cuda / Rocm? 

Also it would be really great if you can share with us applications / use-cases that can benefit from adding oneapi::mkl::stats functionality to oneMKL Interfaces.

**Comment by jinz2014** [comment]
I will close the issue. Thank you for the questions and comments.
