### ISSUE TITLE
Static library version of libonemkl.so

### ISSUE THREAD

**Issue by edwards-nag** [oneapi-src/oneMKL#36]
Will a static library version of the dispatcher libonemkl.so (with the same PIC versions of the objects as in the shared library) be provided? I'm not sure if linking with a static library make sense for oneMKL, but even if it doesn't, this static library may be useful for making custom oneMKL shared libraries, similar to this for regular Intel MKL.

https://software.intel.com/content/www/us/en/develop/documentation/mkl-linux-developer-guide/top/linking-your-application-with-the-intel-math-kernel-library/building-custom-shared-objects.html

**Comment by mkrainiuk** [comment]
Hello @edwards-nag,
libonemkl.so is more like [MKL single dynamic library](https://software.intel.com/content/www/us/en/develop/documentation/mkl-linux-developer-guide/top/linking-your-application-with-the-intel-math-kernel-library/linking-quick-start/using-the-single-dynamic-library.html) in this case, it contains only runtime dispatcher that loads backend libraries based on the targeted device, all wrappers implementation for third-party libraries are in backend libraries, that have both static and dynamic versions. So I guess we can support this idea with custom shared libraries but for backend libraries as they have all functionality that potentially can be customized.

**Comment by edwards-nag** [comment]
Hi Maria,

OK, thanks for the info.
