### ISSUE TITLE
Is compiler-rt really necessary for oneMKL; could there be an alternative?

### ISSUE THREAD

**Issue by JackAKirk** [oneapi-src/oneMKL#362]
compiler-rt is not built by default using the standard configure.py script from https://github.com/intel/llvm , it takes a long time to build.
However compiler-rt is currently required by at least some oneMKL backends, see https://github.com/oneapi-src/oneMKL/issues/336
I have no idea to what extent compiler-rt is used. If this dependency could be removed easily then it would make the process of building oneMKL from open source much more straightforward.

**Comment by JackAKirk** [comment]
Note it seems it is only required for rocm libs: https://github.com/intel/llvm/issues/10612#issuecomment-1664149574
So I guess the answer is there is no way around it?

**Comment by andrewtbarker** [comment]
@sbalint98 or @TejaX-Alaghari do you have any insights into this question?

**Comment by JackAKirk** [comment]
Sorry, I should close this. compiler-rt is required by rocm (see https://github.com/intel/llvm/issues/10612#issuecomment-1664149574), so this nothing that can be changed by oneMKL.
