### ISSUE TITLE
CBLAS_INCLUDE not specified

### ISSUE THREAD

**Issue by jinz2014** [oneapi-src/oneMKL#367]
cmake reports CBLAS_INCLUDE is not set when building oneMKL with the tests enabled. 

cmake -DCBLAS_INCLUDE=/path/to/cblas/include

**Comment by andrewtbarker** [comment]
Are you following the [cmake build instructions](https://oneapi-src.github.io/oneMKL/building_the_project.html#building-with-cmake)? They do not say anything about setting `CBLAS_INCLUDE` in the cmake configuration step, you specify the location of a reference BLAS with `REF_BLAS_ROOT`.

Can you please provide the complete command line you used and the resulting error message?

**Comment by jinz2014** [comment]
If others encountered the same issue, they may leave a comment.  I will close the issue. Thanks.
