### ISSUE TITLE
Add support for conda in win in case of "Could NOT find MKL (missing: OMP_DLL_DIR)"

### ISSUE THREAD

**Issue by hxhc** [oneapi-src/oneMKL#368]
When using conda to install mkl-devel in windows, it will raise error like "Could NOT find MKL (missing: OMP_DLL_DIR)". This is because the libiomp5md.dll is located in ${MKL_ROOT}/bin. But the corresponding find_path function missed this directory, so please add the support for conda in win.

For example

https://github.com/oneapi-src/oneMKL/blob/c3011d83f2b835c520d69360acae0b80387958f4/cmake/mkl/MKLConfig.cmake#L854C1-L865C71

```cmake
    if(WIN32)
      set(OMP_DLLNAME ${LIB_PREFIX}${MKL_OMP_LIB}.dll)
      find_path(OMP_DLL_DIR ${OMP_DLLNAME}
        HINTS $ENV{LIB} $ENV{LIBRARY_PATH} $ENV{MKLROOT} ${MKL_ROOT} $ENV{CMPLR_ROOT}
        PATH_SUFFIXES "redist/${MKL_ARCH}"
             "redist/${MKL_ARCH}_win" "redist/${MKL_ARCH}_win/compiler"
             "../redist/${MKL_ARCH}/compiler" "../compiler/lib"
             "../../compiler/latest/windows/redist/${MKL_ARCH}_win"
             "../../compiler/latest/windows/redist/${MKL_ARCH}_win/compiler"
             "../../compiler/latest/windows/compiler/redist/${MKL_ARCH}_win"
             "../../compiler/latest/windows/compiler/redist/${MKL_ARCH}_win/compiler")
             
              # simply add this is enough maybe
             "bin"  
      find_package_handle_standard_args(MKL REQUIRED_VARS OMP_DLL_DIR)
```

**Comment by andrewtbarker** [comment]
Thank you for reporting this issue. Since you seem to already have a fix, would you consider making a pull request to fix the issue? Otherwise it may take us some time to get to it.

**Comment by hxhc** [comment]
https://github.com/oneapi-src/oneMKL/pull/380

@andrewtbarker I hope this pr fixes the issue.

**Comment by wjiangsheng** [comment]
I changed the MKLConfig.cmake file to this：
    if(WIN32)
      set(OMP_DLLNAME ${LIB_PREFIX}${MKL_OMP_LIB}.dll)
      find_path(OMP_DLL_DIR ${OMP_DLLNAME}
        HINTS $ENV{LIB} $ENV{LIBRARY_PATH} $ENV{MKLROOT} ${MKL_ROOT} $ENV{CMPLR_ROOT}
        PATH_SUFFIXES "bin"
              # Legacy layout support for oneMKL
              "redist/${MKL_ARCH}"
              "redist/${MKL_ARCH}_win" "redist/${MKL_ARCH}_win/compiler"
              "../redist/${MKL_ARCH}/compiler" "../compiler/lib"
              "../../compiler/latest/windows/redist/${MKL_ARCH}_win"
              "../../compiler/latest/windows/redist/${MKL_ARCH}_win/compiler"
              "../../compiler/latest/windows/compiler/redist/${MKL_ARCH}_win"
              "../../compiler/latest/windows/compiler/redist/${MKL_ARCH}_win/compiler"
        NO_DEFAULT_PATH)
      check_required_vars(OMP_DLL_DIR)
      find_package_handle_standard_args(MKL REQUIRED_VARS OMP_DLL_DIR)
      set(MKL_ENV_PATH "${OMP_DLL_DIR}")
    endif()
and change it to this：
    if(WIN32)
      set(OMP_DLLNAME ${LIB_PREFIX}${MKL_OMP_LIB}.dll)
      find_path(OMP_DLL_DIR ${OMP_DLLNAME}
        HINTS $ENV{LIB} $ENV{LIBRARY_PATH} $ENV{MKLROOT} ${MKL_ROOT} $ENV{CMPLR_ROOT}
        PATH_SUFFIXES "bin"
              # Legacy layout support for oneMKL
              "redist/${MKL_ARCH}"
              "redist/${MKL_ARCH}_win" "redist/${MKL_ARCH}_win/compiler"
              "../redist/${MKL_ARCH}/compiler" "../compiler/lib"
              "../../compiler/latest/windows/redist/${MKL_ARCH}_win"
              "../../compiler/latest/windows/redist/${MKL_ARCH}_win/compiler"
              "../../compiler/latest/windows/compiler/redist/${MKL_ARCH}_win"
              "../../compiler/latest/windows/compiler/redist/${MKL_ARCH}_win/compiler")
      check_required_vars(OMP_DLL_DIR)
      find_package_handle_standard_args(MKL REQUIRED_VARS OMP_DLL_DIR)
      set(MKL_ENV_PATH "${OMP_DLL_DIR}")
    endif()

**I still get an error when I change it to this：**
CMake Error at CMakeLists.txt:18 (find_package):
  Found package configuration file:

    E:/Program Files (x86)/Intel/oneAPI/mkl/2024.0/lib/cmake/mkl/MKLConfig.cmake

  but it set MKL_FOUND to FALSE so package "MKL" is considered to be NOT
  FOUND.  Reason given by package:

  The required variable OMP_DLL_DIR has an invalid value
  "OMP_DLL_DIR-NOTFOUND".

**Comment by hxhc** [comment]
#380 closed

**Comment by jonas-eschmann** [comment]
I get the same error, without using conda (just the oneMKL 2024.0 offline installer and `find_package(MKL REQUIRED)` in cmake:

```
-- MKL_VERSION: 2024.0.0
-- MKL_ROOT: C:/Program Files (x86)/Intel/oneAPI/mkl/2024.0
-- MKL_ARCH: None, set to ` intel64` by default
-- MKL_LINK: None, set to ` dynamic` by default
-- MKL_INTERFACE_FULL: None, set to ` intel_ilp64` by default
-- MKL_THREADING: None, set to ` intel_thread` by default
-- Found C:/Program Files (x86)/Intel/oneAPI/mkl/2024.0/lib/mkl_intel_ilp64_dll.lib
-- Found C:/Program Files (x86)/Intel/oneAPI/mkl/2024.0/lib/mkl_intel_thread_dll.lib
-- Found DLL: C:/Program Files (x86)/Intel/oneAPI/mkl/2024.0/bin/mkl_intel_thread.2.dll
-- Found C:/Program Files (x86)/Intel/oneAPI/mkl/2024.0/lib/mkl_core_dll.lib
-- Found DLL: C:/Program Files (x86)/Intel/oneAPI/mkl/2024.0/bin/mkl_core.2.dll
CMake Error at CMakeLists.txt:27 (find_package):
  Found package configuration file:

    C:/Program Files (x86)/Intel/oneAPI/mkl/2024.0/lib/cmake/mkl/MKLConfig.cmake

  but it set MKL_FOUND to FALSE so package "MKL" is considered to be NOT
  FOUND.  Reason given by package:

  The required variable OMP_DLL_DIR has an invalid value
  "OMP_DLL_DIR-NOTFOUND".
```
