### ISSUE TITLE
INT_TYPES for the set_csr_data() function arguments 

### ISSUE THREAD

**Issue by jinz2014** [oneapi-src/oneMKL#377]
For the oneMKL function 

```
    sycl::event set_csr_data (
        sycl::queue &queue,
        oneapi::mkl::sparse::matrix_handle_t handle,
        const INT_TYPE num_rows,
        const INT_TYPE num_cols,
        oneapi::mkl::index_base index,
        INT_TYPE *rowptr,
        INT_TYPE *colinds,
        DATA_TYPE *values,
        const std::vector<sycl::event> &dependencies = {} );
```

1. The INT_TYPEs for *rowptr and *colinds may be different
2. It seems that "size_t" is not accepted for the two arguments (*rowptr and *colinds).  The error message is "no known conversion from 'size_t *' (aka 'unsigned long *') to 'std::int64_t *' (aka 'long *')"

Thanks

**Comment by Rbiessy** [comment]
Hello @jinz2014, I don't think this is the right place to report this issue, oneMKL interface does not support sparse functions yet.
I think you are trying to use the close-source oneMKL product. You can find that `std::size_t` is not a supported integer type here: https://www.intel.com/content/www/us/en/docs/onemkl/developer-reference-dpcpp/2023-2/sparse-blas-supported-data-and-integer-types.html#SPARSE-BLAS-SUPPORTED-DATA-TYPES

**Comment by jinz2014** [comment]
Can you please recommend a place for reporting issues for sparse functions ?

**Comment by Rbiessy** [comment]
I think this is the place you are looking for, for any issue with the oneapi mkl product: https://community.intel.com/t5/Intel-oneAPI-Math-Kernel-Library/bd-p/oneapi-math-kernel-library
