### ISSUE TITLE
Intel oneAPI mkl library apt distribution gpg key is expired.

### ISSUE THREAD

**Issue by sdake** [oneapi-src/oneMKL#390]
# Summary
The [Intel apt repository pre-installation steps](https://www.intel.com/content/www/us/en/docs/oneapi/installation-guide-linux/2023-2/apt.html#PRE-INSTALLATION-STEPS) which are the latest upstream documentation for MKL install with `apt` uses an expired `.gpg` signature key.

# Version
`2023.3.0` regression in apt repository

# Environment
* HW you use
`NVIDIA CUDA A40`

* Backend library version
* OS name and version
`Debian Bookworm`
* Compiler version
* CMake output log

# Steps to reproduce
Please see the sister issue that has extensive analysis in https://github.com/artificialwisdomai/origin/issues/107#issue-1920663886. This analysis was done as I was attempting to automate our build of `faiss` now that we (had) a functional faiss build.

**Comment by andrewtbarker** [comment]
My understanding is that this has been resolved. @sdake can you confirm?

**Comment by sdake** [comment]
@andrewtbarker confirmed, I will close now. Thank you.

Thank you,
-stever
