### ISSUE TITLE
Layout mismatch

### ISSUE THREAD

**Issue by Rbiessy** [oneapi-src/oneMKL#400]
While working on sparse_blas I ran into an issue with the `layout` enum. In OneMKL interface it is defined [here](https://github.com/oneapi-src/oneMKL/blob/develop/include/oneapi/mkl/types.hpp#L44) as
```
enum class layout : char { column_major = 0, row_major = 1, C = 0, R = 1 };
```
whereas in the close-source headers it is defined as:
```
enum class layout : char {
    row_major = 0,
    col_major = 1,
    R = 0,
    C = 1,
};
```

One difference is the name `column_major` vs `col_major`. The [oneMKL interface documentation](https://oneapi-src.github.io/oneAPI-spec/spec/elements/oneMKL/source/architecture/architecture.html) mentions that it should be `col_major`.

The main issue is that the underlying values are swapped. **Should the interface enum be changed to match the close-source headers or is this intentional?** I think changing this will only affect the blas tests but should not change any of the existing logic.

It is an issue for sparse_blas as this is the only domain where the `layout` is a function parameter AFAIK. There is no good solution to properly convert the open-source layout to the close-source one as they have the same name and namespace. The only way would be to swap the `char` values before calling the backend function.

**Comment by Rbiessy** [comment]
Tagging @gajanan-choudhary who helped me find this issue and @mmeterel as this would affect blas tests.

**Comment by mmeterel** [comment]
@Rbiessy Thanks for reporting this difference. I can't think of any reason why we would want different/swapped ordering for this enum class. It is likely a typo. If you want, go ahead and open a PR with matched ordering and enum names. I can also do it if you prefer that way.

**Comment by Rbiessy** [comment]
Alright, thanks Mesut. I can work on it next Monday.
