### ISSUE TITLE
Error during cmake --build . 

### ISSUE THREAD

**Issue by vidyalathabadde** [oneapi-src/oneMKL#436]
Could someone help me in the successful build of oneMKL for cuda backend with reference blas from Intel oneMKL?

steps followed:
> cmake .. -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DENABLE_CUBLAS_BACKEND=True -DENABLE_MKLCPU_BACKEND=False -DENABLE_MKLGPU_BACKEND=False
> cmake --build .

Initially, I got `Could NOT find CBLAS (missing: CBLAS_file)` error after cmake step, so I changed CBLAS_REQUIRED to BLAS_REQUIRED here **tests/unit_tests/CMakeLists.txt +21**. 
with this change I'm able to complete the cmake step however got stuck at the build step.

Please let me know if the change is incorrect and help me with the proper details so that I can use oneMKL to build my sample on NVIDIA GPU.

error log
```
In file included from /onemkl/oneMKL/tests/unit_tests/blas/extensions/gemm_bias.cpp:37:
In file included from onemkl/oneMKL/tests/unit_tests/blas/extensions/../include/reference_blas_templates.hpp:29:
onemkl/oneMKL/tests/unit_tests/blas/extensions/../include/reference_blas_wrappers.hpp:44:36: error: use of undeclared identifier 'REF_BLAS_LIBNAME'
   44 |         h_libblas = GET_LIB_HANDLE(REF_BLAS_LIBNAME);
      |                                    ^
onemkl/oneMKL/tests/unit_tests/blas/extensions/../include/reference_blas_wrappers.hpp:48:63: error: use of undeclared identifier 'REF_BLAS_LIBNAME'
   48 |                 std::string("failed to load BLAS library ") + REF_BLAS_LIBNAME);
      |                                                               ^
onemkl/oneMKL/tests/unit_tests/blas/extensions/../include/reference_blas_wrappers.hpp:57:37: error: use of undeclared identifier 'REF_CBLAS_LIBNAME'
   57 |         h_libcblas = GET_LIB_HANDLE(REF_CBLAS_LIBNAME);
      |                                     ^
onemkl/oneMKL/tests/unit_tests/blas/extensions/../include/reference_blas_wrappers.hpp:61:64: error: use of undeclared identifier 'REF_CBLAS_LIBNAME'
   61 |                 std::string("failed to load CBLAS library ") + REF_CBLAS_LIBNAME);
      |                                                                ^
4 errors generated.
gmake[2]: *** [tests/unit_tests/blas/extensions/CMakeFiles/blas_extensions_ct.dir/build.make:76: tests/unit_tests/blas/extensions/CMakeFiles/blas_extensions_ct.dir/gemm_bias.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:890: tests/unit_tests/blas/extensions/CMakeFiles/blas_extensions_ct.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
```

**Comment by hjabird** [comment]
Hi vidyalathabadde! Do you want to build the unit tests? If not, set `-DBUILD_FUNCTIONAL_TESTS=OFF`. 

Additionally, I cound that setting `True` and `False` didn't work. Try something similar to the following:
```
cmake ../oneMKL/ -GNinja -DCMAKE_CXX_COMPILER=icpx -DCMAKE_C_COMPILER=icx -DENABLE_CUBLAS_BACKEND=ON -DENABLE_MKLCPU_BACKEND=OFF -DENABLE_MKLGPU_BACKEND=O
FF -DBUILD_FUNCTIONAL_TESTS=OFF
```
(albeit with `clang++` and `clang`, and whatever path you'd prefer.)

**Comment by hjabird** [comment]
Additionally, I cound that setting `True` and `False` didn't work. Try something similar to the following:
```
cmake ../oneMKL/ -GNinja -DCMAKE_CXX_COMPILER=icpx -DCMAKE_C_COMPILER=icx -DENABLE_CUBLAS_BACKEND=ON -DENABLE_MKLCPU_BACKEND=OFF -DENABLE_MKLGPU_BACKEND=O
FF -DBUILD_FUNCTIONAL_TESTS=OFF
```
(albeit with `clang++` and `clang`)

**Comment by vidyalathabadde** [comment]
Hi @hjabird, 

Thank you so much for your reply. Yeah with the above command, I'm able to build the oneMKL for cuda BE. 
But when I'm trying to link it with my code during compilation it gives the undefined references error.
```
/usr/bin/ld: /tmp/simpleCUBLAS_LU-9dfaa3.o: in function `oneapi::mkl::lapack::getrf_batch(sycl::_V1::queue&, long*, long*, double**, long*, long**, long, long*, double*, long, std::vector<sycl::_V1::event, std::allocator<sycl::_V1::event> > const&)':
simpleCUBLAS_LU-f4c50e.cpp:(.text+0x280f): undefined reference to `oneapi::mkl::lapack::detail::getrf_batch(oneapi::mkl::device, sycl::_V1::queue&, long*, long*, double**, long*, long**, long, long*, double*, long, std::vector<sycl::_V1::event, std::allocator<sycl::_V1::event> > const&)'
/usr/bin/ld: /tmp/simpleCUBLAS_LU-9dfaa3.o: in function `_ZN6oneapi3mkl6lapack27getrf_batch_scratchpad_sizeIdTnPNS1_8internal9enable_ifIXsr5is_fpIT_EE5valueEvE4typeELPv0EEElRN4sycl3_V15queueEPlSE_SE_lSE_':
simpleCUBLAS_LU-f4c50e.cpp:(.text._ZN6oneapi3mkl6lapack27getrf_batch_scratchpad_sizeIdTnPNS1_8internal9enable_ifIXsr5is_fpIT_EE5valueEvE4typeELPv0EEElRN4sycl3_V15queueEPlSE_SE_lSE_[_ZN6oneapi3mkl6lapack27getrf_batch_scratchpad_sizeIdTnPNS1_8internal9enable_ifIXsr5is_fpIT_EE5valueEvE4typeELPv0EEElRN4sycl3_V15queueEPlSE_SE_lSE_]+0x4c): undefined reference to `_ZN6oneapi3mkl6lapack6detail27getrf_batch_scratchpad_sizeIdTnPNS1_8internal9enable_ifIXsr5is_fpIT_EE5valueEvE4typeELPv0EEElNS0_6deviceERN4sycl3_V15queueEPlSG_SG_lSG_'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```
command used:
>clang++ -fsycl -fsycl-targets=nvptx64-nvidia-cuda *.cpp -I../../../Common/ -I ../../../include/ -I oneMKL/build/oneMKL_installation/include/ -L oneMKL/build/oneMKL_installation/lib/ -lonemkl_blas_cublas -lonemkl

Could you please help me out with this issue?

Thanks,
Vidya.

**Comment by hjabird** [comment]
Those linker errors suggest you're trying to use the LAPACK interface. However, building with the *cuBLAS* backend doesn't enable this - that is the BLAS interface only.

I think (for I've never used it!) that you need to additionally enable the *cuSOLVER* backend to avoid these linking issues. You can do this by setting `-DENABLE_CUSOLVER_BACKEND=ON`.

**Comment by vidyalathabadde** [comment]
Thanks a lot for your assistance @hjabird. It works. I'm able to compile and run the code successfully now.
