### ISSUE TITLE
create device RNG engine to host.

### ISSUE THREAD

**Issue by tb5874** [oneapi-src/oneMKL#440]
my github sample code is here.
https://github.com/tb5874/practice_oneapi/blob/main/oneapi_test02_user/icx_01_make_library/set_lib_name/set_lib_name.cpp
in there, Line : 2849, sycl_kernel_random_mkl()

i create RNG-engine like below.
```
[ here is sample code 01 : --> ]
q->parallel_for{
  ...
 oneapi::mkl::rng::device::philox4x32x10<> rng_engine(seed, offset);
  ...
}
[ here is sample code 01 : <-- ]
```

but, actually i wanted to create engine to host with pointer and use q->parallel_for().
because i just want only one RNG-engine ( for one seed and offset ).
below is sample code.
```
[ here is sample code 02 : --> ]
int main(void) {
  ..
  void* get_ptr = new oneapi::mkl::rng::device::philox4x32x10<>(seed, offset);
  ..
  q->parallel_for{
    ...
    oneapi::mkl::rng::device::philox4x32x10<>* rng_engine = (oneapi::mkl::rng::device::philox4x32x10<>*)get_ptr 
    oneapi::mkl::rng::device::generate(rng_dist, rng_engine);
    ...
  }
}
[ here is sample code 02 : <-- ]
```

and i tired oneapi::mkl::rng::philox4x32x10 method.
like below.
```
[ here is sample code 03 : --> ]
...
int* sycl_buf = sycl::malloc_device<int>( 100, (*(sycl::queue*)queue_ptr) );
oneapi::mkl::rng::philox4x32x10 engine( (*(sycl::queue*)queue_ptr) , 777 );
oneapi::mkl::rng::uniform<int> distr(0, 10);
oneapi::mkl::rng::generate(distr, engine, 100, sycl_buf);
...
[ here is sample code 03 : <-- ]
```

but i couldn't use this method.
because q created with sycl::device(sycl::gpu_selector_v);
and sycl_buf is device memory.
is there anymethod ?

i really hope to use 'create RNG engine to host with pointer and use q->parallel_for()' style.

**Comment by andreyfe1** [comment]
Hi @tb5874,

It's not clear to me how usage of the single RNG-engine can help here. If it was possible and the pointer to object was copied to each SYCL work-item, there would be data races because all work-items would try to update the state of the same engine. So, it would be great if you could add more details why having a single RNG-engine created on host would benefit.

Generally, in oneMKL we have different approaches to parallelize random number generation:

1. Host API. This is useful if users don't need to care about `parallel_for` submission (code 03 in your example)
2. Having an engine object on every SYCL work-item using the offset correlated to the work-item index (code 01 in your example). However, it may also be flexible if you generate more than one number by each work-item within `parallel_for`, e.g.
```cpp
int portion_size = /*for example*/ 4;
q->parallel_for{ random_numbers / portion_size, 
...
oneapi::mkl::rng::device::philox4x32x10<> rng_engine(seed, idx * portion_size );
for(int i = 0; i < portion_size; ++i){
    buf[idx * portion_size + i] = oneapi::mkl::rng::device::generate(rng_distr, rng_engine);
}
...
}
```
So, engine initialization time can be hide by generating more numbers.
3. Pre-calculate engine states to a separate memory. This is useful if users need to initialize an engine only ones and then use it multiple times in different SYCL kernels afterwards.
Example:
```cpp
int portion_size = /*for example*/ 4;
oneapi::mkl::rng::device::philox4x32x10<>* sycl_buf = sycl::malloc_device( random_numbers / portion_size, q );

auto event = q->parallel_for{random_numbers / portion_size,
...
    sycl_buf[idx] = rng_engine(seed, idx * portion_size );
...
}
...
q->parallel_for{ random_numbers / portion_size, event,
...
for(int i = 0; i < portion_size; ++i){
    buf[idx * portion_size + i] = oneapi::mkl::rng::device::generate(rng_distr, sycl_buf[idx]);
}
...
}
```

**Comment by tb5874** [comment]
Hi @andreyfe1 
Thank you for answer.

sorry for not clear above explain. ( my english skill is very short... jajaja... sorry..! )

for use single RNG-engine purpose is below image.
<img width="605" alt="queue_rng" src="https://github.com/oneapi-src/oneMKL/assets/56007123/f0935c4e-7268-46df-bf8d-aac06d104389">

currently i use below code, and have no problem.
```
q->parallel_for
	sycl::range(sizeof_count),
	[=](auto index) {                                
		std::uint64_t seed = get_seed; ( from outside, fixed. )
		std::uint64_t offset = index;
		oneapi::mkl::rng::device::uniform<int> rng_dist(type_a, type_b);
		oneapi::mkl::rng::device::philox4x32x10<> rng_engine(seed, offset);
		buf[(std::int64_t)index] = oneapi::mkl::rng::device::generate(rng_dist, rng_engine);
	}
```

i just hope create single RNG-engine, below code style.
this is appropriate ?
```
void sycl_mkl_rng(...) {
        ...
        if (get_type == "philox4x32x10") {
            rng_ptr = new oneapi::mkl::rng::device::philox4x32x10((*(sycl::queue*)queue_ptr), get_seed);
        }
        else if (get_type == "mt19937") {
            rng_ptr = new oneapi::mkl::rng::device::mt19937((*(sycl::queue*)queue_ptr), (std::uint32_t)get_seed);
        }
        else {
            ...
        }
        ...
}
```
```
q->parallel_for
	sycl::range(sizeof_count),
	[=](auto index) {                                
		oneapi::mkl::rng::device::uniform<int> rng_dist(type_a, type_b);
		oneapi::mkl::rng::device::philox4x32x10<>* rng_engine = (oneapi::mkl::rng::device::philox4x32x10<>*)rng_ptr
		buf[(std::int64_t)index] = oneapi::mkl::rng::device::generate(rng_dist, rng_engine);
	}
```

**Comment by andreyfe1** [comment]
Seems, host API is the best option for you. You mentioned it in sample code 03 in the initial message:
```cpp
int* sycl_buf = sycl::malloc_device( 100, ((sycl::queue)queue_ptr) );
oneapi::mkl::rng::philox4x32x10 engine( ((sycl::queue)queue_ptr) , 777 );
oneapi::mkl::rng::uniform distr(0, 10);
oneapi::mkl::rng::generate(distr, engine, 100, sycl_buf);
```
You also noticed that sycl_buf can be a problem. Why do yo think so?
If you want to access data on host as well, you can allocate a memory using `sycl::malloc_shared`

**Comment by tb5874** [comment]
Hi again @andreyfe1 

when device is cpu ( Intel(R) Core(TM) i9-10900X CPU @ 3.70GHz   3.70 GHz )
sycl_buf have no problem.
all kinds of work did well.
```
sycl::device d1(sycl::cpu_selector_v);
sycl::queue q1(d1);
int* sycl_buf1 = sycl::malloc_device( 100, q1 );
oneapi::mkl::rng::philox4x32x10 engine( q1 , 777 );
oneapi::mkl::rng::uniform distr(0, 10);
oneapi::mkl::rng::generate(distr, engine, 100, sycl_buf1);
```

but 
when device is gpu ( intel-arcA770 )
i couldn't use below code.
```
sycl::device d2(sycl::gpu_selector_v);
sycl::queue q2(d2);
int* sycl_buf2 = sycl::malloc_device( 100, q2 );
oneapi::mkl::rng::philox4x32x10 engine( q2, 777 );
oneapi::mkl::rng::uniform distr(0, 10);
oneapi::mkl::rng::generate(distr, engine, 100, sycl_buf2);
```
currently i have no more detail about this problem. 
i did not save error message...! sorry.
but certain different is device ( arcA770 vs intel-cpu ).
few days later ( may be weeks? ) i will test. and then send information for you.

and i know sycl::malloc_shared will be help this problem.
but sometimes i just want to use only sycl::malloc_device. ( for avoid double memory allocation, desktop and device )

thank you ! 
your answer was helpful !
have a good one !

**Comment by andreyfe1** [comment]
Thanks for the answer, @tb5874.
I've just made some small changes to make the code compile and run:
```cpp
  sycl::device d2(sycl::gpu_selector_v);
  sycl::queue q2(d2);

  int* sycl_buf2 = sycl::malloc_device<int>( 100, q2 );

  oneapi::mkl::rng::philox4x32x10 engine( q2, 777 );
  oneapi::mkl::rng::uniform<int> distr(0, 10);
  oneapi::mkl::rng::generate(distr, engine, 100, sycl_buf2);
  q2.wait();

  sycl::free(sycl_buf2, q2);
```
Hope it helps.
I see no issues on GPU. Let us know you will see any. Error messages are always welcome!
