### ISSUE TITLE
[CMake] New users can struggle with the CBLAS testing dependency when building oneMKL - what to do?

### ISSUE THREAD

**Issue by hjabird** [oneapi-src/oneMKL#443]
**The problem**

Both in the issues ([here](https://github.com/oneapi-src/oneMKL/issues/436)), and privately, I've supported new users struggling to build the oneMKL library. Their aim was to build and install oneMKL. 

In both cases, the sticking point was the dependency of the BLAS unit tests on CBLAS. This dependency on CBLAS, combined with the fact that the unit tests are build by default, meant that they required support.

**Possible solutions**

1. Only build the oneMKL library by default: building anything else (examples, tests), should be opt-in. This would also reduce build/install times.
2. More helpful error messages for the CBLAS dependency. Error messages should make it clear how to avoid this dependency.

**Comment by hjabird** [comment]
Note another issue caused by this [here](https://github.com/oneapi-src/oneMKL/issues/451).

**Comment by Rbiessy** [comment]
Fixed by https://github.com/oneapi-src/oneMKL/pull/577
