### ISSUE TITLE
Could NOT find CBLAS (missing: CBLAS_file)

### ISSUE THREAD

**Issue by yinshiyou** [oneapi-src/oneMKL#451]
I am Building oneMKL interface project with CMake on linux x64 platform.
Using command: cmake .. -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DMKL_ROOT=/opt/intel/oneapi/mkl/2024.0
Error message as following: 
```
-- Looking for dpc++
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find CBLAS (missing: CBLAS_file)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindCBLAS.cmake:23 (find_package_handle_standard_args)
  tests/unit_tests/CMakeLists.txt:21 (find_package)
```
I have installed intel-oneapi-mkl and intel-oneapi-mkl-devel, didn't Intel(R) oneAPI Math Kernel Library (oneMKL)  support BLAS or  need to add additional options into cmake command.

**Comment by hjabird** [comment]
Hello @yinshiyou.
The issue is that testing is enabled by default, and the tests want a reference CBLAS implementation. Set `-DBUILD_FUNCTIONAL_TESTS=OFF`. See [this very similar issue](https://github.com/oneapi-src/oneMKL/issues/436).

**Comment by yinshiyou** [comment]
> Hello @yinshiyou. The issue is that testing is enabled by default, and the tests want a reference CBLAS implementation. Set `-DBUILD_FUNCTIONAL_TESTS=OFF`. See [this very similar issue](https://github.com/oneapi-src/oneMKL/issues/436).

Thank you very much. It works now :)
