### ISSUE TITLE
-DENABLE_CUFFT_BACKEND missing from documentation

### ISSUE THREAD

**Issue by rafbiels** [oneapi-src/oneMKL#453]
# Summary
The CMake option `-DENABLE_CUFFT_BACKEND` is not documented where the other CUDA backend options are (CUBLAS, CUSOLVER, CURAND).

# URLs
* https://oneapi-src.github.io/oneMKL/building_the_project.html#build-options
* https://github.com/oneapi-src/oneMKL/blob/0927a952dd143ea7cc245ea07dba5d26a120b9d6/docs/building_the_project.rst#build-options

# Additional details
Could the `-DENABLE_CUFFT_BACKEND` please be added in the table summarising build options?

**Comment by Rbiessy** [comment]
Thanks Rafal we will look into this.
