### ISSUE TITLE
Outdated conan installation instructions

### ISSUE THREAD

**Issue by dindon-sournois** [oneapi-src/oneMKL#464]
The [conan installation instructions](https://oneapi-src.github.io/oneMKL/building_the_project.html#building-with-conan) seems outdated. 

 - First this is not `CONAN_USER_HOME` but `CONAN_HOME`
 - `conan config install conan/` doesn't actually works as if $CONAN_HOME/profiles doesn't exists the oneMKL conan profile isn't copied
 - `--profile <profile_name>` doesn't seem to works, had to use `--profile:build=<profile_name>` instead
 - the COMPILER_PREFIX variable in the oneMKL conan profile gets reported as parsing error
 - and so on

I'd say the doc probably needs to be updated for Conan2 or to provide clear conan version requirement.

**Comment by hjabird** [comment]
Unfortunately the decision has been made to stop supporting Conan (see https://github.com/oneapi-src/oneMKL/discussions/267), and its in the process of being removed https://github.com/oneapi-src/oneMKL/pull/460. This is partly due to the trouble of keeping it up to date, as you have identified.

**Comment by Rbiessy** [comment]
We have merged the PR https://github.com/oneapi-src/oneMKL/pull/460 @hjabird mentioned to remove the outdated instructions.
