### ISSUE TITLE
[DFT][Unit Tests] External Unit test set fails if either USM or Buffer memory is not supported

### ISSUE THREAD

**Issue by CETuke** [oneapi-src/oneMKL#522]
# Summary

The current design of the external unit tests runs equivalent USM and Buffer memory testing within the same test. This assumes that both USM and Buffer memory is supported by all DFT backends and these tests will fail (not skip) if only one of those memory access models is supported.
The existing try-catch methods assume the catch is for unsupported DFT size and retries the commit without a further catch so the test will always fail if the actual return was unsupported memory model.

 I can't see anywhere in the specification that indicates both memory models must be supported by a given DFT backend, feel free to close this if that is indeed the case.

# Version
Occurs on develop branch
The tests in question are:
https://github.com/oneapi-src/oneMKL/blob/develop/tests/unit_tests/dft/source/workspace_external_tests.cpp
Sepcifically:
TEST_P(WorkspaceExternalTests, SetWorkspaceOnWorkspaceAutomatic) 

# Expected behavior
I would expect to be able to run the external tests and be able to have half of them pass with the others skipped if only one of the memory models was supported.

**Comment by hjabird** [comment]
Hello @CETuke, 
As far as I know, there are no guarantees about supporting both memory models (although I haven't checked!). However, I believe that the all the current backends support both, and have been verified to pass with both. Is this a case where an existing backend fails unit tests, or something else?
Thanks!

**Comment by CETuke** [comment]
> Hello @CETuke, As far as I know, there are no guarantees about supporting both memory models (although I haven't checked!). However, I believe that the all the current backends support both, and have been verified to pass with both. Is this a case where an existing backend fails unit tests, or something else? Thanks!

I noticed the issue because I'm one of the engineers adding a new DFT backend for Imagination Technologies GPU and our libraries currently don't support USM (although that support is anticipated further down the line). I'm having to disable the external unit tests on my local build as they will always fail for the new backend.
 Apart from the buffers support issue, I also think the failure to add a second catch after the first (and the implicit assumption that the only reason for a failed commit could be memory size) could be a design oversight.

**Comment by hjabird** [comment]
That's exciting!

You're right in that the tests aren't perfect, but they're good enough for the current backends. Trying to anticipate all possible combinations of support would be challenging and would bring unnecessary complexity.

I think the way forward is to update the tests as required as new backends are added. It makes sense for the implementer to do this because they're capable of testing that the modified tests do as required. In your case, this sounds like skipping over the USM functionality in the tests.

**Comment by CETuke** [comment]
> I think the way forward is to update the tests as required as new backends are added. It makes sense for the implementer to do this because they're capable of testing that the modified tests do as required. In your case, this sounds like skipping over the USM functionality in the tests.

Okay, that sounds reasonable. Thanks.
