### ISSUE TITLE
v0.5 release notes

### ISSUE THREAD

**Issue by toxicscum** [oneapi-src/oneMKL#547]

**Comment by sknepper** [comment]
I don't think there are any LAPACK features to include in this list. Thanks!

**Comment by paveldyakov** [comment]
Hi @toxicscum, for RNG we had bug fixes only - no new features

**Comment by andrewtbarker** [comment]
BLAS:
- ~New portBLAS backend support~
- Improved support for ROCm backend

**Comment by andrewtbarker** [comment]
@toxicscum Do you have a date or a commit hash for the previous release so we can check which timeframe/commits might have new features to report?

**Comment by vmalia** [comment]
### Documentation
- Added security.md file which includes guidance on reporting security incidences.
- Updated documentation and README with UXL Foundation details.

**Comment by vmalia** [comment]
> @toxicscum Do you have a date or a commit hash for the previous release so we can check which timeframe/commits might have new features to report?

The v0.4 tag was created on April 12, and uses the latest commit(028d8bac8cbac674877d6302f2d87cfc87d7ac03) from April 10 on develop. I checked all commits from April 12 to August 05. Filtering by authors was useful.

**Comment by hjabird** [comment]
* Documentation
  * Rewrite build documentation https://github.com/oneapi-src/oneMKL/pull/510
* DFT
  * Improve specification for compute function overloads, and implement in oneMKL interfaces. https://github.com/oneapi-src/oneMKL/pull/503
  * Add FWD/BWD STRIDES API: https://github.com/oneapi-src/oneMKL/pull/514

**Comment by Rbiessy** [comment]
> * New portBLAS backend support

@andrewtbarker @toxicscum Support for portBLAS was already mentioned in the [0.3 release notes](https://github.com/oneapi-src/oneMKL/releases/tag/v0.3). I think it can be removed from 0.5.

**Comment by andrewtbarker** [comment]
@Rbiessy you're right, of course, good catch.
