### ISSUE TITLE
Add prefixes to macros in in config.hpp.in

### ISSUE THREAD

**Issue by al42and** [oneapi-src/oneMKL#554]
# Summary

To prevent potential macro naming conflicts between oneMKL and client applications, this RFC proposes adding a unique prefix (such as `ONEMKL_` or `ONEAPI_ONEMKL_`) to all macros defined in oneMKL's public API.

# Problem statement

oneMKL defines a bunch of configuration macros in `config.hpp`, which is transitively included in the `<oneapi/mkl.hpp>` file. 

Those are `ENABLE_<backend>_BACKEND` for each enabled backend, `BUILD_SHARED_LIBS` and `REF_(BLAS|CBLAS)_LIBNAME`.

As a consequence, the client application that tries to use oneMKL will also have them all defined. This could be useful, but, since macros don't obey any scope rules, they can also easily cause confusion if the client application itself uses, e.g., `ENABLE_CUFFT_BACKEND` or `BUILD_SHARED_LIBS`.

[ES.33 in C++ Core Guidelines](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Res-MACROS) recommends adding _supposedly unique prefixes (e.g., your organization’s name)_ to the macro names.

As such, I suggest adding `ONEMKL_` or `ONEAPI_ONEMKL_` prefix to all the macros defined in the public API.

# Details

* Those macros are not part of the specification as far as I can tell, but they can (intentionally or not) affect user applications.

**Comment by Rbiessy** [comment]
Thanks for the RFC, I agree this would be nicer. I would suggest using `ONEAPI_ONEMKL_` for now. Is this blocking you? We may have the bandwidth to work on this but contributions are welcome if anyone needs this soon.

**Comment by al42and** [comment]
> Is this blocking you?

Not blocking, just wanted to raise a concern since it's part of public API (I don't have a link at hand, but it was suggested in one of the examples to check these variables).

> We may have the bandwidth to work on this but contributions are welcome if anyone needs this soon.

Ok! :wink:

**Comment by s-Nick** [comment]
#571 addressed this issue
