### ISSUE TITLE
[ROCFFT] RocFFT fails tests when using ROCm 6.0 or later

### ISSUE THREAD

**Issue by hjabird** [oneapi-src/oneMKL#559]
# Summary

The current tip of oneMKL interfaces fails unit tests when using ROCm 6.0 or later. Using ROCm 5.4.3 does not fail tests.

The failed tests are real-to-complex multi-dimensional tests.

# Version

The issue was introduced with https://github.com/oneapi-src/oneMKL/pull/528 and can be reproduced with oneMKL interfaces developr.

# Environment

* AMD MI210
* Reproduceable RocFFT from ROCm 6.0 or 6.1
* Ubuntu 22.04
* ICPX 2024.2 with Codeplay's plugin for AMD (which supports ROCm 6.0.2 for MI210).

# Steps to reproduce

Build with RocFFT enabled. Test with

```
./bin/test_main_dft_ct --gtest_filter=*REAL_SINGLE_in_place_USM*batches_1*
```
to observe failures. 

# Observed behavior
Tests give wrong results or memory faults.

# Expected behavior
Tests should pass.

**Comment by hjabird** [comment]
* It seems to be the backward DFT that fails. 
* If the tests prior to regression-causing PR are used, the tests still pass. (ie. tests using the INPUT/OUTPUT API with recommit, instead of using FWD/BWD API).
* This problem can also be reproduced on an AMD W6800.

**Comment by hjabird** [comment]
This turned out to be a rocFFT bug. RocFFT issue https://github.com/ROCm/rocFFT/issues/504

**Comment by hjabird** [comment]
There is a work-around for the above at https://github.com/hjabird/oneMKL/tree/hjab/fix_rocfft6_issue

Unfortunately there is still are still failing tests - out-of-place complex 4x4x4_fwd_strides_2_4_1_16_bwd_strides_1_4_16_1_batches_2. These tests pass with ROCm 5.4.3, but fail with ROCm 5.7.1 and later.

**Comment by hjabird** [comment]
This looks like a bug in rocFFT to me. I've described the issue at https://github.com/ROCm/rocFFT/issues/507. I think we oneMKL Interfaces will have to throw unsupported on these tranposing DFTs.

**Comment by Rbiessy** [comment]
The 2 workarounds have been merged and the issues fixed in more recent versions of rocFFT. Closing.
