### ISSUE TITLE
Does device api support exist in this repo?

### ISSUE THREAD

**Issue by JackAKirk** [oneapi-src/oneMKL#573]
I can't see any implementations or tests for https://oneapi-spec.uxlfoundation.org/specifications/oneapi/latest/elements/onemkl/source/domains/rng/device_api/device-routines
A subset was questioned here: https://github.com/oneapi-src/oneMKL/issues/476
and the response was that intels mkl supports device routines. But does the open source oneMKL support them at all for any backends?

Thanks

**Comment by aelizaro** [comment]
Hi @JackAKirk, yes, RNG device APIs are available via oneMKL Interfaces. Here is an implementation: https://github.com/oneapi-src/oneMKL/tree/develop/include/oneapi/mkl/rng/device, it is header-based. To use rng device APIs you need to `#include "oneapi/mkl/rng/device.hpp"` directly.

The tests can be found here: https://github.com/oneapi-src/oneMKL/tree/develop/tests/unit_tests/rng/device

**Comment by JackAKirk** [comment]
> Hi @JackAKirk, yes, RNG device APIs are available via oneMKL Interfaces. Here is an implementation: https://github.com/oneapi-src/oneMKL/tree/develop/include/oneapi/mkl/rng/device, it is header-based. To use rng device APIs you need to `#include "oneapi/mkl/rng/device.hpp"` directly.
> 
> The tests can be found here: https://github.com/oneapi-src/oneMKL/tree/develop/tests/unit_tests/rng/device

Great! thanks very much.

Is there any docs on how to build these tests (in particular I'd like to build them on a cuda backend)?
I had a look but I don't see such docs, and these tests don't build by default unlike the host-api tests.
Thanks

**Comment by JackAKirk** [comment]
> > Hi @JackAKirk, yes, RNG device APIs are available via oneMKL Interfaces. Here is an implementation: https://github.com/oneapi-src/oneMKL/tree/develop/include/oneapi/mkl/rng/device, it is header-based. To use rng device APIs you need to `#include "oneapi/mkl/rng/device.hpp"` directly.
> > The tests can be found here: https://github.com/oneapi-src/oneMKL/tree/develop/tests/unit_tests/rng/device
> 
> Great! thanks very much.
> 
> Is there any docs on how to build these tests (in particular I'd like to build them on a cuda backend)? I had a look but I don't see such docs, and these tests don't build by default unlike the host-api tests. Thanks

Hi @aelizaro 

If you do have instructions on how to build those device tests that would be great. If not no worries, I'll work out the cmake. Thanks

**Comment by JackAKirk** [comment]
Closing as I realized that these tests actually are ran already as part of existing test build.
