### ISSUE TITLE
Unable to use oneMKL DFT with cuFFT backend

### ISSUE THREAD

**Issue by decasdev** [oneapi-src/oneMKL#590]
I'm using Ubuntu 20.04.6 LTS, with oneAPI Base Toolkit 2024.2 installed and I have this very basic code to perform an FFT and I want to target an RTX 3080: 
```c++
#include <iostream>
#include <stdexcept>
#include <complex>
#include <sycl/sycl.hpp>
#include <oneapi/mkl/dfti.hpp>

size_t N = 16;

typedef oneapi::mkl::dft::descriptor<oneapi::mkl::dft::precision::DOUBLE,
                                     oneapi::mkl::dft::domain::COMPLEX>
    complex_fft;

auto exception_handler = [](sycl::exception_list elist) {
    for (auto &e : elist) {
        try {
            std::rethrow_exception(e);
        } catch (sycl::exception &e) {
            std::cerr << "Caught asynchronous SYCL exception: "
                      << e.what() << std::endl;
        } catch (std::exception &e) {
            std::cerr << "Caught standard exception: "
                      << e.what() << std::endl;
        }
    }
    std::terminate();
};

int main(int argc, char const *argv[])
{
    try
    {
        if (argc > 1)
            N = std::stoul(argv[1]);

        sycl::queue q(sycl::default_selector_v, exception_handler);
        std::cout << "Device: " << q.get_device().get_info<sycl::info::device::name>() << std::endl;
        std::cout << std::endl;

        std::complex<double> *host_data = sycl::malloc_host<std::complex<double>>(N, q);
        std::complex<double> *device_data = sycl::malloc_device<std::complex<double>>(N, q);

        q.fill(host_data, std::complex<double>(2.0, 0.0), N).wait_and_throw();

        std::cout << "Host data: ";
        for (size_t i = 0; i < N; i++)
            std::cout << host_data[i] << " ";
        std::cout << std::endl;

        complex_fft fft_descriptor(N);
        fft_descriptor.commit(q);

        q.copy(host_data, device_data, N).wait_and_throw();
        oneapi::mkl::dft::compute_forward(fft_descriptor, device_data).wait_and_throw();
        q.copy(device_data, host_data, N).wait_and_throw();

        std::cout << "Host data: ";
        for (size_t i = 0; i < N; i++)
            std::cout << host_data[i] << " ";
        std::cout << std::endl;
    }
    catch(const std::exception& e)
    {
        std::cerr << e.what() << '\n';
    }
    
    return 0;
}
``` 

I've followed the steps to build the interface:
`~ $ git clone https://github.com/oneapi-src/oneMKL.git`
`~/oneMKL $ mkdir build && cd build`
`~/oneMKL/build $ cmake .. -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DENABLE_CUFFT_BACKEND=True -DTARGET_DOMAINS=dft`
`~/oneMKL/build $ cmake --build .`
`~/oneMKL/build $ cmake --install . --prefix ~/oneMKL`

I'm trying to compile with:
`~$ clang++ -fsycl -fsycl-targets=nvptx64-nvidia-cuda -Xsycl-target-backend=nvptx64-nvidia-cuda --offload-arch=sm_86 test.cpp -o test -L~/oneMKL/lib -lonemkl_dft_cufft`

But I get this error:
/usr/bin/ld: /tmp/clang-4ecf6b728f/test-1efbc3.o: in function `main':
test-94e4a7.cpp:(.text+0x533): undefined reference to `oneapi::mkl::dft::descriptor<(oneapi::mkl::dft::precision)36, (oneapi::mkl::dft::domain)32>::descriptor(long)'
/usr/bin/ld: test-94e4a7.cpp:(.text+0x548): undefined reference to `oneapi::mkl::dft::descriptor<(oneapi::mkl::dft::precision)36, (oneapi::mkl::dft::domain)32>::commit(sycl::_V1::queue&)'
/usr/bin/ld: test-94e4a7.cpp:(.text+0x644): undefined reference to `sycl::_V1::event oneapi::mkl::dft::compute_forward<oneapi::mkl::dft::descriptor<(oneapi::mkl::dft::precision)36, (oneapi::mkl::dft::domain)32>, std::complex<double> >(oneapi::mkl::dft::descriptor<(oneapi::mkl::dft::precision)36, (oneapi::mkl::dft::domain)32>&, std::complex<double>*, std::vector<sycl::_V1::event, std::allocator<sycl::_V1::event> > const&)'
/usr/bin/ld: test-94e4a7.cpp:(.text+0x848): undefined reference to `oneapi::mkl::dft::descriptor<(oneapi::mkl::dft::precision)36, (oneapi::mkl::dft::domain)32>::~descriptor()'
/usr/bin/ld: test-94e4a7.cpp:(.text+0x862): undefined reference to `oneapi::mkl::dft::descriptor<(oneapi::mkl::dft::precision)36, (oneapi::mkl::dft::domain)32>::~descriptor()'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)

I don't know what I'm missing, I've tried everything.

**Comment by s-Nick** [comment]
Hi @decasdev,
thank you for raising this issue, I'll look into it and get back to you as soon as possible.

**Comment by s-Nick** [comment]
I was able to reproduce your error. There are a couple of things to change in your test.

First, the header included `<oneapi/mkl/dfti.hpp>`  is from the Intel(R) oneAPI Math Kernel Library library. If you want to use oneMKL interface library you need to use `oneapi/mkl.hpp`.

Second small change, it seems you are trying to use run-time dispatching and to do it you need to use `-lonemkl` flag. To understand better how to use runtime or compile-time dispatching, I suggest you to read this part of the documentation https://github.com/oneapi-src/oneMKL?tab=readme-ov-file#host-api
Using the following command and changing the header should work.
```bash
clang++ -fsycl -fsycl-targets=nvptx64-nvidia-cuda -Xsycl-target-backend=nvptx64-nvidia-cuda --offload-arch=sm_86 test.cpp -o test -L~/oneMKL/lib -lonemkl_dft_cufft -lonemkl
```

One last thing, for a project or larger tests, we *highly* recommend to use CMake integration to have everything properly configured. You can check how to do it reading the related [documentation](https://github.com/oneapi-src/oneMKL/blob/develop/docs/using_onemkl_with_cmake.rst).

**Comment by decasdev** [comment]
Thank you for your attention.
I'm still running into some problems.

I've changed the header file to `#include <oneapi/mkl.hpp>`.

But now, when compiling with: `~$ clang++ -fsycl -fsycl-targets=nvptx64-nvidia-cuda -Xsycl-target-backend=nvptx64-nvidia-cuda --offload-arch=sm_86 test.cpp -o test -L~/oneMKL/lib -lonemkl -lonemkl_dft_cufft`
I get the following error message:
```
/usr/bin/ld: cannot find -lonemkl
/usr/bin/ld: cannot find -lonemkl_dft_cufft
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
``` 


Even tho with `~$ ls ~/oneMKL/lib` I get:
``` 
cmake                   libonemkl_dft_cufft.so.0  libonemkl_dft_mklcpu.so.0  libonemkl_dft_mklgpu.so.0  libonemkl.so.0
libonemkl_dft_cufft.so  libonemkl_dft_mklcpu.so   libonemkl_dft_mklgpu.so    libonemkl.so
```

**Comment by s-Nick** [comment]
Add a space between `-L` and `~/oneMKL/lib`. I think that `~` is not expanding correctly. It should be `-L ~/oneMKL/lib` or use the full path instead of `~`

**Comment by decasdev** [comment]
With the space it goes back to the original error.

I also tried the CMake approach now:
```cmake
# CMake 3.23.5 is the minimum recommended for IntelLLVM on Linux
cmake_minimum_required(VERSION 3.23.5)

# Set the DPC++ compiler
set(CMAKE_CXX_COMPILER icpx)

# Set the project name
project(test LANGUAGES CXX)

# Find oneAPI
find_package(IntelSYCL REQUIRED)

# Add the executable
add_executable(test test.cpp)
add_sycl_to_target(TARGET test  SOURCES test.cpp)

include(FetchContent)
set(BUILD_FUNCTIONAL_TESTS False)
set(BUILD_EXAMPLES False)
set(ENABLE_CUFFT_BACKEND True)
set(TARGET_DOMAINS "dft")
FetchContent_Declare(
        onemkl_interface_library
        GIT_REPOSITORY https://github.com/oneapi-src/oneMKL.git
        GIT_TAG develop
)
FetchContent_MakeAvailable(onemkl_interface_library)

# Link the oneMKL library
target_link_libraries(test PRIVATE onemkl)

# Add compiler flags
target_compile_options(test PRIVATE
    -fsycl-targets=nvptx64-nvidia-cuda -Xsycl-target-backend --cuda-gpu-arch=sm_86
)
``` 
After building and compiling with make, I get this error in execution:
```
Device: NVIDIA GeForce RTX 3080

No kernel named _ZTSZN4sycl3_V17handler4fillISt7complexIdEEEvPvRKT_mEUlNS0_2idILi1EEEE_ was found -46 (PI_ERROR_INVALID_KERNEL_NAME)
```

**Comment by s-Nick** [comment]
It should work by splitting `~` from the rest.
Anyhow, I think in your CMakeLists you are missing to link to the specific target.
Can you try adding `target_link_options(test PRIVATE -fsycl-targets=nvidia_gpu_sm_86 )` ?

**Comment by decasdev** [comment]
With the addition of `target_link_options(test PRIVATE -fsycl-targets=nvidia_gpu_sm_86 )` it worked.
Still couldn't make it work via CLI tho.

Thank you so much for your attention.
