### ISSUE TITLE
How to use fgrmes to solve linear system with sparse matrix?

### ISSUE THREAD

**Issue by sjlovemzd** [oneapi-src/oneMKL#613]
Hello,
I want to solve a linear system Ax=b using gmres method, A is a sparse matrix. [https://www.intel.com/content/www/us/en/docs/onemkl/developer-reference-c/2025-0/fgmres-interface-description.html#RCI_ID_USERDATAARRAYS](url) tell me MKL has fgmres to solve linear system in an iterative way. I want to find the example code.  Document(https://www.intel.com/content/www/us/en/docs/onemkl/developer-reference-c/2025-0/iterative-sp-solvers-reverse-comm-iface-rci-iss.html) tell me that in the Intel® oneAPI Math Kernel Library (oneMKL) installation directory with the path examples/solverc/source, there is example code. But I can not find it. So where is the example code?

**Comment by Rbiessy** [comment]
Hello @sjlovemzd, I should clarify first that there is some confusion between the different oneMKL projects, see the FAQ: https://github.com/oneapi-src/oneMKL?tab=readme-ov-file#onemkl

Your question is about the Intel oneMKL product for which you can get help on this forum: https://community.intel.com/t5/Intel-oneAPI-Math-Kernel-Library/bd-p/oneapi-math-kernel-library

`gmres` is not supported in oneMKL Interface. As to your question of where you can find the Intel oneMKL product examples, I would suggest to install the oneAPI base toolkit from https://www.intel.com/content/www/us/en/developer/tools/oneapi/base-toolkit-download.html and extract the tarballs in `/opt/intel/oneapi/mkl/2025.0/share/doc/mkl/examples/` (using the default installation path on linux).

Hope this helps!
