### ISSUE TITLE
PyPI package mkl==2021.1.1 takes up too much space

### ISSUE THREAD

**Issue by storypku** [oneapi-src/oneMKL#64]
# Summary

MKL library installed via `pip3 install mkl==2021.1.1` has duplicate shared library (so) entries and  takes up too much space on disk, which, when built into Docker images, will increase significantly the final image size.

# Version
mkl == 2021.1.1 release

# Environment
Ubuntu Linux 18.04/20.04
Python3.6/Python3.8
pip3 20.3.1

# Steps to reproduce

```
pip3 install mkl==2021.1.1
pip3 show -f mkl 
ll /usr/local/lib/libmkl_*  -lh
```

# Observed and Expected behavior

`ls -lh` shows the following files

```
-rwxr-xr-x 1 root root  47M Dec 10 20:19 /usr/local/lib/libmkl_avx2.so.1*
-rwxr-xr-x 1 root root  64M Dec 10 20:19 /usr/local/lib/libmkl_avx512_mic.so.1*
-rwxr-xr-x 1 root root  61M Dec 10 20:19 /usr/local/lib/libmkl_avx512.so.1*
-rwxr-xr-x 1 root root  50M Dec 10 20:19 /usr/local/lib/libmkl_avx.so.1*
-rwxr-xr-x 1 root root 513K Dec 10 20:19 /usr/local/lib/libmkl_blacs_intelmpi_ilp64.so*
-rwxr-xr-x 1 root root 513K Dec 10 20:19 /usr/local/lib/libmkl_blacs_intelmpi_ilp64.so.1*
-rwxr-xr-x 1 root root 310K Dec 10 20:19 /usr/local/lib/libmkl_blacs_intelmpi_lp64.so*
-rwxr-xr-x 1 root root 310K Dec 10 20:19 /usr/local/lib/libmkl_blacs_intelmpi_lp64.so.1*
-rwxr-xr-x 1 root root 514K Dec 10 20:19 /usr/local/lib/libmkl_blacs_openmpi_ilp64.so*
-rwxr-xr-x 1 root root 514K Dec 10 20:19 /usr/local/lib/libmkl_blacs_openmpi_ilp64.so.1*
-rwxr-xr-x 1 root root 315K Dec 10 20:19 /usr/local/lib/libmkl_blacs_openmpi_lp64.so*
-rwxr-xr-x 1 root root 315K Dec 10 20:19 /usr/local/lib/libmkl_blacs_openmpi_lp64.so.1*
-rwxr-xr-x 1 root root 513K Dec 10 20:19 /usr/local/lib/libmkl_blacs_sgimpt_ilp64.so*
-rwxr-xr-x 1 root root 513K Dec 10 20:19 /usr/local/lib/libmkl_blacs_sgimpt_ilp64.so.1*
-rwxr-xr-x 1 root root 310K Dec 10 20:19 /usr/local/lib/libmkl_blacs_sgimpt_lp64.so*
-rwxr-xr-x 1 root root 310K Dec 10 20:19 /usr/local/lib/libmkl_blacs_sgimpt_lp64.so.1*
-rwxr-xr-x 1 root root 166K Dec 10 20:19 /usr/local/lib/libmkl_cdft_core.so*
-rwxr-xr-x 1 root root 166K Dec 10 20:19 /usr/local/lib/libmkl_cdft_core.so.1*
-rwxr-xr-x 1 root root 129M Dec 10 20:19 /usr/local/lib/libmkl_core.so*
-rwxr-xr-x 1 root root 129M Dec 10 20:19 /usr/local/lib/libmkl_core.so.1*
-rwxr-xr-x 1 root root  40M Dec 10 20:19 /usr/local/lib/libmkl_def.so.1*
-rwxr-xr-x 1 root root  12M Dec 10 20:19 /usr/local/lib/libmkl_gf_ilp64.so*
-rwxr-xr-x 1 root root  12M Dec 10 20:19 /usr/local/lib/libmkl_gf_ilp64.so.1*
-rwxr-xr-x 1 root root  13M Dec 10 20:19 /usr/local/lib/libmkl_gf_lp64.so*
-rwxr-xr-x 1 root root  13M Dec 10 20:19 /usr/local/lib/libmkl_gf_lp64.so.1*
-rwxr-xr-x 1 root root  30M Dec 10 20:19 /usr/local/lib/libmkl_gnu_thread.so*
-rwxr-xr-x 1 root root  30M Dec 10 20:19 /usr/local/lib/libmkl_gnu_thread.so.1*
-rwxr-xr-x 1 root root  12M Dec 10 20:19 /usr/local/lib/libmkl_intel_ilp64.so*
-rwxr-xr-x 1 root root  12M Dec 10 20:19 /usr/local/lib/libmkl_intel_ilp64.so.1*
-rwxr-xr-x 1 root root  13M Dec 10 20:19 /usr/local/lib/libmkl_intel_lp64.so*
-rwxr-xr-x 1 root root  13M Dec 10 20:19 /usr/local/lib/libmkl_intel_lp64.so.1*
-rwxr-xr-x 1 root root  62M Dec 10 20:19 /usr/local/lib/libmkl_intel_thread.so*
-rwxr-xr-x 1 root root  62M Dec 10 20:19 /usr/local/lib/libmkl_intel_thread.so.1*
-rwxr-xr-x 1 root root  48M Dec 10 20:19 /usr/local/lib/libmkl_mc3.so.1*
-rwxr-xr-x 1 root root  46M Dec 10 20:19 /usr/local/lib/libmkl_mc.so.1*
-rwxr-xr-x 1 root root  40M Dec 10 20:19 /usr/local/lib/libmkl_pgi_thread.so*
-rwxr-xr-x 1 root root  40M Dec 10 20:19 /usr/local/lib/libmkl_pgi_thread.so.1*
-rwxr-xr-x 1 root root 6.8M Dec 10 20:19 /usr/local/lib/libmkl_rt.so*
-rwxr-xr-x 1 root root 6.8M Dec 10 20:19 /usr/local/lib/libmkl_rt.so.1*
-rwxr-xr-x 1 root root 7.4M Dec 10 20:19 /usr/local/lib/libmkl_scalapack_ilp64.so*
-rwxr-xr-x 1 root root 7.4M Dec 10 20:19 /usr/local/lib/libmkl_scalapack_ilp64.so.1*
-rwxr-xr-x 1 root root 7.4M Dec 10 20:19 /usr/local/lib/libmkl_scalapack_lp64.so*
-rwxr-xr-x 1 root root 7.4M Dec 10 20:19 /usr/local/lib/libmkl_scalapack_lp64.so.1*
-rwxr-xr-x 1 root root  28M Dec 10 20:19 /usr/local/lib/libmkl_sequential.so*
-rwxr-xr-x 1 root root  28M Dec 10 20:19 /usr/local/lib/libmkl_sequential.so.1*
-rwxr-xr-x 1 root root 617M Dec 10 20:19 /usr/local/lib/libmkl_sycl.so*
-rwxr-xr-x 1 root root 617M Dec 10 20:19 /usr/local/lib/libmkl_sycl.so.1*
-rwxr-xr-x 1 root root  40M Dec 10 20:19 /usr/local/lib/libmkl_tbb_thread.so*
-rwxr-xr-x 1 root root  40M Dec 10 20:19 /usr/local/lib/libmkl_tbb_thread.so.1*
-rwxr-xr-x 1 root root  15M Dec 10 20:19 /usr/local/lib/libmkl_vml_avx2.so.1*
-rwxr-xr-x 1 root root  15M Dec 10 20:19 /usr/local/lib/libmkl_vml_avx512_mic.so.1*
-rwxr-xr-x 1 root root  14M Dec 10 20:19 /usr/local/lib/libmkl_vml_avx512.so.1*
-rwxr-xr-x 1 root root  15M Dec 10 20:19 /usr/local/lib/libmkl_vml_avx.so.1*
-rwxr-xr-x 1 root root 7.4M Dec 10 20:19 /usr/local/lib/libmkl_vml_cmpt.so.1*
-rwxr-xr-x 1 root root 8.3M Dec 10 20:19 /usr/local/lib/libmkl_vml_def.so.1*
-rwxr-xr-x 1 root root  14M Dec 10 20:19 /usr/local/lib/libmkl_vml_mc2.so.1*
-rwxr-xr-x 1 root root  14M Dec 10 20:19 /usr/local/lib/libmkl_vml_mc3.so.1*
-rwxr-xr-x 1 root root  14M Dec 10 20:19 /usr/local/lib/libmkl_vml_mc.so.1*
```

Many of the `libmkl_XXX.so` and `libmkl_XXX.so.1` pairs share the same checksum, where `libmkl_XXX.so` should be symbol link of its corresponding `libmkl_XXX.so.1`.

And the same problem exists with `tbb==2021.1.1`.

**Comment by vmalia** [comment]
Hi @storypku 

I verified the issue you mentioned. You are right - the .so files should be symlinks only. This issue does not exist in the direct installation from the oneAPI website though.

I will pass on the bug report to the concerned team within Intel, however, this bug is not related to this project. It is related to the oneAPI MKL product (https://software.intel.com/content/www/us/en/develop/tools/oneapi/components/onemkl.html). To be specific, it is related to the Python distribution of oneMKL (https://pypi.org/project/mkl/).

A clarification of different products/projects under the oneMKL brand name are mentioned in the [FAQs](https://github.com/oneapi-src/oneMKL#faqs) in the README file.

Thank you bringing this to our attention!

**Comment by storypku** [comment]
> Hi @storypku
> 
> I verified the issue you mentioned. You are right - the .so files should be symlinks only. This issue does not exist in the direct installation from the oneAPI website or even via APT.
> 
> I will pass on the bug report to the concerned team within Intel, however, this bug is not related to this project. It is related to the oneAPI MKL product (https://software.intel.com/content/www/us/en/develop/tools/oneapi/components/onemkl.html). To be specific, it is related to the Python distribution of oneMKL (https://pypi.org/project/mkl/).
> 
> A clarification of different products/projects under the oneMKL brand name are mentioned in the [FAQs](https://github.com/oneapi-src/oneMKL#faqs) in the README file.
> 
> Thank you bringing this to our attention!

@vmalia , Thank you for your  prompt response. I will try alternative options you mentioned before this issue got finally resolved.

Regards,
Liu Jiaming

**Comment by fzimmermann89** [comment]
This issue got "solved" in a rather annoying way -- the .so files are now missing from the current pip wheel (no symlink is created instead), so gcc will not be able to find the libraries. 

What would the proper channel be to report this?

Thanks,
Felix

**Comment by mkrainiuk** [comment]
Hi @fzimmermann89, unfortunately pip wheel doesn't support symlinks (https://github.com/pypa/pip/issues/5919) so there is no way so far to do proper fix on our side. We removed files duplication to fix the package size, in [Get Started Guide](https://software.intel.com/content/www/us/en/develop/documentation/get-started-with-mkl-for-dpcpp/top.html) in "Step 1: Install Intel® oneAPI Math Kernel Library" you can find how to modify the link line to make it work with new pip package without symlinks. As long term solution we are investigating how symlinks (or alternative options) could be enabled in pip wheel package format.

**Comment by fzimmermann89** [comment]
Thanks!
But it remains a bit annoying to get a pip package that needs mkl for building to work.

As a humble sugesstion: Could it be possible to create the symlinks when installing the mkl-devel package? That one is currently just a meta package, doesn't have to be a wheel but could have a setup.py that creates the symlinks. Then other packages could simply depend upon mkl-devel for building.

This would be similiar to have e.g. debian handles it with the ...-dev packages.

**Comment by tomashek** [comment]
@fzimmermann89, 
"Could it be possible to create the symlinks when installing the mkl-devel package?"
This is a good suggestion: a non-wheel that creates the symlinks. We have not found a way with wheels to do that. We will look into it. Thank you!

**Comment by rgommers** [comment]
I commented on this problem and potential solutions, plus a workaround to make automatic linking against MKL work in GitHub Actions CI jobs, at https://github.com/conda-forge/intel_repack-feedstock/issues/34#issuecomment-1746461047

Currently, the `mkl-devel` package on PyPI should be considered broken. Asking users to manually amend link arguments can't really be considered a valid solution. Providing pkg-config and CMake files with correct link args (so including `.so.2` explicitly) is a solution that won't increase the wheel sizes. 

More solutions can be thought of as well of course, for example having `mkl-devel` install a `.so` copy for each `libmkl_*.so.2` file in the `mkl` package.

For context: I'm improving the support for MKL in NumPy, and running into MKL packaging problems like this one that make that more than a little challenging. It'd be great to prioritize this issue.

**Comment by mkrainiuk** [comment]
Hi @rgommers ,

I've added a comment to the original issue https://github.com/conda-forge/intel_repack-feedstock/issues/34#issuecomment-1751290342 with the idea of dropping support for devel package in PyPI.

**Comment by ghost** [comment]
libmkl_sycl.so is still missing after a `pip install mkl`, seemingly as part of the correction of above bug.

```bash
docker build --tag xpu:workaround - <<'EOF'
FROM python:3.11-bookworm
RUN pip install --upgrade pip setuptools
RUN python -m pip install torch==2.0.1a0 torchvision==0.15.2a0 intel_extension_for_pytorch==2.0.110+xpu -f 'http://ec2-52-27-27-201.us-west-2.compute.amazonaws.com/ipex-release.php?device=xpu&repo=us&release=stable' --trusted-host ec2-52-27-27-201.us-west-2.compute.amazonaws.com
RUN pip install mkl
ENV LD_LIBRARY_PATH /usr/local/lib/
EOF

docker run -it --rm --network=none --device /dev/dri xpu:workaround 
Python 3.11.6 (main, Nov  1 2023, 13:35:59) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import intel_extension_for_pytorch as ipex
/usr/local/lib/python3.11/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: ''If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/intel_extension_for_pytorch/__init__.py", line 93, in <module>
    from .utils._proxy_module import *
  File "/usr/local/lib/python3.11/site-packages/intel_extension_for_pytorch/utils/_proxy_module.py", line 2, in <module>
    import intel_extension_for_pytorch._C
ImportError: libmkl_sycl.so.3: cannot open shared object file: No such file or directory
```

**Comment by mkrainiuk** [comment]
Hi @chandrahjr, `mkl` package contains only C/Fortran API libraries, for SYCL API please use `mkl-dpcpp` package.

[Here](https://www.intel.com/content/www/us/en/docs/oneapi/installation-guide-linux/2023-2/pip.html#GUID-47CBEF8D-F608-4705-98AA-062A264F6CC6) you can find the full list of available oneMKL package names

**Comment by ghost** [comment]
My journey to understanding the dependency tree for PyTorch xpu led me to below. I am pulling in `intel-basekit` based on the public-facing documentation, but it is rather heavy. I'll try `mkl-dpcpp` directly to see if that can help.

--> request better defining dependencies in the apt packages and pip packages, so that these get pulled in automatically instead.

```bash
docker build --tag xpu:workaround - <<'EODOCKERFILE'
# syntax=docker/dockerfile:1.6

#FROM ubuntu:mantic
FROM python:3.11-bookworm

ARG DEBIAN_FRONTEND=noninteractive
RUN --mount=target=/var/lib/apt/lists,type=cache,sharing=locked --mount=target=/var/cache/apt,type=cache,sharing=locked <<'OSPREP'
apt update
apt upgrade -y
apt install -y python3-venv wget gpg
OSPREP

# PEP668 
ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"
RUN pip install --upgrade pip setuptools

# RUN pip install mkl 
# is broken? due to https://github.com/oneapi-src/oneMKL/issues/64#issuecomment-812632736
# therefore fall back to apt package
# https://www.intel.com/content/www/us/en/developer/tools/oneapi/base-toolkit-download.html?operatingsystem=linux&distributions=aptpackagemanager
RUN --mount=target=/var/lib/apt/lists,type=cache,sharing=locked --mount=target=/var/cache/apt,type=cache,sharing=locked <<'EOMKL'
wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB \ | gpg --dearmor | tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null
echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | tee /etc/apt/sources.list.d/oneAPI.list
apt update
apt install -y intel-basekit
EOMKL

# https://github.com/intel/intel-extension-for-pytorch/issues/412#issuecomment-1715605398
RUN --mount=type=cache,target=/root/.cache/pip python3 -m pip install torch==2.0.1a0 torchvision==0.15.2a0 intel_extension_for_pytorch==2.0.110+xpu -f 'http://ec2-52-27-27-201.us-west-2.compute.amazonaws.com/ipex-release.php?device=xpu&repo=us&release=stable' --trusted-host ec2-52-27-27-201.us-west-2.compute.amazonaws.com

#  libgomp.so.1: cannot open shared object file: No such file or directory
RUN --mount=target=/var/lib/apt/lists,type=cache,sharing=locked --mount=target=/var/cache/apt,type=cache,sharing=locked apt install -y libgomp1

# libze_loader.so.1: cannot open shared object file: No such file or directory
RUN --mount=target=/var/lib/apt/lists,type=cache,sharing=locked --mount=target=/var/cache/apt,type=cache,sharing=locked apt install -y libze1

# torch.xpu.is_available() false
RUN --mount=target=/var/lib/apt/lists,type=cache,sharing=locked --mount=target=/var/cache/apt,type=cache,sharing=locked apt install -y intel-opencl-icd

COPY --chmod=0755 <<'EOENTRY' /docker-entrypoint.sh
#!/bin/bash
# libmkl_intel_lp64.so.2: cannot open shared object file: No such file or directory
source /opt/intel/oneapi/setvars.sh
python3
EOENTRY
ENTRYPOINT "/docker-entrypoint.sh" 
EODOCKERFILE

docker run -it --rm --device /dev/dri --user 0 xpu:workaround
```


```bash
:: initializing oneAPI environment ...
   docker-entrypoint.sh: BASH_VERSION = 5.2.15(1)-release
   args: Using "$@" for setvars.sh arguments:
:: advisor -- latest
:: ccl -- latest
:: compiler -- latest
:: dal -- latest
:: debugger -- latest
:: dev-utilities -- latest
:: dnnl -- latest
:: dpcpp-ct -- latest
:: dpl -- latest
:: ipp -- latest
:: ippcp -- latest
:: mkl -- latest
:: mpi -- latest
:: tbb -- latest
:: vtune -- latest
:: oneAPI environment initialized ::

Python 3.11.6 (main, Nov  1 2023, 13:35:59) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import intel_extension_for_pytorch as ipex
/opt/venv/lib/python3.11/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: ''If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
>>> import torch
>>> torch.xpu.is_available()
True
>>>
>>> print(ipex.xpu.get_device_name(0))
Intel(R) Graphics [0x56a0]
```
