### ISSUE TITLE
Refactor build rules for unit tests

### ISSUE THREAD

**Issue by vrpascuzzi** [oneapi-src/oneMKL#71]
# Summary
Enabling `BUILD_FUNCTIONAL_TESTS` compiles unit tests in both `rng` and `blas` domains.

# Problem statement
If working in a single domain with `BUILD_FUNCTIONAL_TESTS` enabled, irrelevant unit tests are compiled, adding a non-negligible overhead in build times. For example, if one is working exclusively in the `rng` domain and enables `BUILD_FUNCTIONAL_TESTS`, `blas` unit tests are compiled and the total build time is substantially greater than if only `rng` domain unit tests (the relevant tests) were compiled.
```
# `blas' + `rng' unit tests
$ time ( cmake --build <...> -- -j16 )
<...>
real	10m59.050s
user	158m41.756s
sys	2m28.292s
```
vs.
```
# `rng' unit tests
$ time ( cmake --build <...> -- -j16 )
<...>
real	1m24.986s
user	9m7.986s
sys	0m11.170s
```
Of course, going the other direction -- i.e. working in the `blas` domain and compiling `rng` domain tests -- does not add much more compilation time.

# Details
The top-level [`CMakeLists.txt`](https://github.com/oneapi-src/oneMKL/blob/master/CMakeLists.txt) adds the [`tests`](https://github.com/oneapi-src/oneMKL/blob/master/tests) subdirectory if `BUILD_FUNCTIONAL_TESTS` is enabled, then [`tests/CMakeLists.txt`](https://github.com/oneapi-src/oneMKL/blob/master/tests/CMakeLists.txt) builds the GoogleTest infrastructure and adds the [`unit_tests`](https://github.com/oneapi-src/oneMKL/blob/master/tests/unit_tests) subdirectory.

Furthermore, [`tests/unit_tests/CMakeLists.txt`](https://github.com/oneapi-src/oneMKL/blob/master/tests/unit_tests/CMakeLists.txt) currently handles all the condition checking for both domains. The checks can quickly become difficult to manage when adding additional back-ends. For example, `rng` domain tests aren't built if either `cublas` or `netlib` back-end are enabled. Should one wish to add an additional CUDA-based back-end (say, for `cuRAND`), this could be an issue; it conceivable one would want to build tests for both `cuBLAS` and `cuRAND`.

# Proposed solution(s)
Some possibilities:
1. **Clean up `tests/unit_tests/CMakeLists.txt`**
Use conditionals in a cleaner way to separate domain-specific rules more generally.
2. **Split tests by domain, keeping existing `cmake` options**
Refactor the existing `CMakeLists.txt` files to build unit tests based on whether `blas` or `rng` options are specified.
3. **Split tests by domain, modifying existing `cmake` options**
Similar to the previous solution, but also introducing domain-specific options `BUILD_FUNCTIONAL_TESTS_BLAS` and `BUILD_FUNCTIONAL_TESTS_RNG` (or some variation of the names), and keeping `BUILD_FUNCTIONAL_TESTS` as a catch-all.

Other ideas are of course welcome.

**Comment by vmalia** [comment]
Thanks @vrpascuzzi 

We have this task in our todo list, but if you have a patch, feel free to open a PR.

**Comment by vrpascuzzi** [comment]
@vmalia,

I'm currently working on adding `cuRAND` to the `rng` domain. Maybe it'll make more sense -- and eliminate doing things twice -- once it's about ready. It may also make more sense at that point to combine `cuBLAS` and `cuRAND` into a common `CUDA` back-end, similar to `mklgpu` and `mklcpu`.

The difference between 1 and 2 is the former would keep the existing setup and only requires a little rethinking about what to build, while the latter would use a separate `CMakeLists.txt` for each domain (as opposed having build rules for both `rng` and `blas` in the same, somewhat convoluted, file).

**Comment by mkrainiuk** [comment]
@vrpascuzzi, by combining cuBLAS and cuRAND  do you mean from the build options naming perspective?
Do you think it makes sense to split not only test but build completely for domains? Because I believe to work with RNG domain we don't really need to build BLAS at all.

**Comment by vrpascuzzi** [comment]
@mkrainiuk,

I agree -- one should be able to build _only_ back-ends and tests from the domain they wish. The problem here is that currently [`tests/unit_tests/include/test_helper.hpp`](https://github.com/oneapi-src/oneMKL/blob/master/tests/unit_tests/include/test_helper.hpp) uses the same `func` for `mklxpu` so all tests are built for both `rng` and `blas` domains. My thinking of combining cuBLAS and cuRAND was to be consistent with what is already done for `mklxpu` back-ends. But then, yes, we fall back into the trap of needing both `rng` and `blas` domain tests be built.

In [`tests/unit_tests/include/test_helper.hpp`](https://github.com/oneapi-src/oneMKL/blob/master/tests/unit_tests/include/test_helper.hpp),  `TEST_RUN_CT_SELECT` is simplified by checking for which back-ends are enabled; this enables tests for both domains. To get around this, I use:
```
#ifdef ENABLE_BLAS_CUBLAS_BACKEND
#define TEST_RUN_NVIDIAGPU_CUBLAS_SELECT(q, func, ...) \
    func(oneapi::mkl::backend_selector<oneapi::mkl::backend::cublas>{ q }, __VA_ARGS__)
#endif
#else
#define TEST_RUN_NVIDIAGPU_CUBLAS_SELECT(q, func, ...)
#endif
#ifdef ENABLE_RNG_CURAND_BACKEND
#define TEST_RUN_NVIDIAGPU_CURAND_SELECT(q, func, ...) \
    func(oneapi::mkl::backend_selector<oneapi::mkl::backend::curand>{ q }, __VA_ARGS__)
#endif
#else
#define TEST_RUN_NVIDIAGPU_CURAND_SELECT(q, func, ...)
#endif
<...>
            else if (vendor_id == NVIDIA_ID)                                   \
                TEST_RUN_NVIDIAGPU_CUBLAS_SELECT(q, func, __VA_ARGS__);        \
                TEST_RUN_NVIDIAGPU_CURAND_SELECT(q, func, __VA_ARGS__);       \
        }                                                                      \
    } while (0);
```
We could do something similar for the `intelxpu` back-ends, e.g. `ENABLE_BLAS_MKLXPU_BACKEND`, `ENABLE_RNG_MKLXPU_BACKEND`, etc. or similar.

Or, if we combine into a common `cuda` back-end, in the spirit of `mklxpu`:
```
#ifdef ENABLE_CUDA_BACKEND
#define TEST_RUN_NVIDIAGPU_CUBLAS_SELECT(q, func, ...) \
    func(oneapi::mkl::backend_selector<oneapi::mkl::backend::cuda>{ q }, __VA_ARGS__)
#else
#define TEST_RUN_NVIDIAGPU_SELECT(q, func, ...)
#endif
```
There are a number of ways to do this but you probably know best. :)

**Comment by vmalia** [comment]
Hybrid solution using option 2 and 3 from the proposed solutions was implemented and merged. Closing this issue.
