### ISSUE TITLE
Intel oneAPI Installation Not Working

### ISSUE THREAD

**Issue by raaid-tanveer** [oneapi-src/oneMKL#77]
I have been trying to register myself on Intel's Developer Zone to get access to the oneMKL library, but the download page is sending me back to the registration form every time. Is there any workaround to downloading oneMKL without registering first on Intel?

**Comment by rscohn2** [comment]
Click 'continue as guest' instead of logging in.
<img width="560" alt="Untitled" src="https://user-images.githubusercontent.com/1936730/108363001-6f4f6380-71c2-11eb-82ae-c5d3a8e56c01.png">

**Comment by jasukhar** [comment]
@raaid-tanveer please let us know if any further help needed. This project doesn't cover oneMKL binary product and the better way to escalate issues is [oneMKL Forum](https://community.intel.com/t5/Intel-oneAPI-Math-Kernel-Library/bd-p/oneapi-math-kernel-library). You can read more about difference between oneMKL interfaces project and Intel oneMKL release [here](https://github.com/oneapi-src/oneMKL#onemkl).
