### ISSUE TITLE
[CUDA] MKL and RNG

### ISSUE THREAD

**Issue by vpascuzz** [oneapi-src/oneMKL#8]
Hi,

After spending some time getting oneMKL to build with cuBLAS support [1], I can now use oneMKL with CUDA devices. However, I overlooked the fact that this brings in only the cuBLAS backend, and not the random-number generators available for Intel hardware.

Is there any plan to integrate RNGs for CUDA devices, e.g. with a cuRAND backend? While I understand CUDA support is in general experimental, I test my codes on both Intel and NVIDIA GPUs to ensure the software runs on both platforms, i.e. we are aiming for heterogenous solutions.
I'd be very interested to help in such an effort, but don't want to reinvent the wheel if something is already in the works.

Thanks.

[1] https://github.com/intel/llvm/issues/1548

**Comment by marius-cornea** [comment]
Hello, and thank you for your interest in using and contributing to oneMKL. The first stage in our plan to support RNGs consists of adding support for, and integrating our own MKL RNGs. The current plan is to do so around August of this year. Having those available might ease your work of adding support for other RNGs. Are you interested in using certain RNGs and distributions from cuRAND?

**Comment by vpascuzz** [comment]
Thanks for the feedback (and joining github :), @marius-cornea. The strategy makes sense.

I'm not a serious user of cuRAND. Rather, I am porting some CUDA code to DPC++/SYCL that uses the XORWOW (cuRAND default generator) and the uniform distribution. I notice, however, that MKL doesn't natively include XORWOW(?). Probably not a huge deal since it may be difficult to reproduce the same randoms on both Intel and NVIDIA platforms.

Having RNG support for CUDA devices is my primary concern.

**Comment by marius-cornea** [comment]
Hello, that is correct, MKL does not include XORWOW. If you are interested in obtaining the same results on both Intel and NVIDIA platforms, you could try either the Philox, or the MT19937 generator. We will let you know when support for the first oneMKL RNG has been added. That could serve as an example for adding support for similar cuRAND generators.

**Comment by vpascuzz** [comment]
@marius-cornea Sounds good -- thanks.

**Comment by jasukhar** [comment]
Hello @vpascuzz! We will keep this issue open to let you know once APIs for RNG are integrated.

**Comment by vpascuzz** [comment]
Thanks!
