### ISSUE TITLE
Rng mklcpu backend uses ambiguous kernel names

### ISSUE THREAD

**Issue by sbalint98** [oneapi-src/oneMKL#89]
# Summary
In the rng mklcpu backend in `philox4x32x10.cpp` the same kernel names are generated for both the USM and buffer API. This does not cause an error when using dpc++, but according to the SYCL standard, this is illegal and causes problems with some SYCL implementations, tested with hipSYCL. 

# Observed behavior
For example, the kernels at line 328  and 68 in `philox4x32x10.cpp` appear to have the same name. This is a result of the combination of the type of `distr`  and  `philox4x32x10_impl` being used as kernel names. Since kernels are declared for both USM and buffer interfaces with the same type of `distr` this results in ambiguous kernel names.  

# Expected behavior
All kernels should have a unique name.

**Comment by aelizaro** [comment]
Hi, @sbalint98, thank you for noticing this issue, I will fix it. Is this issue blocking you? If yes, I will do it as soon as possible.

**Comment by sbalint98** [comment]
Hi, @aelizaro thanks for the quick response. This issue is not critical for me.

**Comment by aelizaro** [comment]
ok, thank you! Then I expect to fix it by the next week.
