### ISSUE TITLE
Be able to setup oneMKL with the open source intel compiler ( https://github.com/intel/llvm )

### ISSUE THREAD

**Issue by cperkinsintel** [oneapi-src/oneMKL#98]
# Summary
Presently the oneMKL setup revolves around a full oneAPI installation. It would be nice to be able to easily setup and build oneMKL with just the open source version of the intel compiler for SYCL ( https://github.com/intel/llvm ).  

The Intel compiler for SYCL is built with CMake, Ninja and Python 3, and it has the user configure the various dependencies and backends themselves (LevelZero, OpenCL, TBB) with instructions.  Ideally the matching oneMKL setup could build atop that (rather than assuming Conan or sudo access).

**Comment by jasukhar** [comment]
Hi @cperkinsintel! oneMKL already supports llvm compiler (see a readme), as well as have a choice to not use oneMKL binary release and use open source alternatives like netlib. Also for oneMKL binary download we use package managers and users can select conan for automation. Is anything missing?

**Comment by vrpascuzzi** [comment]
@cperkinsintel,

> Presently the oneMKL setup revolves around a full oneAPI installation.

This depends on the target. For example, cuBLAS and cuRAND _do_not_ require oneAPI whatever, and Netlib can be used for BLAS on x86. Since only the interfaces are open source, the Intel MKL library is required for Intel GPUs.

**Comment by cperkinsintel** [comment]
AFAICT, the instructions here: https://github.com/oneapi-src/oneMKL#building-with-cmake  do not work with only the open source compiler.  It won't find TBB and the CMAKE script assumes TBBROOT is set, which would only be set by the oneAPI environment setup script.   But even if I trick it regarding TBB, it still has trouble. 

```
# clang++ is built and all the paths for intel/llvm and its dependencies are on LD_LIBRARY_PATH etc.

export TBBROOT=/rdrive/ref/tbb/lin/2021.2.0.236/
export CXX=$(which clang++)
cmake .. -DMKL_ROOT=/iusers/cperkins/sycl_workspace/oneMKL/ -DTARGET_DOMAINS=rng -DBUILD_FUNCTIONAL_TESTS=False
```

```
-- TARGET_DOMAINS: rng
-- Performing Test is_dpcpp
-- Performing Test is_dpcpp - Success
-- Found TBB: /rdrive/ref/tbb/lin/2021.2.0.236/lib/intel64/gcc4.8/libtbb.so  
CMake Error at /usr/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
  Could NOT find MKL (missing: mkl_sycl_file)
Call Stack (most recent call first):
  /usr/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:445 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindMKL.cmake:54 (find_package_handle_standard_args)
  src/rng/backends/mklcpu/CMakeLists.txt:23 (find_package)


-- Configuring incomplete, errors occurred!
```

**Comment by jasukhar** [comment]
That's correct behavior see https://github.com/oneapi-src/oneMKL#notice-for-use-of-conan-package-manager. If Building with CMake, oneTBB and oneMKL packages must be installed manually. To have packages installed automatically we provide conan support

**Comment by cperkinsintel** [comment]
@jasukhar  By "correct behavior" you are saying that oneAPI has to be installed to be able to use CMake to install oneMKL.  But that's what this issue is about.  It is a request to be able to install oneMKL with the intel open source SYCL compiler _instead_ of requiring a full oneAPI installation.

**Comment by jasukhar** [comment]
You don't need to have a full installation. You can install only oneMKL and oneMKL installation will already include oneTBB. oneTBB is a hard dependency for oneMKL and we redistribute it as part of oneMKL standalone.

**Comment by jasukhar** [comment]
@cperkinsintel does it help to clarify  your question?

**Comment by jasukhar** [comment]
@cperkinsintel feel free to re-open if something wasn't addressed by the clarifications above.

**Comment by jiapei100** [comment]
> That's correct behavior see https://github.com/oneapi-src/oneMKL#notice-for-use-of-conan-package-manager. If Building with CMake, oneTBB and oneMKL packages must be installed manually. To have packages installed automatically we provide conan support

yeah... I just built **oneTBB** from source and have it installed...
Also, I'm trying to manually built oneMKL, but failed with this **ERROR message**.

**Comment by mmeterel** [comment]
What is the error?

**Comment by jiapei-nexera** [comment]
Okay... I got it...

cmake enables
```
 ENABLE_MKLCPU_BACKEND            ON
 ENABLE_MKLCPU_THREAD_TBB         ON
 ENABLE_MKLGPU_BACKEND            ON
```
by default, which seems to make **NO** sense -- to build **oneMKL** of course does **NOT** have **MKL BACKEND** yet..

The following seems to be reasonable, but failed with some **ERROR** as well:
```console
 ENABLE_CUBLAS_BACKEND            ON
 ENABLE_CURAND_BACKEND            ON
 ENABLE_CUSOLVER_BACKEND          ON
 ENABLE_MKLCPU_BACKEND            OFF
 ENABLE_MKLCPU_THREAD_TBB         OFF
 ENABLE_MKLGPU_BACKEND            OFF
```

The error message:
```console
CMake Error at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
   Could NOT find LAPACKE (missing: CBLAS64_file)
```


Well, it looks it has something to do with `ENABLE_CUSOLVER_BACKEND`.

Now, the following configuration works for me, which seems **NOT 100% reasonable**.

```console
 ENABLE_CUBLAS_BACKEND            ON
 ENABLE_CURAND_BACKEND            ON
 ENABLE_CUSOLVER_BACKEND          OFF
 ENABLE_MKLCPU_BACKEND            OFF
 ENABLE_MKLCPU_THREAD_TBB         OFF
 ENABLE_MKLGPU_BACKEND            OFF
```

because I can clearly tell from `/usr/local/cuda/lib64` that **cusolver** comes with **cuda installation**.

```console
 peijia@Katana-GF76-12UE  /usr/local/cuda/lib64  ll *solver*
-rw-r--r-- 1 root root  14M Jun  9 15:00 libcusolver_lapack_static.a
lrwxrwxrwx 1 root root   19 Jun  9 15:00 libcusolverMg.so -> libcusolverMg.so.11
lrwxrwxrwx 1 root root   27 Jun  9 15:00 libcusolverMg.so.11 -> libcusolverMg.so.11.3.4.124
-rwxr-xr-x 1 root root 154M Jun  9 15:00 libcusolverMg.so.11.3.4.124
lrwxrwxrwx 1 root root   17 Jun  9 15:00 libcusolver.so -> libcusolver.so.11
lrwxrwxrwx 1 root root   25 Jun  9 15:00 libcusolver.so.11 -> libcusolver.so.11.3.4.124
-rwxr-xr-x 1 root root 258M Jun  9 15:00 libcusolver.so.11.3.4.124
-rw-r--r-- 1 root root 253M Jun  9 15:00 libcusolver_static.a
```

Anyway, now configured, successfully...

```console
 C compiler: icx was found in PATH, using icx
 TARGET_DOMAINS: blas;rng
 Looking for dpc++
 CMake Deprecation Warning at deps/googletest/CMakeLists.txt:53 (cmake_minimum_required):
   Compatibility with CMake < 2.8.12 will be removed from a future version of
   CMake.

   Update the VERSION argument <min> value or use a ...<max> suffix to tell
   CMake that the project does not need compatibility with older versions.

 Found CBLAS: /usr/lib/x86_64-linux-gnu/libcblas.so
 Found CBLAS: /usr/lib/x86_64-linux-gnu/libblas.so
 Found CBLAS: /usr/include/x86_64-linux-gnu
 SYCL_DEVICE_FILTER will be set to the following value(s): [cuda:gpu] for run-time dispatching examples
 SYCL_DEVICE_FILTER will be set to the following value(s): [cuda:gpu] for run-time dispatching examples
 Configuring done
```



However, in the end, failed to build:

```console
dpcpp: warning: CUDA version is newer than the latest supported version 11.5 [-Wunknown-cuda-version]
dpcpp: error: cannot find 'remangled-l64-signed_char.libspirv-nvptx64--nvidiacl.bc'; provide path to libspirv library via '-fsycl-libspirv-path', or pass '-fno-sycl-libspirv' to build without linking with libspirv
```

What can I say????


Therefore, for intel packages, download and use them...

**Comment by mmeterel** [comment]
by default, which seems to make NO sense -- to build oneMKL of course does NOT have MKL BACKEND yet..

@jiapei100  I am puzzled with this comment: Here, you are trying to build "oneMKL interfaces" which is different than "MKL BACKEND". mklcpu and mklgpu backends come from Intel oneMKL product, which can be downloaded from oneAPI Base Tool Kit. For more information on the differences between oneMKL interfaces and Intel oneMKL, please see [FAQs](https://github.com/oneapi-src/oneMKL#faqs).
To be able to use NVIDIA backend, you do not need MKL backends, which can be controlled using CMAKE variables, as you pointed out. 
One more thing I want to point out is: NVIDIA backends are supported through LLVM compiler. (See [here](https://github.com/oneapi-src/oneMKL#linux))
